### ISSUE TITLE
Implement Layout and Navigation on the Wallet Page

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#10325]
## Description

Implement navigation logic for the Rewards/Wallet page and update the Explore page URL to align with platform behavior for both mobile and desktop.

## Project Owner
@dillchen

### 1a. **Page Navigation from Nav Bars**

- Description: Add logic for accessing the Rewards/Wallet page from both mobile and desktop:
- Mobile: “Wallet” button in bottom navigation.
- Desktop: allows user to navigate to this from the "top nav bar" (see designs)

### 1b. **Page Navigation from Profile Dropdown: updated**

~~Replaces “Wallet” option under the Profile dropdown menu~~

Profile dropdown behavior remains unchanged for:

- Open Wallet (optional dropdown) -> same behavior (visible and only to Magic users)
- Referral Link -> (same behavior)

Profile dropdown behavior to be updated for:
- My Transactions -> opens up to the rewards page with the Token Transactions Table visible to the user.

### 2. **On Rewards Page Behavior**

- See All Redirect: Ensure clicking “See All” from the Rewards Page redirects users to the correct table and tab (with dummy data for now): 1) Earnings Tab 2) Balances Tab 3) XP Tab

- Please note, there is a "tab button row" across the top of the page here. Clicking each tab, should change both the displayed card and the table respectively. For example, if I click `Referral Earnings`, I should see the card and referral earnings table

<img width="310" alt="image" src="https://github.com/user-attachments/assets/601ce4b3-f444-4090-9637-212e101a2e95" />

## Design Links and Design Screenshots

<img width="780" alt="image" src="https://github.com/user-attachments/assets/18969b21-492b-4a95-9ea4-f50b306999f2" />

**Mobile Bottom Nav**

<img width="440" alt="image" src="https://github.com/user-attachments/assets/5c6adc59-3faf-478e-bf56-4710f7ef09dc" />

Same [link](https://www.figma.com/design/3P2W6qekniGbODrYwPD4n8/Rewards-Page?node-id=40-130&p=f&t=IxFSJFJVXlyjcBg9-0) as in #7775

**Comment by masvelio** [comment]
Some of these things from description are not clear to me:

1. > Desktop: Replaces “Wallet” option under the Profile dropdown menu, allows user to navigate to this from the "top nav bar" (see designs)

We don't have "wallet" option in the profile menu. Or you mean "open wallet", but this is optional - only for magic sign-ins?
Also, I can't see "wallet" on the designs in top navbar on desktop. It is only on mobile, which is weird because wallet on mobile should be on bottom nav. Yeah, let's clarify it.

![image](https://github.com/user-attachments/assets/913c6994-5511-429e-8187-732535bc6147)
![image](https://github.com/user-attachments/assets/4329891c-d34b-46d5-a861-beb98a316dc1)

2. > Update the platform URL for the Explore page to /wallet.

This is also not clear to me. We call explore page this => https://common.xyz/communities but I don't think this is what it meant here? Also new page is called Reward so do we want to use /wallet url and icon?

**Comment by sssssabinaaa** [comment]
1. Sorry, yes that wallet modal should be in the desktop as well as mobile. Updating the figma to reflect this now
2. Deferring this to @dillchen

**Comment by dillchen** [comment]
@masvelio updated the OP to reflect that the URL should be /rewards

**Comment by dillchen** [comment]
> We don't have "wallet" option in the profile menu. Or you mean "open wallet", but this is optional - only for magic sign-ins?

Originally my thought was to include 2 points of entry on Desktop and Mobile
- Desktop: 
-- Top Nav Bar (Click Wallet Icon, or Click XP Progress Bar)
-- Profile Drop Down (Click Rewards -- which should be shown to all users, Rewards would replace Open Wallet, because the Wallet functionality would now be directly on the page

- Mobile 
-- Bottom Nav Bar (Click Wallet Icon)
-- Profile Drop Down (Click Rewards -- which should be shown to all users, Rewards would replace Open Wallet, because the Wallet functionality would now be directly on the page) -- 

However, now, I think this is what the behavior of the profile dropdown should be Items to keep:

- Open Wallet (optional dropdown)
- Referral Link 

Items to Update
- My Transactions -> opens up to the rewards page with the Token Transactions Table visible to the user.

> Also, I can't see "wallet" on the designs in top navbar on the desktop. It is only on mobile, which is weird because wallet on mobile should be on bottom nav. Yeah, let's clarify it.
