### ISSUE TITLE
Can't switch community addresses

### ISSUE THREAD

**Issue by 7racker** [hicommonwealth/commonwealth#1491]
**Prob**
https://youtu.be/gbep6pTxHSY?t=370

**💩work arrrrround**
https://youtu.be/gbep6pTxHSY?t=450

**Solution**
Clicking new address in user dropdown button should reload 

- url
- only relevant UI and divs. not full page reload

**Comment by gdjohnson** [comment]
So, this is not actually a bug, but more a design decision. 

If you think the behavior is confusing, I think that's grounds for us to reconsider. Pinging @zakhap so he can be a part of this decision-making.

Basically, you want the behavior to be, that if a user switches addresses _while on their own profile page_, they are redirected to the new address's profile page automatically. 

The address switching is working just fine here. That's why you lose the "Set Identity" and "Edit" buttons. You're no longer on the address of the profile you're viewing, so you get a different view.

What's not happening is the profile page isn't switching automatically. I get why that behavior is appealing; it also has downsides. E.g., if you're switching between addresses in order to transfer tokens, or preview your profile from an outside address's perspective, you want to remain on the original profile page pre-switch. It could be hugely annoying to switch up on them automatically, especially since the "Back" buttons risks taking them to a page state where they're viewing as their pre-switch address. 

Furthermore, there's a structural simplicity: you can switch addresses from anywhere in the app—so this profile redirect would be a deviation from expected behavior, unless we _always_ redirect to the new addr profile post-switch, which would be a HUGE hassle to users—and the button to view your active address profile is always the same.

So, I can see both sides here. I can totally see where the confusion comes from: "I'm on my own profile; I switch addresses, I should see the new profile." But the profile is just an address listing like any other page on the site, and you remain on it as you toggle through addresses. But to be clear, I don't believe anything's actually broken from the timestamped video sections.

**Comment by jnaviask** [comment]
cc @CowMuon
