### ISSUE TITLE
Address design issues & code structure on manage community panel

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#179]
- The cui-switch components look off - why is the round toggle larger than the div it fits into?
- The add webhook button should be assigned an intent of none, so it matches the promote admins button, and doesn't change color when moused over
- There should be no underline under admins' usernames
- CSS classes should be .UpperCamelCase if they are components, .snake-case otherwise. For example, .membersList should be .members-list
- The height of this form often changes unexpectedly, including when the dialog opens, and when switching between tabs
- The way components are named seems quite arbitrary; components are variously called panels, forms, or otherwise differently.
   - *The component exported in a file should always have the same name in javascript as the file, AND the same name as the component's parent CSS class*
    - CSS classes should be .hyphenated-snake-case, never .camelCase, unless they are the parent class for a component.

**Comment by zakhap** [comment]
Things I've attended to in `zak.cap-bugs`: 
- [ ] The cui-switch components look off - why is the round toggle larger than the div it fits into?
- [x] The add webhook button should be assigned an intent of none, so it matches the promote admins button, and doesn't change color when moused over
- [x] There should be no underline under admins' usernames
- [ ] CSS classes should be .UpperCamelCase if they are components, .snake-case otherwise. For example, .membersList should be .members-list
- [ ] The height of this form often changes unexpectedly, including when the dialog opens, and when switching between tabs
- [ ] The way components are named seems quite arbitrary; components are variously called panels, forms, or otherwise differently. 
- [ ]  _The component exported in a file should always have the same name in javascript as the file, AND the same name as the component's parent CSS class_
- [ ] CSS classes should be .hyphenated-snake-case, never .camelCase, unless they are the parent class for a component.

**Comment by zakhap** [comment]
Spent a while trying to figure out why the Switch Component is off–couldn't diagnose exactly.

**Comment by zakhap** [comment]
Regarding arbitrary naming conventions, how should I name things in the future? 
I was trying to be clear by differentiating between Forms, Panels (left and right), Rows, etc. but apparently it was not clear.

**Comment by zakhap** [comment]
@raykyri I'd love some guidance on these issues before I finish up the associated PR: #264

**Comment by raykyri** [comment]
I think a couple of main things

1) is this whole module called the admin panel or the manage community dialog?
2) it would be easier to understand if there was a more clear hierarchy of components. there is just a lot of terminology here and it takes a lot of time to parse the graph to be able to do any more work on this table:

- panel contents (admin_panel_contents.ts)
- panels (admin_tab_panel.ts)
- tables (chain_metadata_management_table.ts, community_metadata_management_table.ts)
- rows (input_property_row.ts, manage_roles_row.ts, toggle_property_row.ts)
- forms (upgrade_roles_form.ts)
- tabs (webhooks_tab.ts)

- Is a tab panel the same thing as a tab?
- I would name the various rows so it is clear from their filename what parent components they sit within. Or just put them in the parent table's file tbh. Does not seem helpful to have them split out
- If there are other places that other components have been separated into their own file, but they are substantially the same as their parent component, also combine those

IMO there should only be ~one layer of nesting of components inside each folder.

**Comment by raykyri** [comment]
On the switch component, that's fine, I'll take a look at that later
