### ISSUE TITLE
Update to Node v18

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#2162]
This issue was previously to upgrade to Webpack v5, which was intended to include upgrading to Node v16, however we've upgraded Webpack and still have to upgrade Node.

**Comment by Librechain** [comment]
Was just about to add this as an issue because its sent the entire project into dependency hell for me. Was trying to spend this up to preview what it was all about. Doesn't compile because of conflicting dependencies. Current webpack requires lowering npm version but doing so conflicts w the version required for all other packages (>=16)

**Comment by jnaviask** [comment]
As a quick fix, you can run `yarn --ignore-engines` to get the installation working. We're planning to upgrade to node 16 soon.

**Comment by CowMuon** [comment]
Let's go ahead and upgrade to Node 18 (LTS). EOL for Node 16 is actually this September. (It was brought forward bc of OpenSSL 1.1 release.)
