### ISSUE TITLE
Add caching for on-chain identities

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#239]
- We don't cache on-chain identities right now, which means we make more requests to the chain than necessary
- Add caching for that & scale to any other areas of chain data that seem like a good idea
    - Don't do this for balances
    - Do this for identity
- Ideally do this in a way where it's scalable to proposals and councillors
- Circulate a quick spec?

**Comment by dillchen** [comment]
Some Todos pulled from Slack: https://hicommonwealth.slack.com/archives/CFAJ5PKM5/p1589595227061100

**Comment by jnaviask** [comment]
We can probably fetch and maintain these things via chain events and store them as chain entities. But it wouldn't necessarily reduce the amount we fetch from the node on the client unless we decide we want to back identities/etc with data from the server.

**Comment by jnaviask** [comment]
Looks like the `client/scripts/controllers/chain/substrate/account.ts` file has a function called `identity()` that grabs the identity from the API, but we also have a `client/scripts/controllers/chain/substrate/identity.ts` file that maintains a cache. We should be using the identity cache instead of fetching from chain every time.

**Comment by jnaviask** [comment]
Update on this issue is: we need to create a cache backed by localStorage in order to persist identities across refreshes. This cache must clear, though, if we switch chains, and should clean itself out at some point to avoid wasting space.
