### ISSUE TITLE
Implement New Routing Layer

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2434]
After discussing with Jake, the plan is to do the Router conversion by EOD Tuesday Jan 10. 

Assigned to @jnaviask  pairing with @mhmulford0 

Please make sure to keep Routing Section of [State of React](https://www.notion.so/12-30-State-of-React-40a0aa870e524dd78c36030bf8963cfa) documented up-to-date, so that anyone on Front End team can read that section and understand how to pick up any work here.

**Comment by jnaviask** [comment]
Progress, on the branch: marcin.react-interop-testing => was able to get props passing through layout, no need to hardcore scope anymore.

Next step: get redirects across pages working, i.e. `setRoute` in the interop layer.

**Comment by jnaviask** [comment]
Most recent push gets one example of a working redirect in `views/pages/discussions/thread_preview.tsx` . Note that it requires wrapping the ClassComponent into a FunctionComponent to take advantage of the `useNavigate` hook, which is injected into the ClassComponent's `props` and used to navigate.

We should figure out a way to generalize this, perhaps as a HOC or some other sort of wrapper, as we will not be able to use the global `setRoute` function within the interop layer at all.

Also note that the ViewThread page is completely broken, because of the mess that is our Quill implementation (but it does redirect to it properly!).

**Comment by jnaviask** [comment]
Latest push adds a `NavigationWrapper` function that injects a `navigate` prop for use in components.

**Comment by jnaviask** [comment]
> HOC? You fancy. So what's the plan for setRoute once we are ready to remove the Interop layer? 

SetRoute will actually get deprecated immediately, as this method requires updating components that use redirect. It'll take a bit of elbow grease though.

**Comment by jnaviask** [comment]
Added most of the routes today, and some ClassComponent helper methods for setRoute and navigateToSubpage, only usable by components wrapped with NavigationWrapper. Implemented NavigationWrapper + the new methods for a few components, but needs to be added across the codebase / as needed. Also, there exist many outstanding redirects that do not conform to the pattern of routing within a component -- these uses will require rethinking or refactoring.

**Comment by CowMuon** [comment]
Can we either close this issue if routing layer is now working 100% and there is nothing left to be done, or if there is _anything _ outstanding at all on that, add it here for completion.

**Comment by masvelio** [comment]
I am working on this currently as a part of applying `app.ts` refactor into react project. Routing is not working 100%, there are still things to figure out like handling custom domains

**Comment by zakhap** [comment]
To confirm for tomorrow (based on our 1-on-1): 
- Finish router for normal (not custom domain) routes (will be in separate issue)

We want to get this merged prior to the reactathon Wednesday
