### ISSUE TITLE
API remaining work

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2444]
Meaning mainly Swagger, so we can ship what we've been calling API v2. (Most definitely abusing the term version here, so let's pretend that never happened. Because we actually will need real API versioning.  Expectation here is we didn't actually set `version` to 2 in our OAS.

**Comment by kurtisassad** [comment]
Swagger is already set up, the remaining work is to go over with someone to ignore sensitive fields from post request

**Comment by CowMuon** [comment]
Basically ready for review, @kurtisassad & @rvmelkonian will discuss today and move card to Read for Review.

**Comment by CowMuon** [comment]
Blocked: Requires Permissions PR #2402 to go in first.

**Comment by kurtisassad** [comment]
Remaining work: post roles + get jwt routes

blocked until Jake gets back for security discussion.

**Comment by CowMuon** [comment]
Given that the permissions discussion call happened last week, is this still blocked?

**Comment by CowMuon** [comment]
Only thing needed is login. Expected to take about a day for post/delete requests. What did we we decide on JWTs?

**Comment by kurtisassad** [comment]
> Only thing needed is login. Expected to take about a day for post/delete requests. What did we we decide on JWTs?

It was decided that we did not want to go ahead with the JWT tokens. Instead we will verify user's ownership of the addresses based on the following way (for clarity APIKey = key from kong, key = public key from private/public key pair):

1. User gets APIKey from kong
2. User signs APIKey with their private key, they will send (signed(APIKey))
3. We verify the users APIKey is valid and also signed with their key
4. We then allow/disallow the user access to the requested external api

**Comment by kurtisassad** [comment]
On further digging into the code the initial workflow seems not possible. The reason for this is that, currently we have the account verification handled by the webwallets. We don't store the public key of the user, so basically I will need to implement a method on the backend for every webwallet (but will use the specific webwallet based on the Addresses.wallet_id), to go through their API in order to check if the signed message was signed by the account.

**Comment by jnaviask** [comment]
What the user should provide:
- public key = address + APIKey + signature(APIKey)
- We query the address against the Addresses table
- We use verification code similar to /verifyAddress (maybe abstract it?) to validate the combo of the three items (pubkey, string, signature)

The main flaw in this approach is replay attacks. If I intercept your request, then there's nothing stopping me from doing as I wish, because there's no expiration of the signature or way that we "consume" the token, akin to how we generate a random string with an expiration time on login.

However, this may not be a significant enough security issue to make this scheme unworkable. cc @MuonShot to ensure we're comfortable moving forward with this.

**Comment by kurtisassad** [comment]
Just as a side note with this approach the users will only be able to use the API on a per-account basis (not a per user basis).

**Comment by jnaviask** [comment]
If they own one address, they're assumed to own the entire user object.

The bigger issue here is if an address is registered on two separate users (e.g. 0x123 on dydx and 0x123 on ethereum).

**Comment by kurtisassad** [comment]
After meeting last Wednesday, it was decided we would hold off on this for further consideration of how to perform user validation.

**Comment by jnaviask** [comment]
Stale.
