### ISSUE TITLE
Fix Quill rendering on React (Thread + Comment Loading Race-Condition)

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2460]
Quill is broken in React, per the ViewThread page.

**Comment by raykyri** [comment]
fixed some render issues. remaining things to flag:

- the mithrilInterop layer seems to be missing significant parts of mithril functionality - e.g. adapting oncreate() and other lifecycle methods automatically, and handling m.redraw() cycles when props are updated. this means that subcomponents may not be redrawn when the data passed to them is updated.
- this is a bug on view_thread where the thread body loads sometimes, but not at other times, likely due to a race condition as the bug is moderately stick (will work fine for a while, and then break for a while, etc)
- links and other layout controls don't work.

**Comment by CowMuon** [comment]
What's the status on this? Seems like we have some decisions to make around how we get from some of the ways we've been utilizing [sic] Quill to how we use it with React. (We're not using Quill API to best of my knowledge.) 

We would have to choose between 2 different Quill for React implementations: 
[zenoamaro/react-quill](https://github.com/zenoamaro/react-quill) - Seems to be the most widely used library for this.
[gtgalone/react-quilljs](https://github.com/gtgalone/react-quilljs) - Smaller, less well maintained project that has also been mentioned as a possible option. 

WRT to which Quill for React library, my main question would be what does react-quilljs do/have that react-quill doesn't? 

Related to this is the question of whether we want to continue to support markdown which we feel is not especially valued by our communities. Currently we are saving in markdown format, not quill deltas. Need to make decision here. Look at usage, raise at 2/1 partner meeting.

**Comment by raykyri** [comment]
Quill uses ContentEditable, so I'm not sure that we can't use TextField/Input MUI components. I'd generally expect an sophisticated editor to require some amount of customization, and while we're not in the editor business we are in the content creation and text composing business.

- `react-quilljs` looks like about 25 lines of core logic, plus configuration, for ~100 LOC total. 
- `react-quilljs` looks like about 100 lines of core logic, plus configuration, for 550 LOC total. 
- I would agree that it's probably easiest to write our own wrapper. 
- How do we feel about porting over the existing Quill components?
- If we are focusing on just rich text, then the case for redoing the component gets stronger as 95% of the complexity we have right now is about managing Quill to Markdown. But gathering feedback on Markdown at the partner meeting seems like the right place to start. If we're keeping Markdown, then it may be a good idea to preserve as much of the old editor component as much as possible.

**Comment by jnaviask** [comment]
As a result of customer discussion, we're not deprecating either Markdown or Quill functionality. Cost of this decision: unknown.
