### ISSUE TITLE
Implement code splitting across the Commonwealth app.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2461]
TODO: 

- [x] write down goals and outcomes etc @kurtisassad 
- [ ] What are remaining tasks here @jnaviask 
- [ ] https://github.com/hicommonwealth/commonwealth/issues/2618

**Comment by kurtisassad** [comment]
[Allows for easier webpack runtime debugging: ](https://github.com/hicommonwealth/commonwealth/pull/2450)

goals:
reduce FCP time by reducing the time it takes to run the webpack runtime.

**Comment by jnaviask** [comment]
- Merge dillon's PR
- get import type in

**Comment by kurtisassad** [comment]
Remaining work.

[#2618](https://github.com/hicommonwealth/commonwealth/issues/2618)
Code split remaining crypto libraries. We have decided to defer this until we refactor app structure, so that the code splitting can be used in less places resulting in cleaner and more logically consistent code/reasoning.

**Comment by CowMuon** [comment]
We decided as a fam this will follow the React-a-thon.
