### ISSUE TITLE
Crowdfunding QA/Backing Flow

### ISSUE THREAD

**Issue by 0xdantrinh** [hicommonwealth/commonwealth#2491]
Document Outlining The QA Process: https://www.notion.so/hicommonwealth/QA-Crowdfunding-and-Prepare-for-Production-05f62da62cb843a58fa4215e70a103b5

Following Steps to Complete Crowdfunding for Production:

1. Need to add a UserBalance UI for the project Token in view_project component
2. Need to add token approval flow for this project Token [https://www.notion.so/hicommonwealth/Create-Approval-Interaction-Button-within-Crow[…]ve-the-Project-Accepted-Token-08aba04a767248438c01d3e4e304d380](https://www.notion.so/hicommonwealth/Create-Approval-Interaction-Button-within-Crowdfund-to-Approve-the-Project-Accepted-Token-08aba04a767248438c01d3e4e304d380)
3. Need To get Back Button working by linking all the above with this
4. Need to get Curate Button working (This is buggy and we should split this into a separate branch to prevent Monolith branch)

**Comment by dantrinh** [comment]
1. UserBalance simple UI present now in View_Project for whichever the accepted project token is 
2. Token Approval Flow Exists now for Backing and Curating Buttons (aka we now approve the project to spend the accepted project token of the signed in wallet)
3. Back Button is Working


Outstanding work to split into separate Tasks:
1. UI should display the current token's symbol rather than ETH because Curated Projects accept any accepted Project Token
2. We should change the rest of the fields that display (total funded, etc) given these downstream changes
3. Curate is buggy and the call to the contract is not working (this needs to be thoroughly debugged and might take a day or require launching updated contracts)
