### ISSUE TITLE
Investigate Flink for Batching Notifications 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2536]
After discussing the need to batch notifications, which are currently handled as an ongoing stream of individual events, which is not scalable, let's investigate using Dataflows for this, ie. Apache Beam. In particular let's think about using Flink as our job runner.

**Comment by timolegros** [comment]
While Flink is powerful and could be useful in this case, it is not available as a Heroku add-on which means we would need to host our own Flink instance. This is not ideal at the moment because it increases our architecture, development, and deployment complexity for little gain. I think it's best to close this issue for now and revisit our options when we refactor notifications using a holistic approach.
