### ISSUE TITLE
Increase minimum dynos

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2545]
We're seeing Heroku scaling up dynos for the app from 1 to 2 and even 3 at least once every hour going all the way back to the window for this log data (1/17 or about a week ago.) On the face of things this seems to indicate we need to be running the app on a minimum of 2 dynos. 

Let's increase minimum dyno's from 1 to 2, and for the rest of the week we will look at how it is scaling.

**Comment by timolegros** [comment]
The minimum number of dynos has been scaled to 2. Will revisit metrics on Friday.

**Comment by timolegros** [comment]
Went from averaging 150 Request timeout errors every 2 hours to averaging somewhere in the 30's so far.

**Comment by timolegros** [comment]
Unfortunately, I think scaling the minimum dynos was not as beneficial as first hoped. Given the limited data available it's hard to tell but Heroku seems to be scaling just as frequently from 2 -> 3 dynos as it did from 1 -> 2 dynos. It's important to note that Heroku scales based not on CPU or memory usage but on route response times. This leads me to believe that rather than dyno load being the issue here it could simply be that we have unstable routes that sometimes have really long response times regardless of dyno load (most likely DB related).

Thus I would advise that we scale the minimum dynos back down to 1 and observe once again if any significant changes occur. If response times and error rates remain about the same then we will have confirmed that dyno load is not a bottleneck for our response times.
