### ISSUE TITLE
Easy Analytics Win

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2663]
On the API demo call today it came up that they have an analytics need that may be easy & straightforward to implement. 

Can we send user data base on JWT use to Datadog, and then query off there with an API call? 

Some Questions: 
Why would we use Datadog for that, rather than our own Datastore? What do we get by using Datadog for that? 
What are the actual requirements here? It's great we think there's an easy win here, should we just go ahead and implement it without any planning or documentation? 
Which workstream is this for? Is this new work? Is this a better way to complete an existing request? Is this just a random hack? 
Where does this wire up to the API? What module has responsibility for this functionality? 

Let's discuss implementing this, and if it's a green light, what the targets & timeline for execution are.

**Comment by kurtisassad** [comment]
>Why would we use Datadog for that, rather than our own Datastore?

The issue is that a relational database is not a great place to store timeseries data. It is much more efficient to use some no-sql solution, which datadog provides and we already have set up.

The other option is that we set up our own no-sql db, or use our relational database (which already takes forever to query). Flooding it with information would not be so great for performance purposes I think.

>What are the actual requirements here?

Actually requirements as I remember from the call were (paraphrasing) "We want to see analytics of user activity so that we can reward active users".

>Which workstream is this for? Is this new work?

This would be adding towards the API

>Where does this wire up to the API?

We have StatsDController which sends data to datadog this is the very easy part to set up.

Reading the data off datadog we have not implemented yet, but its a simple REST API, so I don't think it would be too much trouble.

>what the targets & timeline for execution are.

In my estimation it would take about a day. No timeline was specified, but we had told the customers that we would implement improvements by next month (more of a general statement, not directly related to this specific piece of functionality).

**Comment by jnaviask** [comment]
I am highly suspicious about the plan of _using datadog to deliver client metrics, as part of our product_. The tool is meant for internal usage and this use case would go against Datadog ToS. We should design our own solution instead.
