### ISSUE TITLE
Discussions lose comment data/buggy refresh: Perhaps Identity related

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/commonwealth#272]
## Description

The discussions page for a chain (Edgeware) community goes through an odd refresh/reload cycle. It seems state exists correctly on first load and then some state is lost/deleted causing the view to go out of sync

## *Who* is the bug affecting?

All users of the community

## *What* is affected by this bug?

Proper ordering of threads in discussions

## *When* does this occur?

On load/on refresh

## *How* do we replicate the issue?

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/13153687/83092263-29fa6d00-a05a-11ea-8a61-2b11b0083307.gif)

## Expected behavior (i.e. solution)

This reordering/loss of data should not occur

**Comment by raykyri** [comment]
It seems like comments have been cleared after the reload, so the root cause of this is probably related to the refreshAll issues.

This seems like the most relevant issue: https://github.com/hicommonwealth/commonwealth/issues/226

However that issue is written in a way that's somewhat unclear so I'll update this issue and put it on this week's sprint board.
