### ISSUE TITLE
Adjust `navigateToSubpage` to react-router

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#2748]
this is a follow up ticket to #2669

**Comment by jnaviask** [comment]
I wanted to emphasize that this is, IMO, _the most important next task_ in the React migration, because this is what will make the site navigable, allowing everyone to click around and discover what does and doesn't work. We should definitely have navigateToSubpage ready to go before Reactathon 2, or at least very clear instructions on how to implement it across the codebase.
