### ISSUE TITLE
Weekly Email Digest Script 

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#2839]
## Description
PRD: https://www.notion.so/Email-Digest-Notification-38628d130a2c4d6398eeca1beabbca03

This script will need to be run weekly, should be executed programatically.
Prerequisites:
- SendGrid Template ID (NOT NECESSARY TO EXECUTE ON THIS WORK)

This Script should run in two parts:
1. Formatting the data for each community
2. Formatting the email for each user (reusing the data from part 1)

Part 1, getting relevant data for each community:
1. For each Community on Commonwealth, storing this data in a map (`chain => ThreadData[]`),
  a. Get the 2-3 most active threads for the community, in order of "most active" descending (formula: 60% comments count, 40% reaction count, within last week)
    - Thread Title, 300 characters of body, comment count, view count, reaction count, author (name, avatar url), thread id (for generating link /chain/discussion/id)
2. each community should also get an "activity score" => (40% thread counts, 30% comments, 30% reactions). this is for sorting the order of the email. 

Part 2, formatting the email: 
1. for each user that 1. has an email, and 2. has `emailNotificationInterval === 'weekly'`: 
   - for each community they are a member of, sorted by community score descending, get the ThreadData[] from the map.  
   - format into large object
   - send to SendGrid

**Comment by alexyoung23j** [comment]
@zakhap do we have other cron jobs running anywhere? Should I write this as a route and then call it with an airplane cron job or something?

**Comment by alexyoung23j** [comment]
Potential Testing plan:

1. test out the script with email sending turned off on beta (ensure the correct objects are getting created) with our db that has users with email notifs turned on

2. test out the script with email sending turned on on frick since that db shouldn't have any users with emails turned on yet (correct me if I'm wrong about that part). Then we can sign up for emails and ensure the emails only send to a few commonwealth emails

**Comment by alexyoung23j** [comment]
A question for @jnaviask and @MuonShot: This script currently runs in a route called runDigestScript. This is a slow route because we have to process each user individually and create/send their email- with a substantial number of users it likely take on the order of ~30 seconds. Is this a problem? I thought we have a maximum route resolution time set or something to that effect. On staging, it runs correctly and sends emails as expected, but the route returns a 503.

**Comment by CowMuon** [comment]
If we are getting service unavailable (ie the 503 error) this is not really ready to go out. We need to debug the 503. First thing is to confirm if it's just hitting the 30 second time out, next is to know what the actual execution time is. Preferred option is *not* to just increase the timeout, but handle this more efficiently. I can take a look at the code on that branch later.

**Comment by alexyoung23j** [comment]
Have identified that this is a heroku timeout[ value problem](https://devcenter.heroku.com/articles/request-timeout#:~:text=An%20application%20has%20an%20initial,the%20connection%20will%20be%20terminated.). And this is not changeable, and probably shouldn't be changed even if we could as you said. Another strategy is needed then- we can probably optimize these queries a bit but given that this script will be used to send emails to potentially many users, I don't know that we can ever have a super safe guarantee that it will run in under 30 seconds? We can just not await the async script run and return a success before it finishes, but then we lose the error handling.

**Comment by alexyoung23j** [comment]
Resolved- we will not await the completion of the script in the route, and instead send a confirmation email when the script is completed. Airplane route updated to reflect this.
