### ISSUE TITLE
Script to copy production follower to selected development database.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2840]
Add as yarn command, for easy "bump to master". Follower is commonwealth-beta::RED.

**Comment by jnaviask** [comment]
Should be a package.json command that takes a flag which specifies which database to blow away.

WARNING: DO NOT ACCIDENTALLY COMMIT THE URLS OF OUR DATABASES!

**Comment by CowMuon** [comment]
Something like:
`heroku pg:copy commonwealth-beta::HEROKU_POSTGRESQL_RED_URL --app commonwealth-staging`

Would be great to benchmark the following times: 
1. Current time to deploy to `Frack`. (presumed to be on par with Prod)
2. Time above command takes to complete. 
3. New deploy to `Frack` time.

The salient questions here are: 
- How much deploy time this takes?
- (Keeping in mind we won't be "deploying" as such in future)
- Plan to reduce surface area of manual CA (nee QA) on Frick/Frack?
- What is delta b/w Frick/Frack deploy times? 
- Is there any need (current/anticipated) for Frick to be non-ephemeral?

**Comment by CowMuon** [comment]
blocks #2964

**Comment by kurtisassad** [comment]
1. Difficult to say because we would need an average over multiple runs to be confident in the estimation, but one run has taken me ~27m before becoming available to requests.
2. Takes 242 seconds, copy size is around 4GB, giving us a 16mbps transfer speed.
3.  max(1, 2) assuming our release script in procfile looks like `yarn reset-frack-db || [old release script` . But the issue is the db time will scale much faster than the server time. If the db becomes too large it will cause performance issues, and will also require us to refactor our server to wait to make sure the db is start up (or at least hang until db is start up).

**Comment by CowMuon** [comment]
Had to bounce the PR back to draft as it appears still not be copying from RED.
