### ISSUE TITLE
Show More trims the whole page

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#2869]
Example weirdness

https://commonwealth-react.herokuapp.com/redacted-cartel/discussion/3975-rff-rip-proposal-process

**Comment by jnaviask** [comment]
This is an issue with the `renderQuillDelta` function, apparently, as the array of ops passed into it is correct for the above page but it still only renders the first line. Wondering if @raykyri is interested in taking a look. Doubt it's a big fix, hence the 1 tag, but if it reveals deeper issues, we can bump the points required.

**Comment by rbennettcw** [comment]
@jnaviask  I'm able to reproduce the issue locally on the `react` branch. The issue is that the elements are converted to `span`, and all elements render on a single line horizontally without a line break. I'm trying both CSS and JS tweaks. Will need a bit more time to find a solution that preserves the spans while showing on multiple lines.

Is there an acceptance criteria for this? If not, I'll aim to have the collapsed preview height 100-200px or so.

![Image](https://user-images.githubusercontent.com/126922418/223231355-78979de7-34a1-42c9-88d3-a033e9384c5a.png)

**Comment by rbennettcw** [comment]
PR: https://github.com/hicommonwealth/commonwealth/pull/3042
