### ISSUE TITLE
Remove ChainEventTypes

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#2949]
Stub ticket to be populated with scope of work migrated from Notion.

**Comment by timolegros** [comment]
# Tech Spec
## Overview
### The Problem
The chain-event-type removal migrations affect far too many records and tables in a single transaction resulting in deadlocks. This means chain-event-types removal cannot be deployed as is.
### Motivation
Chain-event-types removal is an important first step towards a generalized chain-events and notifications system so it is important to get this out.
### The Ideal Solution
One of:
1. Removes the long-running migrations and instead makes the database changes over time via a background script/job while ensuring backward compatibility with the legacy data that still exists. This solution avoids downtime entirely but requires much more work to update the API and write scripts.
2. Put the app in maintenance mode for 10-20 minutes and run the existing migrations. Immediate solution but requires app downtime.

The spec that follows is for the ideal solution 1 because solution 2 does not require any additional changes.

## Platform Requirements
### API Changes
1. Stop the generation of new legacy chain-event notifications
    - This will happen automatically since the chain-event consumer will filter out unnecessary notifications
4. Stop the creation of new legacy chain-event subscriptions
    - This will also happen automatically since the subscription API is updated to create the refactored subscriptions
5. Ignore legacy chain-event subscriptions
    - Update the query in the `/viewSubscriptions` route to ignore legacy subscriptions by filtering out subscriptions that have column `legacy` set to null (null is considered True so that we don't need to update every record in the migration i.e. legacy = false indicates a new/modern chain-event subscription).
    - Update the query in the `/viewNotifications` route to ignore legacy subscriptions (same as above).
6. Ignore legacy chain-event notifications
    - This will happen automatically since legacy subscriptions are ignored

### Database Changes
#### CW DB
Create a script which:
- Deletes notifications and notificationsRead older than 90 days once every day [timing/max-age TBD]
- Deletes legacy subscriptions (subscriptions whose `object_id` is a chain-event-type rather than simply a chain)

Delete queries should not delete more than X (e.g. 10k) records at a time to reduce DB/app congestion. If the queries are too large then this is the same thing as running an extremely long migration which reduces app response time.

#### Migrations
1. Remove the `20221226221226-delete-existing-ce-subs-notifs.js` migration which deletes notifications, notifications read, and subscriptions.
2. Redo the changes undone in `20230316212013-revert-cet-migrations.js` -> MUST BE DONE REGARDLESS OF CHOSEN SOLUTION
    - Drop CET table
    - Drop `chain_event_type_id` column from `Subscriptions` table
    - Drop `chain_entity_id` column from `Subscriptions` table

## Testing
1. CA proposals and notifications settings pages
2. New tests from #3168 will test event creation + propagation

## Notes
It should be noted that for future changes, we should always avoid app downtime. That is, changes should be specced in a way that avoids app downtime (i.e. CET removal should have implemented ideal solution 1 to begin with). It is only suggested here because it is the most efficient solution if short app downtime is considered acceptable.
