### ISSUE TITLE
 Fix `AvatarUpload` component

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3213]
## Description
Image uploads not working on React branch. The update-avatar-affordance (plus button on thumbnail) opens file dialog (doesn't seem to support url location for some reason?) but the file does not populate the thumbnail or save correctly. 

## Acceptance Criteria
- Avatar upload works correctly.

**Comment by masvelio** [comment]
@martins87 this is important, please take a look at this as next ticket

**Comment by martins87** [comment]
> @martins87 this is important, please take a look at this as next ticket

On it

**Comment by martins87** [comment]
@CowMuon @jnaviask @zakhap 

On 'View profile' page the 'Edit' option is missing on react branch. Do you guys want me to add it with this ticket?

![image](https://user-images.githubusercontent.com/30223098/226951208-6a1a5183-4009-472b-95d0-23bde0f0f02d.png)

**Comment by martins87** [comment]
> What is the cause of the edit field missing?

Edit profile page is also not rendering. I'm investigating why not

**Comment by martins87** [comment]
Image upload is ok but when app is trying to retrieve image recently uploaded to AWS, it's getting access denied (403).

I don't have access to our Amazon S3 settings. Can I have access or any of you check this, please?
Cc @CowMuon @jnaviask @zakhap

**Comment by martins87** [comment]
> What is the cause of the edit field missing?

Must be profile owner.

**Comment by CowMuon** [comment]
BLOCKED

**Comment by masvelio** [comment]
@CowMuon @martins87 Blocked by what?

**Comment by CowMuon** [comment]
@martins87 no worries, will get this sorted

**Comment by dillchen** [comment]
Is there an attached PR for this? / still blocked?

**Comment by martins87** [comment]
> Is there an attached PR for this? / still blocked?

No PR yet. I investigated why the images are not uploading and actually they are. What is not working is fetching the images just uploaded: the application is getting AWS 403 Forbidden.

I asked someone to look this up or give me access, because I don't have any to S3.

**Comment by jnaviask** [comment]
On deeper investigation, this has NOTHING to do with credentials. The way the flow SHOULD work (and does on Master):
1. Client calls /getUploadSignature
2. /getUploadSignature returns an upload URL
3. Client posts file to the upload URL
4. Upload URL returns the file's public URL
5. Component returns the file's public URL

How it currently works on react:
1. Client calls /getUploadSignature
2. /getUploadSignature returns an upload URL
3. Component returns the upload URL (which doesn't work, because the file hasn't been uploaded anywhere yet)

This PR should be fairly straightforward to do by referencing the logic against master.

**Comment by martins87** [comment]
> 

Thanks, Jake. I'll make the same master logic then.
