### ISSUE TITLE
Merge root_id work onto React

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3330]
## Description
Part of #3225. Includes the following commits:
1e1d3654e628e50f1f822c0a9296ffcadbb0092d
70eb60afa1a24690936748e21e74fa52beca3585
b107d5bc3fadd03e0f5c0b95d4e09f3da62d55c6
2c1c6127ac4d2835ee401e2391445e300b3b810a
0d2cf971a2e0f50245e15af49c49b871f7dc3704

**Comment by CowMuon** [comment]
For some additional context here, although both root_id and CET types have been merged into master, would prefer if we merge these commits separately, rather than just merging master in.

Please cherry pick your original (root_id) commits and test accordingly so we can catch react branch up to master on this.
