### ISSUE TITLE
Merge ChainEventTypes removal work onto React

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3331]
## Description
Part of #3225. Includes:
6632d14d6033d310b208e3a0014251e1afadbe40
d47e82d01ac73865ae36c575e2230dbb74896490

**Comment by CowMuon** [comment]
For some additional context here, although both root_id and CET types have been merged into master, would prefer if we merge these commits separately, rather than just merging master in. 

Please cherry pick your original commits and test accordingly so we can catch react branch up to master on this.
