### ISSUE TITLE
Snapshot Testnet

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3347]
## Problem
We currently have no way of leveraging testnets for new Snapshot related functionality we deploy.

## solution / Acceptance Criteria
- Technical specification of proposed testing setup. 

We can discuss during CE Office Hours this week, but wanted to get it on our radar before then.

**Comment by jnaviask** [comment]
Currently we support a SNAPSHOT_HUB_URL, which we can set to `https://testnet.snapshot.org` in order to access testnet data from snapshot. This will allow us to pull data from / make requests to the testnet. We need to ensure we have a known configuration setup that allows us to take advantage of this testnet.
