### ISSUE TITLE
Move commonwealth wiki documentation inside commonwealth repo

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3379]
## Description
Currently, we maintain our documentation in the github wiki. The benefit of the github wiki is that it's easy to spin up new wiki pages. However, it is currently not actively maintained, and it is difficult to see and validate edits to the wiki.

By using the commonwealth repo rather than the github wiki as a source of truth, we can ensure documentation is provided alongside development work + review it together, to aid in understanding the changes in a PR. We can also submit documentation changes as PRs, so they're tracked alongside product changes as contributions to the codebase.

Open question: how to organize the docs?

## Acceptance Criteria
- The contents of the Commonwealth Github Wiki are moved into the repo itself as markdown files.
- The github wiki is marked as reprecated.

**Comment by gdjohnson** [comment]
@jnaviask Is the open organization question mainly one of directory tree structure, then?

My guess is we should start by replicating the wiki's present organization and slowly anneal and re-anneal the organization schema of those files as time goes on. I don't think we have a clear enough picture of where we want to be and where we're headed, in terms of what the dev docs will & can be. This is my experience with earlier (Notion-based) iterations of our dev docs, at least. (Which BTW have not been ported over—do we want to include that in our migration?)

**Comment by CowMuon** [comment]
Yes, the current organizational structure of the engineering wiki doesn't really reflect an ideal or exceptionally well thought out anatomy, but more organic/ally, as a living (in the cybernetic sense) body of knowledge. 

Having said that, we do actually have a pretty clear picture of where we want to be. 

Re: Notion DRI docs, those are not needed here (or at all really.) Having said that, we do need to significantly revamp our DRI  organisation, which re-working should ideally come out of Chronicling work (tho not necessarily as immediately.)

**Comment by gdjohnson** [comment]
The old Notion docs tracked document completeness/reliability—I think having some similar tagging system would be useful. We're pretty limited with pure Markdown files, unless we want to start inserting JS snippets to parse/filter files based on their contents—but we could at least have some metadata stored at the top which is visible/searchable. 

What sort of metadata might be useful?
(1) DRI for the area, so team members working off incomplete or ambiguous docs know who to contact for clarification. (Note that in many cases, this may not be the individual responsible for the git blame, e.g. if I have worked with a DRI engineer to write & submit the documentation myself.)
(2) Latest verified date that the docs are relevant to. Again, this may not be the same as timestamps obtained through git blame—someone may update a small section of an entry without auditing and verifying the entire file for accuracy/relevance. 
(3) Completeness/quality indicator. In the old Notion docs, we used red/yellow/green, with red being docs being either seriously incomplete or out of date, yellow being partial and useful but in need of attention, and green being basically verified (e.g. by a DRI, the Archivist, or a team lead) as up-to-date and basically complete.

Why keep track of documentation status?
(1) To track which docs are in poor shape & need love. Doubles as a call to action: engineers using the docs can quickly and synoptically which doc entries need work, which should hopefully inspire some hole-filling in our knowledge base.
(2) To give engineers reading from the docs some context as to the quality of the docs they're dealing with. An engineer might spend an hour struggling to interpret documents that have fallen out of date since time of writing, or which were put together in a slap-dash fashion and are now being (mistakenly) treated as authoritative.
(3) To give team leaders a sense of doc entry quality before they pass off work to e.g. contractors. If some project-relevant area of the codebase is underdocumented, that can be quickly noticed and addressed, rather than the manager having to personally assess doc quality en toto.

**Comment by gdjohnson** [comment]
> Having said that, we do actually have a pretty clear picture of where we want to be.

Fair enough, but I don't! Happy to take a call (or come into the office, once offsite is over) to discuss the big-picture vision for how you'd like our docs organized and structured. I'm also very happy to work ~autonomously on this project, per conversations we've had about bottom-up org style, but my ideas and opinions are gonna inevitably differ, and it's hard to move forward without clarity/alignment.

**Comment by gdjohnson** [comment]
@CowMuon I think the situation is meaningfully different now then it was when I established the Notion wiki, and different too from when you inherited it.

The color-demarcation system (red/yellow/green) was built to serve two functions. First, it was envisioned as a way for engineers to specifically flag (along with comments) stale or incomplete docs, which they came across organically in the course of using the docs, using an easy-to-tag, readable-at-a-glance color system. Second, I imagined it as a way to take an "agile" approach to docs, where I could publish documentation for some part of a component/file, and flag it as incomplete so I could come back to it later. 

This system failed, IMO, because of our overwhelming push for new feature development at that time—not because of the intrinsic/formal features of the system itself. After setting up the initial docs system—on the premise that I would be able to devote 1 day of my work week to maintaining/expanding it—this maintenance/expansion time allocation never materialized, and there was no one around to freshen up stale docs, or add missing sections to incomplete entries. It also, I think, failed because a large amount of stubs were added (not by me) without any intent or possibility of their ever being built upon. My new presence as a dedicated docs-handler, in addition to our new PR system for approving all new docs additions (including any stubs), should markedly ameliorate both of these problems.

I'm not attached to the legacy system, and am happy to go other directions. But these are my two takeaways: (1) I don't think that formal features of earlier systems should take the blame for what was a failure of resource allocation. (2) An overwhelmingly repetitive takeaway of my research into docs systems—both best practices/failed approaches at major software companies, and also my team-specific one-on-ones this past week—has been that doc staleness is one of the biggest issues a successful documentation system needs to solve. 

We could try debundling the affordances of a status tracker (e.g. R/Y/G), and solve them independently. I could (1) set up a system for engineers to report doc problems + codebase areas in need of documentation; (2) have some entry-scoped, minimum viable staleness tracker like a "last certified fresh" timestamp; (3) keep track of desired changes/updates to various incomplete entries, so that per request, I can iteratively publish docs in an agile way, rather than waiting til they're perfect & fully complete. 

I'll continue my research into how other software teams handle this, and can continue pitching alternative systems. But these are the problems in need of solving, as I see them.
