### ISSUE TITLE
Add "Contract Type Tags" to Contracts page.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3446]
## Description

> When a user adds a contract, they should be prompted to add a contract type from a dropdown. **_The contract type they added should then be verified by Common to be accurate with the contract that they have added_**. The user should be able to see the type of contracts they have added from the Contract action templates page.  

**_The scope of this ticket is to add the dropdown + viewing UI. Type validation will take place as part of #3562._**

*List of available types in the drop down:*
- ERC20
- ERC721
- Governor Alpha/Bravo
- Moloch
- Aave
- Other

[Designs](https://www.figma.com/file/xXjVv3sPgaD9DjCmR0EGlt/Action-Templates?node-id=256-27982&t=188xk73H4Y2YSuLv-0):

![Image](https://user-images.githubusercontent.com/38763242/233469593-cb3146ce-a0e4-4f52-8d0f-e1bf02af6b7d.png)
![Image](https://user-images.githubusercontent.com/38763242/233469595-8ae4f7f2-86f5-467d-ad11-febce56b145e.png)
![Image](https://user-images.githubusercontent.com/38763242/233469594-a3184bb6-00e5-410a-90bb-0f74d8ca2e27.png)

Server should have this data available in the Contracts table.

## Acceptance Criteria 

- User adds a contract and selects the contract type from a dropdown on the Contracts page. The contract type that the user adds (ERC20, ERC721, Governor Alpha/Bravo/Open Zepellin, Moloch, Aave, Other) is verified on submission to be accurate (see: #3562).
- User browses Contract page to add Contract actions for their community. The UI communicates to the user the contract address and the type of contract that the user has added (ERC20, ERC721, Governor, Moloch, save)

**Comment by zakhap** [comment]
This requires some spec'ing in terms of _how this should get implemented_.

**Comment by sachben91** [comment]
@sachben91 to follow up with Jessica on designs changes

**Comment by sachben91** [comment]
updated this ticket based on what we discussed last week

**Comment by sachben91** [comment]
Added screenshots, the figma and notes underneath it are still good reference

**Comment by ianrowan** [comment]
There are two ways we can and should verify a tag matches a contract.
1. Check if ABI provided matches our ABI reference for the given contract type
2. Then, verify the ABI is in fact that contracts abi we can do this in two ways and should potentially do both but definitely (ii)
    1. Pull ABI from etherscan(if user bypassed the auto pull or it didnt work) 
    2. Make web3 calls to public call functions on contracts to verify ABI matches on-chain code
  
The requirements here would be for us to have ABI references stored for each tag type and a system for semi-fuzzy matching these abi. In short function signatures should match which is `function(datatype)` note the parameter name omitted. 
On this point there is an interesting implementation decision we'll need to make re: which/how many methods we match. In  this sense we should have minimal abis for our references as we don't need to check if all ERC20s have all possible ERC20 methods(ie some have a delegate method some dont).

Another requirement would be to have a evm provider available to simulate transactions to the contract on verification(this should probably happen backend).

I think altogether the validation is important but should be able to afford to be somewhat fuzzy and can potentially use a minimal set of validation requirements as the end result of an incorrect tag would be a template that simply doesnt work(what our simulations are trying to avoid) 

And a final note, we should make clear in someway to users that we do not validate security of the code within the contract. Just because we verify an ERC20 tag does not mean we looked at the source code itself at all and it could still include unexpected functionality in its implementation

**Comment by jnaviask** [comment]
Not planned.
