### ISSUE TITLE
Update styling across Contract-related components.

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3447]
(NB. see comment below about N/400, N/500 jargon.)

## Description

Styles ["on Figma"](https://www.figma.com/file/xXjVv3sPgaD9DjCmR0EGlt/Action-Templates?node-id=0-1&t=LzkdDnDPufzv2VLo-0) have changed across Bet 1. See "Changes" sticky notes on "↳ 12 APR - Eng Refinement" Figma page for descriptions of changes.
- [x] TODO: add list of required style changes to this ticket directly, to avoid working off Figma notes.

### Contract Action Templates page (currently called Contract page) 
- [x] Change all N/500 copy to N/600 copy. (this apparently has to do with font gradient?) 
- [x] Change name from Contracts to Contract Action Templates
- [ ] Change buttons for updated design comps. 

### Add Contracts Page
- [x] Parent breadcrumb -> N/500
- [x] breadcrumb divider -> N/500
- [x] Child Breadcrumb -> N/600
- [x] Textfield placeholder text -> N/600
- [x] Success message -> G/700
- [ ] Change buttons to Design system buttons
- [x] Change the name Templates to Actions 
- [x] Change the button Connect Template to Enable Action

### Changes to Enable Actions modal (previously called Connect Templates)
- [x] Change Header to Heading 4 bold
- [x] Change sub-headers to heading 5 medium
- [x] Change all N/500 copy to N/600
- [x] Change copy to what is in the modal on the design
- [ ] Change buttons to Design system buttons
- [x] Remove nickname and replace with ‘Action Details’ text field

### Contract Actions card 
- [x] Show only 1 name -> display name set in the ‘Enable action’ modal
- [x] Replace nickname with Action details

## Acceptance Criteria

- Implementation of Bet 1 matches comps.

**Comment by CowMuon** [comment]
We are still waiting for clarification from Design as to what N/400, N/500 etc mean.

**Comment by zakhap** [comment]
N/500, N/400 refer to "neutral-400" etc. In the designs and in the code, we use variables (design calls the "style tokens") to update color + box shadow + typography + more. 

For example, here is an example of our scss mixin file `color.scss` with all the variables being defined
![Screen Shot 2023-04-15 at 1 40 29 PM](https://user-images.githubusercontent.com/16248081/232183513-380488b9-ca58-443a-961e-e5f8d68feeae.png)

We have an entire folder of style mixins so that when we update the base styling for commonwealth, it trickles through the system. For example, if we want to change "primary red" to be a different shade, we would simply update the mixin file. All of our color references in the specific component and page styling files use the scss variable so that this is possible. 

There are countless examples of how we use our mixins across dozes of component/page stylesheets if you need any guidance on how to use scss variable mixins.

**Comment by alexyoung23j** [comment]
Not implementing design kit changes yet per discussions with Sachin and Jessica.
