### ISSUE TITLE
Rotate QuickNode Tokens 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#3477]
Seeing an anomaly related to [QuickNode](https://www.quicknode.com/) (endpoint service used for BSC & fantom communities, maybe Spirit Swap?) that we should take heed of and change our key credentials here. 

We have secrets rotation the the roadmap, for this instance, let's hard hat this. 

JTN- if we did smh leak our token, it stands to reason the new one will get leaked too, but in any case we need to do this immediately and keep a close eye on it.

**Comment by jnaviask** [comment]
Credentials have been rotated. However, since they are used directly on the client, they will immediately be leaked again. We need to consider whether a public websocket endpoint is available for bsc and fantom, or whether we can move away from using a paid node provider given the security risk involved, or we can use a similar scheme as with Alchemy, where we have separate frontend and backend keys.
