### ISSUE TITLE
Admin cannot change topics on threads they didn't create

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3522]
## Description
BD reported. See video:
https://www.loom.com/share/7e34168824f247078eea602ef4dfc7ee

Root cause has been identified, see comment below: https://github.com/hicommonwealth/commonwealth/issues/3522#issuecomment-1516642616

## Acceptance Criteria
- Admin (and moderator) should be able to change topic of any thread in the community they administrate (or moderate).

**Comment by masvelio** [comment]
I investigated it a bit but it seems that the problem is more complex. There are some discrepancies in the roles we have in the app and how we handle them on frontend and backend. For example in `members` page non of the user has  `admin` or `moderator` role assigned in cmn-protocol community (`User.tsx`). 

![Image](https://user-images.githubusercontent.com/14819225/233404360-339f08a0-bd49-418b-94af-e8d6029c9d72.png)

However, [Jpegmullet](https://commonwealth.im/profile/id/16462) in the loom video is able to open 3 dots menu that is only available for admin or mod (thread_preview_menu.tsx).


![Image](https://user-images.githubusercontent.com/14819225/233404942-4e07fc7f-bc61-4404-9c5e-815b46eb76be.png)

In backend there is a check that throws error in the console (`You do not have permission to edit post topic`) and this comes from `updateTopic.ts`. In this piece of logic, user has no roles that are comming from `findAllRoles`.

I am not sure how we should tackle this. Is there any documentation how the role and permission system work? I would leave this ticket to someone else as this would probably take me a lot of time to investigate further.

**Comment by jnaviask** [comment]
Ah -- the reason is because Jpegmullet is a _site admin_ = god mode, but not a community admin. I think that is the cause of this discrepancy (as the change topics route does not permit site admins, although perhaps it should). Will close as not planned / fix not needed.

**Comment by masvelio** [comment]
> Ah -- the reason is because Jpegmullet is a _site admin_ = god mode, but not a community admin. I think that is the cause of this discrepancy (as the change topics route does not permit site admins, although perhaps it should). Will close as not planned / fix not needed.

@jnaviask Is there a way to become a site admin via the app? Or only with db modification?

**Comment by jnaviask** [comment]
Reopening: still present. Members page doesn't show admin/moderator role. May be route-related -- likely not a completely front-end issue. To investigate further.

**Comment by jnaviask** [comment]
Issue is with this line in `updateTopic`:
```
  const userAddresses = await req.user.getAddresses();
  const userAddress = userAddresses.find(
    (a) => !!a.verified && a.address === req.body.address
  );
```

The above code is how the `updateTopic` route discovers `userAddress`, which is used for role checks (i.e. confirming the requester is an admin or moderator of the community). Since it only matches based on the address string, and only finds one address, it risks locating an `Address` row that is on another community = not an admin of the community relating to the action.

We instead need to EITHER surface the exact address on the community (by filtering by chain as well as address), OR include all found addresses (generating the list via `filter` rather than `find`) in the `findAllRoles` check via the `Op.in` sequelize query operator (like in the `updateLinkedThreads` route).

**Comment by masvelio** [comment]
Fair point @jnaviask . Your approach seems to work and I put up a [PR that proves that](https://github.com/hicommonwealth/commonwealth/pull/3545). 

However, I still think there is something off with the roles. For example - this fix above won't work for Gods and I guess we can have multiple situations  in the app where God mode confuses users as we are not consistent in checking the roles. 
Eg here - I am a God Admin 
1. I can see `Admin Capabilities`
2. I can't see 3 dots on thread 
![image](https://user-images.githubusercontent.com/14819225/233658089-75572d91-6f10-439d-9e04-55ec55aabdd1.png)

3. If I go to the thread, now I can see the 3 dots menu even though this is not my thread
4. I can see the `change topic` item, but I can't use it
5. I can see the `delete` item and it works fine 🤯 
 
![image](https://user-images.githubusercontent.com/14819225/233658387-fc59c36a-1189-49b4-a05a-1cbabf3b9b00.png)

Having God mode, I can upgrade my role in admin page and then all of these works fine.

**Comment by jnaviask** [comment]
We should move in the direction of removing God mode, or not guaranteeing support for it / ensuring we are clear about its function, as it is only for internal use, and can only be enabled directly in the database.

I will review your PR, though, and then close this ticket once merged, as this is a feature affecting community admins.
