### ISSUE TITLE
Profile threads tab gives "Failed to execute 'removeChild' on 'Node'" when coming from Osmosis community

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3619]
## Description
BD reported. See video:
https://www.loom.com/share/10296a44e70b41398711dc00125e85f6

## Acceptance Criteria
- The threads tab should not crash when accessed after visiting a community.

**Comment by Miaplacidus** [comment]
@jnaviask I'm unable to reproduce the error locally, so any fix I make cannot be confirmed either way. However, I have a possible solution that I've pushed that up to branch `3619-bug-child_node_removal_failure`. This solution assumes that the underlying error is due to React not being able to remove "child" elements of a fragment because fragments don't add anything to the page. It may be wrong, but anyone able to reproduce the error locally would be able to confirm.

**Comment by jnaviask** [comment]
Thank you for the update @Miaplacidus!

**Comment by mhagel** [comment]
I couldn't reproduce this today, just noting.

**Comment by CowMuon** [comment]
Closing as can't reproduce.
