### ISSUE TITLE
Quill: cannot mention all users by profile name

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3684]
## Description
BD reported: some users cannot be mentioned by username, only by address. Video: https://www.loom.com/share/13268346a4174d7b9d772b206f91cb45

Likely related to state being unavailable on the client. We may need a new route that lets us search profiles directly, or may need to modify "bulkAddresses" to search properly.

## Acceptance Criteria
- Mentioning should work for all users with addresses in a community.

**Comment by rbennettcw** [comment]
Estimating this at a 5:
- I've updated the `bulkAddresses` route, which fixed the quill mentions to pull from profiles instead of addresses.
- It appears that a Profile can have multiple Addresses, when joining by user ID. The different data model ends up breaking members search, which relied on the Address model. I'm working on an approach to reconcile the difference.
