### ISSUE TITLE
Markdown rendering incorrect for some tags

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#3694]
## Description
BD reported some weirdness:

![image](https://user-images.githubusercontent.com/1860629/236050038-fdea1571-daf7-49ab-b9cc-c8b542b9966c.png)

![image](https://user-images.githubusercontent.com/1860629/236050063-71ea8cbc-8ff8-499a-b3b4-f178543a144b.png)

## Acceptance Criteria
- Markdown rendering should work as expected.

**Comment by rbennettcw** [comment]
@jnaviask  Currently, I've implemented/tested against the Github standard: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

We're using the same library/config as pre-react.

In your example screenshot, it looks like the italic, slash and bold syntax was double-applied. Is this something we want to officially support? The markdown library does not seem to handle this.

If we want to support it nonetheless, is the expected behavior that a double/triple-applied format should behave as if it was single applied?

**Comment by jnaviask** [comment]
cc @zakhap

**Comment by jnaviask** [comment]
Closing as reporter issue.
