### ISSUE TITLE
Moderation: Inline Archiving UI

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#3924]
## Discussion
**Goal: Allow admins/mods to archive threads so that they can clean up their forum without marking old threads as spam. Community members should still have access to finding and interacting with these threads.**
TLDR: A similar UX pattern to P1a, simple inline archive + discoverability via listing page.

### User Stories:
- As a moderator, I want to be able to archive threads that are not relevant to my community.
- As a community member, I want to be able to see all the archived threads
  - filtered by topic
- As a community member, I want to be able to view specific archived threads.
- As a community member, I should not be able to interact with an archived thread.
- As a community member, I want to know if a thread that I am viewing has been archived.
- As a moderator, I want to unarchive a thread.
- As a moderator, I want archived threads to be hidden by default, but still accessible from the sidebar.

### Design Requirements

**Thread post listing:**
- Default state 
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/2e3f8136-b780-4e0b-a2ad-92c21a492671)

- Hover state (`Neutrals/100`)
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/28733dd4-f75b-4a3e-b153-92e4918e8c6f)
> - On hover, background color becomes `Neutrals/100`

- Action icon hover state
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/2db422cd-1345-4714-b131-028e924e7232)
> - Icon is `Bold/DotsThree` (16 x 16px) with 4px padding all around, so the entire container is 24 x 24px with a radius of 6px—on hover, the color of the icon becomes `Neutrals/600` and a background of `Neutrals/200`

- Dropdown
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/23f43d7c-0ba6-45f4-9dd6-37bf406493eb)

- Dropdown with item (on Hover)
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/11bf635e-5e1a-4f68-ad5d-f07e9c87497c)

- Dropdown specs
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/1680b288-df68-4944-b632-b6166086d6b1)
> - Dropdown is aligned to the container of the action icon and there's a 4px spacing inbetween

**Thread post page:**
- Thread post (default, pre-archiving)
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/16286cbe-14ae-4b5b-adcf-117b36c4c952)

- Confirmation modal with curtain behind
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/efa182b0-7309-48b0-9150-21936eb9835a)
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/984346eb-cc03-44c8-b837-19bae5a62ecc)
> - [Curtain](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=472%3A4607&t=ugnPgbpoK44T4NwU-1) is full screen, `Base/Black` at 20% opacity

- Thread post (post-archiving)
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/1a086307-0af9-4f0d-b40e-f448bb5f849e)
> - Visual indicator = `ArchiveTray/Fill` that is 16 x 16px and `Neutrals/500` with Tooltip
> - Disabled actions for `Upvoting` and `Commenting`
> - Banner informing the user that the thread post has been archived
> - No Quill editor because no comments can be added

- Entry points to find archived posts
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/32555291-556f-4246-b9a2-972979cd49f9)
> - Side nav (on hover) = `Archived` with far right icon `ArchiveTray`
> - Topics filter with divider from created topics

- Archived posts feed
![Image](https://github.com/hicommonwealth/commonwealth/assets/18157060/97dd8174-5bf3-4f16-9c30-c7e7d8f9fa15)

#### Designs Resources
- :tv: [Loom walkthrough](https://www.loom.com/share/ed3cbc284c9b4f7f9e18b026415399d4)
- :arrow_forward: [Prototype](https://www.figma.com/proto/30dpVGV7zndfhS5V0jzf4W/Moderation?page-id=16%3A30536&type=design&node-id=16-33778&viewport=1429%2C372%2C0.24&scaling=min-zoom&starting-point-node-id=16%3A33778)
- :art: [Figma file](https://www.figma.com/file/30dpVGV7zndfhS5V0jzf4W/Moderation?type=design&node-id=16%3A33778&t=0zZfWDNpLZesquzR-1)

### Acceptance Criteria
- Community admin/moderator sees the option to "Archive" when they click on the three-dot drop down on a thread 
- Clicking on "Archive" brings up the confirmation modal 
- Once Archived the thread should display the message that notifies the user (admin and regular user) that the thread has been archived and no more comments can be added 
- Community admin can view the archived threads when they click on Archived under discussions

**Comment by zakhap** [comment]
@Miaplacidus I don't believe so! It should be ready to go

**Comment by jnaviask** [comment]
@Miaplacidus Note that the backend changes are ticketed separately: #4190. You can stub out the specific API calls while building the UI. Format should be similar to the markThreadAsSpam and similar routes. Feel free to ping @rbennettcw if you need any details in advance of the backend PR.

**Comment by rbennettcw** [comment]
Yes, I think the archive functionality would be similar to the existing spam functionality.

The backend implementation would probably look like this:

Thread model
- Will add `archived_at` property (timestamp, nullable)
- On the frontend, a non-null value means it's archived (and you can optionally show the date it was archived)– and a null value means it's _not_ archived

`GET /threads?topic_id=1&archived=true`
- Get archived threads by topic ID

`PATCH /threads/:id/archive` (no body)
- Archives a thread, returns updated thread
    - will set `archived_at` to current timestamp

`PATCH /threads/:id/unarchive` (no body)
- Unarchives a thread, returns updated thread
    - will set `archived_at` set to null

---

Endpoints related to thread reactions/comments will throw an error if the thread is read-only/archived.

**Comment by CowMuon** [comment]
> Endpoints related to thread reactions/comments will throw an error if the thread is read-only/archived.

Seems like a relatively important consideration for Optimistic UI, in that there are a couple different ways the implementation could go. 

First question is why app would make a request against an thread that has been archived. In theory that shouldn't happen, since archived threads cannot be posted to. Given that a client is subscribed to a thread, it should receive the notification when that thread is updated (presumed to just set that boolean on the thread object?) and so the app knows which threads are archived, so the expectation is that making a request to post to an archived thread is a bug at some level. 

So this is different than the normal case where we optimistically add a comment to a thread, locally in app and then after the app issues a command to the back end (platform) to add thatcomment, and getting our 200 success, the platform the commits the event as a notification, which has the effect both of updating the cached value for that object (which thread now points to a newly added comment) as well as commiting locally (when the app receives this notification, and so commits the comment it optimistically made.

**Comment by rbennettcw** [comment]
It sounds we want to implement Optimistic UI via a decoupled pubsub approach to UI updates.

If that's the case, then yes we'd send a 200 initially and immediately update the UI optimistically.

However, we'd still need to handle possible failure cases, like thread not existing, thread being archived, token balance insufficient, permissions insufficient, etc. These are conditions that are checked *after* the initial 200 was sent. For those failure cases, the backend would need to send a 2nd notification with failure details, triggering the UI to "rollback" to the previous state.

---

Note: The current code implementation for creating comments uses the simple request-based approach.

If we want to implement Optimistic UI here, we should probably hold off until the new notifications system is integrated, since that will (likely?) play a role in the pubsub mechanism.

**Comment by CowMuon** [comment]
@Miaplacidus Please remember to leave the old point label when you add the new one.

**Comment by Miaplacidus** [comment]
@zakhap @meeshlin @jnaviask 
I have a question/suggestion in regards to the Topics dropdown. We're adding 'Archive' to the 'Topics' dropdown, which isn't entirely accurate, since 'Archive' isn't a topic. Is there a different way we can handle filtering by archive status in the UI?

**Comment by Miaplacidus** [comment]
@zakhap @meeshlin @jnaviask @CowMuon 
We'll be updating the design a bit to make the acceptance criteria possible. Instead of having 'Archive' available as an option on the topics dropdown, we'll make it a checkbox under the filter dropdowns. The 'Archive' link in the left will default to the 'All' topic when clicked on. @rbennettcw if we hit `GET /threads?topic_id=1&archived=true` without passing a topic id, will we get a list of all archived posts of any topic?

**Comment by rbennettcw** [comment]
@Miaplacidus I think the existing route would be `/threads?bulk=true&topic_id=1`, since we are still essentially using the old routes but with RESTful access.

It doesn't currently support filtering by archived– it'll just show all (paginated) threads for that topic.

Does this ticket require a route that only returns archived items? If so, I can create a new ticket for it and add it.

**Comment by Miaplacidus** [comment]
@rbennettcw We need to be able to click on the 'Archive' link in the menu on the left and see a page with only archived posts (any topic) by default. Of course, the user can then filter by topic, as well. if `/threads` doesn't allow for that, we'll need a new route.

**Comment by rbennettcw** [comment]
@Miaplacidus Gotcha. We can extend the existing bulk threads route. It's the same route currently used on the page that filters threads by topic. It's a relatively complex query so repurposing it is better than creating a new route.

I'm thinking `/threads?bulk=true&topic_id=all_topics&archive=true` where topic_id can be either the ID or `all_topics`.

**Comment by rbennettcw** [comment]
The API change has been made to return only archived threads–– ticket/PR above ^^^

**Comment by Miaplacidus** [comment]
Hey @rbennettcw I can't see where that is. Would you mind sharing a link to that PR?

**Comment by rbennettcw** [comment]
@Miaplacidus https://github.com/hicommonwealth/commonwealth/pull/4713

**Comment by Miaplacidus** [comment]
Current status of card (2023-10-12): awaiting merge into master and deployment

**Comment by Miaplacidus** [comment]
@jnaviask @CowMuon 
Current status (2023-10-17): 
* Responding to last few PR reviews
* Merge conflicts resolved
* Bug appeared after merge: threads no longer immediately disappear following archiving. Fix in progress.
