### ISSUE TITLE
Improve Forum Endpoints 🪣

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#3989]
# Child tickets:
- [x] #4087
- [x] #4282
- [x] #4086
- [x] #4085

## Summary

There are multiple endpoints for fetching threads, which has resutled in redundant code that's difficult to maintain. We should use RESTful paths so that the API is idiomatic and intuitive.

Audit of forum endpoints for reference: https://github.com/hicommonwealth/commonwealth/wiki/Forum-Endpoints-Audit

---

## Organizing code in server-side controllers

Endpoints will be refactored to improve the readability of reusability of code.

It is recommended to create a server-side controller layer for forum endpoints, and implement business logic in the controller(s) rather than directly in the endpoint handler. 
- All logic that reads/writes data belonging to Threads should go into the `ServerThreadsController` class
- All logic that reads/writes data belonging to Comments should go into the `ServerCommentsController` class
- All logic that reads/writes data belonging to Reactions should go into the `ServerReactionsController` class

For clarity: the code location is about the root object type. If we need to fetch the reactions of a thread, then that would go into the `ServerThreadsController` since the `Thread` is the root object type.

Note: The "Server" prefix for the classes helps to differentiate the server-side controllers from the existing client-side controllers that are already named `ThreadsController`, `TopicsController`, etc.

Usage of a controller would look like this:
```ts
const threads = await ServerThreadsController.getThreads(options)
```
```ts
const reactions = await ServerThreadsController.getThreadReactions(threadId)
```
```ts
const updatedComment = await ServerCommentsController.updateComment(commentId, comment)
```

Guidelines:
- Ensure that all controller methods are strongly typed for inputs and return values.
- Ensure that all controller methods are documented to describe expected behavior.

---

### **Threads:**

`GET /threads` - Returns bulk threads
- Implements functionality from `/getThreads`, `/bulkThreads`, `/activeThreads` and `/searchDiscussions`

`GET /threads/:id` - Returns a single thread by ID
- Implements functionality from `/getThreads`

`POST /threads` - Creates a new thread, returns thread
- Implements functionality from `/createThread`

`PATCH /threads/:id` - Updates a thread by ID, returns updated thread
- Implements functionality from `/editThread`

`DELETE /threads/:id` - Deletes a thread by ID, returns nothing
- Implements functionality from `/deleteThread`

### **Comments:**

`GET /comments` - Returns bulk comments
- Implements functionality from `searchComments` (not `bulkComments`)

`POST /threads/:id/comments` – Creates a new comment on a thread, returns comment
- Implements functionality from `/createComment`

`POST /comments/:id/comments` – Creates a new comment (reply) on a parent comment, returns comment
- Implements functionality from `/createComment`

`PATCH /comments/:id` – Updates a comment, returns comment
- Implements functionality from `/editComment`

`DELETE /comments/:id` – Deletes a comment, returns nothing
- Implements functionality from `/deleteComment`

### **Reactions:**

`GET /threads/:id/reactions` – Returns reactions for a thread
- Implements functionality from `/viewReactions`

`GET /comments/:id/reactions` – Returns reactions for a comment
- Implements functionality from `/viewReactions`

`POST /threads/:id/reactions` – Creates a reaction on a thread, returns reaction
- Implements functionality from `/createReaction`

`POST /comments/:id/reactions` – Creates a reaction on a comment, returns reaction
- Implements functionality from `/createReaction`

`DELETE /reactions/:id` – Deletes a reaction, returns nothing
- Implements functionality from `/deleteReaction`

## 2. Update frontend to use new endpoints
- Ensure that all affected components render and function correctly with no regressions.

## 3. Remove old endpoints
- The old endpoints should no longer be used on the frontend, and thus can be removed.
- The `bulkComments` endpoint was not used on the frontend and can also be removed.

**Comment by rbennettcw** [comment]
@jnaviask Feedback on this ticket?

Some endpoints are consolidated, while others are separated– all according to RESTful endpoint patterns.

**Comment by jnaviask** [comment]
This is really great. Some comments:
- We should use PATCH instead of PUT for partial updates. PUT does a wholesale replace.
- I don't believe we support reactions on proposals, so we can deprecate the GET/POST for `/proposals/:id/reactions`

Otherwise, I'm super happy with this layout.

Feel free also to make follow-up tickets with your general suggestions from the forum route audit.

**Comment by kurtisassad** [comment]
I don't like the Controller concept for the backend. I feel like this runs counterintuitive to how SQL works because the point of a relational database is to be able to make joins, I don't see how this controller approach could support this since it inherently separates the models. This makes it prone to more easily creating n + 1 queries.

Imagine a use case where we want to support an endpoint like "get all comments per user". In this case, the ideal solution is to have a query which joins all users to comments like:
```
SELECT c.id, c.chain, ...
FROM "Comments" c
JOIN "Addresses" a ON c.id = a.address_id
JOIN "Users" u ON a.user_id = u.id
WHERE u.id = <user_id>;
```

But the equivalent with the controller approach would be:
```
const addresses = await ServerAddressController.getAddressesByUser(options)
const comments = await ServerCommentsController.getCommentsByAddress(addresses)
```

If we are to argue that we would have a separate method for each route like:
```
const comments = await ServerCommentsController.getCommentsByUsers(user)
```

Then I don't understand the code separation aspect, because right now each route corresponds to a file, which I think is better code segmentation technique than by methods in a controller.

**Comment by rbennettcw** [comment]
@kurtisassad I understand your concern.

For your example of "get all comments per user", the root object is `User`, so under my proposal, that logic would look like this:

```ts
const comments = await ServerUserController.getAllCommentsByUser(userId)
```

`User` is the root object (even though comments are being returned), so the logic would go into the User controller.

My proposal is not to limit each controller to a single model, but to simply create another layer of abstraction so that we can *possibly* reuse some common logic here and there.

The readability and reusability of our code would increase since server handlers would be less than 30 lines of code in most cases. Not all logic would be reusable, but some would be.

**Comment by jnaviask** [comment]
@kurtisassad @rbennettcw Really love the conversation here.

If I had to steelman @kurtisassad's objection, it would be that we have a domain modeling concern, where our various entities (threads, comments, users, etc) intermingle with each other, meaning that a naive approach to data querying abstraction (into controllers) will produce inefficient code.

The key question is: which queries do we actually perform? And can we scope out a minimal set of functions within this controller layer that handle route requirements _efficiently_? This will be part of the work in designing the controller layer.

As for separation into an abstraction layer itself, I'm all for it, because once we have an abstraction layer around the SQL queries, we can mock out the data layer, and start writing proper unit tests for routes rather than integration tests.

@rbennettcw Feel free to proceed as specified.

**Comment by CowMuon** [comment]
🙌
