### ISSUE TITLE
Address switching in Login Selector does not work

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4046]
## Description
Reported by @raykyri. Always resets to first address on refresh + is not respected when posting threads/comments: 
![image](https://github.com/hicommonwealth/commonwealth/assets/1860629/1fbf63ea-a454-40f8-9fbd-be3610df5e50)

Likely state not being propagated across the app.

## Acceptance Criteria
- Address switching by user should properly set thread creator + persist across refresh (and logins, ideally).

**Comment by ianrowan** [comment]
Have not been able to reproduce this making posts across evm communities, refreshing, and logging out/in.

Scenarios attempted:
1. Create thread with address 1
2. Create thread with address 2 
3. Comment on thread 1 with address 2
4. comment on thread 2 with address 1
5. Log out with address 2 selected, log in 
6. Switch addresses while writing thread 
7. refreshing on both addresses 

All expected results 

CC: @jnaviask

**Comment by ianrowan** [comment]
When moving between communities where 2 addresses have been linked, state of selected address in the other community(this could make it look like state is not being maintained maybe?) is maintained which seems like good/expected behavior

**Comment by jnaviask** [comment]
Huh. Will bring up with @raykyri + try to find a specific set of steps to reproduce. Thanks for the investigation.

**Comment by raykyri** [comment]
Checking the slack, I think this is pretty specifically that if you switch the address in the address switcher, the updated address isn't used for the thread created from the New Thread page, but the old address is used instead - mousing over your profile icon confirms this.

**Comment by ianrowan** [comment]
Here is an example of the steps I'm trying 
https://www.loom.com/share/9ef1ddaacb184d3ba74dfc48871cb473
CC @raykyri @jnaviask

**Comment by raykyri** [comment]
The linked PR doesn't fix this and just removes the intermediate author variable which was already equal to `app.user.activeAccount`.

<img width="1257" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/1273926/01c64177-321d-4230-beb3-5dcbe36b21ed">

This remains an issue when creating threads and creating comments - threads or comments are created with the wrong address after switching between addresses.

**Comment by ianrowan** [comment]
@raykyri The issue was that the author variable state was not updating until a form change so if the activeAddress changed but no more text was added author remained the same. The fix was supposed to inject the activeAddress reflected in the last switcher change. 

Could you share a loom from master of this occurring by chance?

**Comment by raykyri** [comment]
I had thought this was still occurring but I must have been merged up to a stale version of master, or there's another cause of this issue that has to do with SessionRevalidationModal interrupting the create thread flow (which is on me to fix).

And it looks this should have fixed the issue because the handler no longer has a stale value for author in its closure. So I guess we can close this and reopen if it shows up again.
