### ISSUE TITLE
Thread Listing Row – Design Update

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4121]
## Description

- Default, showing upvote button (flex, can adjust the width to fit individual contexts in our live site)
  - Attributes:
    - Pinned
    - Status tags (New, Trending)
    - Element tags (Poll, Snapshot)
    - Stage tags
    - Prop tags
    - Spam (disabled)
- Responsive, showing in-line upvote action (breakpoint is at 904px)

Figma: https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707-11676&t=zG3i0wmhAZlcDJpy-0

## Acceptance Criteria

- Above components are added to the Component Kit and are auditable via Storybook stories.
- All updates are used in context, thread preview row components are updated to reflect these styles.

**Comment by meeshlin** [comment]
Left this piece of feedback on [#4191](https://github.com/hicommonwealth/commonwealth/pull/4191)
Looks great and the right actions are being surfaced correctly depending on community (ex. if I'm not in a community and can't post on it).

One note, the spacing between each component should be 0 because the padding around the icon+copy makes up for that. Saves real estate, looks better, and aligns with the interaction as you can only have one action hovered at one time. Please make that change, otherwise, it looks good to me.
