### ISSUE TITLE
Design System: Quill Editor

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4122]
## Description

- Thread, Snapshot, and Proposal editor and all states (default, disabled, focus)
  - Markdown on and off
- Comment editor and all states (default, disabled, focus)
  - Markdown on and off
- Reply editor and all states (default, disabled, focus)
  - Markdown on and off

<img width="868" alt="Screen Shot 2023-06-01 at 1 21 29 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/ab0cb60d-c778-44ac-95ae-1f0b05e6c29c">

Figma: https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=342-4799&t=CMXwC3DWDgOEslre-0

## Acceptance Criteria

- Updates applied to component across the site
- Updates auditable via storybook stories

**Comment by masvelio** [comment]
1. There is a missing `image icon` in figma designs vs the current app. Should we implement it or not?



![Image](https://github.com/hicommonwealth/commonwealth/assets/14819225/95b8d44b-d1c4-42ca-a0c8-a55605a03c0e)


![Image](https://github.com/hicommonwealth/commonwealth/assets/14819225/ababf0e5-3a68-418f-95ad-227e662375e2)

2. Should height of the TextArea container be fixed size and then the content should be scrollable? Or the container should expand to some max-height as this is right now in the app? 

https://github.com/hicommonwealth/commonwealth/assets/14819225/8b0ae60d-7085-4b8e-89be-a7f05ae54c20

3. What type of component it is in terms of the terminology of atomic design. Clearly it is not atom, but should we call it molecule, organism, pattern or? It is important because it has to be placed in proper directory in storybook. 

4. Outline on foucs around the whole editor seems unusual for me. Eg text editor on github as I am writing right now focuses only the editable text-area. If we want to follow the figma design it is probably doable but quite a lot of hackiness because toolbar and text-area are two different containers and generally the wrapper is the simple `div` so we need to manually handle state for focus and blur.


![Image](https://github.com/hicommonwealth/commonwealth/assets/14819225/8ec026c3-0f74-462e-9de1-a08d16507adb)

**Comment by zakhap** [comment]
1. We should have the icon, but tbd from @meeshlin for where it should go
2. Keep the current behavior
3. The Quill Editor is an Organism
4. @meeshlin to confirm!

**Comment by meeshlin** [comment]
@masvelio 

1. Icon is attached
2. Agree with @zakhap, keep the current behavior
3. It's a **Component**, we aren't using atomic language as it's not the norm in design 3. We don't need to be spending time questioning if something is an "organism" or not if we can just put them into three buckets (for now): `Foundations`, `Components`, and `Patterns`. We'll get to `Layouts` at some point if necessary, depends on how y'all feel about this process and the value it's meant to provide. 
> Examples: [Other Design Systems](https://www.notion.so/buildcommon/References-Other-Design-Systems-4061fb2c32124507ad696386d27130c8?pvs=4)
4. We updated our `Focus` states, so reference the [Figma](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=707%3A15777&mode=dev) (you can now toggle to leverage their new feature, [Dev Mode](https://www.youtube.com/watch?v=__ABPkb0aF8)!)

`border-radius: 6px;
border: 1px solid var(--primary-blue-500, #338FFF);
background: var(--base-white, #FFF);
box-shadow: 0px 0px 0px 3px #CCE3FF, 0px 2px 2px -1px rgba(0, 0, 0, 0.12);`

**Comment by meeshlin** [comment]
Adding on to 4, the value is that it differentiates hover states for form fields and text inputs from focus states. @masvelio

**Comment by masvelio** [comment]
progress update: draft PR -
- from code perspective it is done
- quill has been updated in every place in the app
- still have to put it into the storybook, but run into some problems with webpack so need to spend more time on it

**Comment by meeshlin** [comment]
Can we hide the `Placeholder` copy for now. I designed the editor and all text inputs with the option of having placeholder copy—however, as we go through this rip & replace process, it doesn't make sense to show it in the editor.

cc: @Miaplacidus @masvelio @martins87 @zakhap

**Comment by masvelio** [comment]
removed in this commit https://github.com/hicommonwealth/commonwealth/pull/4359/commits/24ee59fe1e93c2793b602cab1966712dbb2be7d1
