### ISSUE TITLE
Polkadot js login not working

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4154]
## Description

Polkadot js login flow does not succeed. See https://commonxyz.slack.com/files/U04N23Y7BBR/F05BK0CE4JY/screen-recording1.webm

To reproduce: attempt to log in on /edgeware with polkadot.js installed.

## Acceptance Criteria

Polkadot js login should work normally.

**Comment by jnaviask** [comment]
Already at least one bug identified in `getAddressFromWallet` (no handling for substrate -- should be same as cosmos). Fixing this bug created an explosion of other issues.

**Comment by alexyoung23j** [comment]
The original task here was to research how much work needs to go into fixing this and what the problem is:

Basically, all wallets except polkadot will allow user to select their target address within the wallet. Polkadot (maybe all substrate works this way) just shows you all your addresses, meaning the CW UI needs to be responsible for allowing the user to select the address they want. This was originally accomplished with a component called `AccountSelector`. The problem is that after the refactor of the login flow to work better with react, the logic for selecting the address has been abstracted away from the actual login component and into a hook. So with the current implementation, there is no straightforward way to pause the data flow to wait for the user to select an address from the `AccountSelector` and then continue with the rest of the login flow. 

Fix here is definitely possible but likely would involve some very hacky solution because of how different the polkadot case is from everything else. Another possible solution would be to just default to using the first address in a polkadot wallet, but this is potentially very confusing and obviously not ideal UX. @mzparacha Would be curious to get your thoughts here, as you did the great work refactoring login a few months back. My guess is this is a 3-5 pointer though, as no obvious fix comes to my mind at least. Hoping you have something clever!

@MuonShot @zakhap tagging you for visibility.

**Comment by CowMuon** [comment]
I am confused by what I am hearing, namely that polkadot has been heard to suggest using other wallets (ie wallets other than polikadot.) While that would seem to make our problem easier (only support wallets that meet standards, so, not polkadot) it does raise the question why they would be saying not to use their own wallet.

**Comment by alexyoung23j** [comment]
Okay, in order that substrate users can at least log in (albeit without any ability to choose their default wallet), I will put up a PR that removes the triggers to mount `AccountSelector` and defaults to choosing the first address in their wallet. We can circle back to this if a business case for extensive polkadot support is made (atm basically only edgeware is affected).

**Comment by mzparacha** [comment]
> @mzparacha Would be curious to get your thoughts here, as you did the great work refactoring login a few months back. My guess is this is a 3-5 pointer though, as no obvious fix comes to my mind at least. Hoping you have something clever!

@alexyoung23j I believe we could just add a conditional state for polkadot and then either make the api calls after selecting address or use the new state value to condition the api calls as well, so something like
```
const [walletType, setWalletType] = useState() // here we store polkadot
``` 

and when its polkadot we do either
A. show user the account selection modal and then make api calls
B. make the initial api call (i think its `/verify`) and then show account selection modal and afterwards any other api calls.

what I mean is that in theory we can hold off any api calls that are to be hold before user selects an address from the account selection modal.

Please LMK if it would work or any issues, would be happy to colab on this and maybe come up with something even better.
