### ISSUE TITLE
Moderation Notifications

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4162]
## Description

- As a user, I should receive a notification if: 
  - **my** **thread** was marked as spam
  - **my** **comment** was marked as spam
  - **my** **thread** was archived
- As a user receiving a Moderation notification, I should know the admin (Profile) that executed the moderation action.

e.g. "**Jaco Naviocean** marked **My pork themed Thread** as Spam" => clicking notification takes you to thread
e.g. "**Woods Saturn** marked your comment as Spam" => clicking notification takes you to comment

## Acceptance Criteria

- Users of Common will receive notifications when moderation actions happen to content they've created.
- The above user stories are implemented.

**Comment by timolegros** [comment]
@jnaviask @zakhap There is a lot going on to clean up the existing/legacy notifications system and build the new system. Would it be possible to hold off on this milestone + issue until we have:
1. cleaned up the legacy notifications system
AND/OR
2. Created the new notifications system.

I highly recommend we hold off on this issue especially since the `emitNotifications` function is already causing extremely long-running queries. This addition would only add to that load/strain. Once the legacy system clean-up milestone is completed this will no longer be an issue.

**Comment by timolegros** [comment]
> @timolegros What do you think the best path forward is for extending the notifications system to emit these notification types?

Given that #4586 was just merged (pending QA), we are one step closer to making it easy for this to happen. That said, the remaining issues in the [Legacy Notifications Clean-up milestone][1] should probably be taken care of before we implement these new notification types i.e. let's fix the notification types we have before we add new notifications. The vast majority of the remaining bugs are client-side and could probably be knocked out within a week by one of our front-end wizards @jnaviask. 

[1]: https://github.com/hicommonwealth/commonwealth/milestone/30
