### ISSUE TITLE
Kyve proposal throwing error "Cannot read properties of undefined (reading 'toLowerCase')"

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4181]
## Description
See: https://commonwealth.im/kyve/proposal/6

## Acceptance Criteria

Proposal page should not show javascript-based error.

**Comment by jnaviask** [comment]
Handing this ticket off to @mhagel to investigate whether we're failing to load proposal titles for some reason.

**Comment by mhagel** [comment]
Something has regressed. Now: 

`Cannot read properties of undefined (reading 'readOnly')`

![Screen Shot 2023-06-26 at 11 11 02 AM](https://github.com/hicommonwealth/commonwealth/assets/9438198/196c9644-d3ec-4cfa-943c-174c2bc2aba6)

**Comment by mhagel** [comment]
It is worth noting that we could have caught this with our E2E test suite if we could run `proposals.spec.ts` in CI.

**Comment by mhagel** [comment]
I reopened this ticket because the spirit of it was the same as the newly discovered bug. However the root cause and specific error was different. There were some null references introduced to a wrapper component cw_content_page. 

I also found a race condition that caused the proposal page to be re-fetched without metadata. This was remedied with a `useRef`  in `view_proposal` fetch to avoid overwriting proposal that is already fully loaded: #4341.
