### ISSUE TITLE
Image Compression Solution

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4238]
## Problem
Images added to the app (via a number of vectors) are not being compressed or otherwise handled in an efficient manner. This is happening in a number of places including the [forum](https://github.com/hicommonwealth/commonwealth/issues/4222), & [user profiles](https://github.com/hicommonwealth/commonwealth/issues/4222#issuecomment-1589485315) & [adding community icons](https://github.com/hicommonwealth/commonwealth/pull/2374), that later of which was significantly reworked a while back by @kurtisassad.  

Moreover we need to have a unified approach here that we extend for each use case, rather than a collection of one off tickets such as linked above. 

## Engineering Requirements
- Need an inventory of site images by type, such that we can set max image size, and hence compression, but image category across app. 
  - eg. How big should a user avatar image file be? What is the maximum size images need to be saved off as? What is the multiplier for retina displays? For liquid retina displays? (arm64-m2) Do we need to or intend to support 4k displays? (product question) 
- It should go without saying that image compression should be handled client side (to avoid sending all the extra data over the wire.) 
- A single unified approach to image compression (as DRY as possible) that can be used/extended for each of the identified use cases. 

## Acceptance Criteria
1. Step one is to complete inventory of affected use cases. 
2. Next, we need to to define max sizes for each of these categories. 
3. Decide on actual compression 
4. Make recommendation on whether to include converting uploaded images to .webp format in the current scope, or circle back later to make that change across app. 
5. Meets Engineering Requirements as above. (so below) 

## Additional considerations
- Roadmap: Currently we save images in whatever format user submits. We would prefer to not just compress, but convert to a standard format -webp, for example- and it seems like it makes more sense to do that as part of this story scope, rather than defining  a compression strategy to handle all the different formats. 
- Max image size here implies minimum size for various UGC images across the site. TBC: Not _necessarily_ included in current scope (viz. additional considerations.) 
-

**Comment by CowMuon** [comment]
After some discussion, preference here is to go straight to .webp, unless there is an identified reason why not to.

**Comment by alexyoung23j** [comment]
Implementation:

1. Modify `compressImage` to always compress to .webp
2. Modify `useImageUploader` and `useImageDropAndPaste` hooks to incorporate `compressImage`.
3. Modify `AvatarUpload` to use `compressImage`.
4. Decide on maximum sizes for each use case.

**Comment by alexyoung23j** [comment]
Based on discussions with @NakulManchanda and @kurtisassad, here is the situation:

We have an [open PR](https://github.com/hicommonwealth/commonwealth/pull/2930) that is an unfinished implementation of the cloudflare solution discussed in the parking lot. If we pursue this option, and it works (needs to be fully tested), the following things are true:

- Images can be uploaded in whatever format the user wants, but they will be served to our site as .webp (cloudflare is handling the conversion)
- There will not be a size limit imposed on the images that are uploaded, but there will be a size limit when they are served on the site

The benefits of actually going forward with this ticket (changing the _upload_ situation, not changing the previously uploaded content): 
- We save some s3 costs because images are compressed client side before uploading
- Going forward, we have a standardized image format. Unclear to me that this is actually worth much in terms of DevEx or performance; no matter the image format we are just fetching it and displaying to users.

The benefits of also going back through previously uploaded content and converting to .webp:
- it's parsimonious and consistent? Again, unclear on what the actual win is here because I don't fully see why DevEx is improved at all.

So I guess my question for you @MuonShot was what specifically was the impetus for writing this ticket? What are the specific things about either DevEx or site performance or costs we want improved? I think answers to that will help determine whether we should move forward with this ticket as written or defer finishing to Kurtis' PR, or neither.

**Comment by CowMuon** [comment]
What decisions need to be made by today / tomorrow, or initial work on this will be blocked? IOW, what is the order of operations for executing scope of work here?

**Comment by alexyoung23j** [comment]
Key decisions, in order:

1. Should be pursue Kurtis/Nakul solution _instead_ of this ticket?
2. If kurtis/nakul solution does not work, should we still do this ticket and why?

**Comment by CowMuon** [comment]
Can we get an update how far we got on this, and an estimate how far out (ie how many hours) we are from delivery on this? @alexyoung23j 

[viz. to get this out the door tomorrow]

**Comment by CowMuon** [comment]
Set this to In Progress on the new board; I did see it got sent back to Teed Up, but without an explanatory comment.

**Comment by alexyoung23j** [comment]
Do not have the appropriate AWS permissions (or was added to the wrong org) to view our current buckets. Need this access to proceed.

**Comment by alexyoung23j** [comment]
Update!! 

Just worked with @kurtisassad to get this ready to go. We did the following:

1. Created a new bucket called assets.commonwealth.im and copied ALL contents of existing bucket commonwealth-uploads to this new bucket. 
2. Set up a cloudflare to cache assets and compress them to .webp format. Because the cache needs to be renewed for this to take work, 12 hours or so will need to elapse before this takes effect.
3. Updated #2930 to reflect this new bucket. This is a migration that converts all image urls in the DB to the new bucket.

Next steps:
1. Run migration on a staging environment. 
2. Ensure that the content is all still available and being fetched as webp. 

@MuonShot

**Comment by CowMuon** [comment]
@alexyoung23j Moved to has PR but no PR added under Development?

**Comment by kurtisassad** [comment]
I have linked the PR now, Basically the CDN PR fixes this ticket as well as the CDN ticket.

**Comment by CowMuon** [comment]
#2930 is still marked as draft? What's the correct status there? @kurtisassad

**Comment by kurtisassad** [comment]
Still in draft because I would like to test it on staging before we review it. Unfortunately all staging envs are in use right now.

**Comment by CowMuon** [comment]
We will need an update to the team wiki documenting what changes were made in Cloudflare for compressed images along with any information how it was setup, expected ongoing concerns, troubleshooting, etc. @alexyoung23j @kurtisassad

**Comment by jnaviask** [comment]
Not closed until CDN settings are properly configured + documented.

**Comment by alexyoung23j** [comment]
https://www.npmjs.com/package/browser-image-compression Potential package to use for client side compression.

**Comment by jnaviask** [comment]
@alexyoung23j what is the scope of work here that you have in progress = what exact steps are you planning on taking?

**Comment by alexyoung23j** [comment]
@jnaviask Since the other PR went in that included the bucket changes + cloudflare polish updates, the scope now is simply to ensure that all images uploaded are compressed to ensure that Cloudflare Polish (which automatically tries to converts all images to webp) is able to succeed as often as possible. If images are already uploaded or optimized on upload, Polish does nothing, but based on this [page](https://developers.cloudflare.com/images/polish/cf-polished-statuses/) in their docs, images should be less than 10mb and have a maximum height or width or 1000px in order for Polish to be used most often. So I will have a PR up in a few minutes that uses a package [browser-image-compression](https://www.npmjs.com/package/browser-image-compression) to ensure those constraints before we upload to s3. I don't really understand what @CowMuon was getting at on the call today- hopefully this answers the question you had.

**Comment by CowMuon** [comment]
> If images are already uploaded or optimized on upload,

What exactly does it mean for images to be "already uploaded on upload"? @alexyoung23j

**Comment by alexyoung23j** [comment]
@MuonShot ah just meant that Polish may not work on images that are already in the bucket, if they are larger than the constraints. After this PR goes in, newly uploaded images will all be compatible with Polish
