### ISSUE TITLE
Research Heroku Multi-Region (potentially Enterprise) for solving the Asia slump

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#4284]
## Description
Heroku offers solutions for managing resources in multiple regions. This should be fully researched and vetted before we consider moving the databases to a separate cloud service. 

## Desired Results
The result of this ticket should include a definitive answer as to whether utilizing Heroku to speed up requests from Asia is not only possible but viable and why. If it is found to not be viable a new research spike ticket should be opened to research alternate solutions. If it is found to be viable the result should include a preliminary guide for enabling multi-region setups within Heroku (to be followed up with a proper spec if required).

**Comment by CowMuon** [comment]
Thanks for starting the ticket here Tim, way to the ground running & welcome back! 

As we discussed Vendredi solution here is based on understanding that is in fact the database round-trip time for otherwise uncacheable queries that is the primary reason for the performance delta between here and there, so to speak. (Now that Euro benchmarks are up and focus moves East to Asia.) 

Don't take as gospel, as I'm not a Heroku person ;-p mais I don't think the Enterprise level gives you anything like geo-replication out of the box, or even something like aurora + regions (which would most likely be the aws service we could leverage here, were we to go in that direction.) 

Rather, I believe we take our pick of the same Heroku marketplace offerings we already have available to us for db replication across regtions, with the added ability to deploy any of this into the Private Namespaces (and presumably faster backbone though this is unconfirmed to be true) that comes at the Enterprise level. 

We should also keep @mzparacha looped in, as we do need to solve for not only the READ side of CRRS in Asia, so that any and all request routes (thanks to @rbennettcw's great work cleaning up routes so we are not mixing up command and request routes) are served by a geographically closer read replica of the database, but also WRITES on the Command side of our CQRS, by definition un-cachaable. 

So rather than chasing the cache at the end of that rainbow, the Common client app guarantees actions the user takes, take effect immediately, optimistically, so that waiting for a database write is no longer a blocking operation, it is a side effect. 

Most of which is beyond the immediate scope here, but important to surface in the greater context of our global application and data architecture.

**Comment by timolegros** [comment]
@NakulManchanda is handling the Singapore slump issue and has researched the necessary solutions. Any research results should come from him.
