### ISSUE TITLE
🪣 Addresses Frictions / Session Key Blockers Bucket 

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4314]
##  🥅 Goal
The goal is to ensure users understand that with unified profiles, they can have different addresses linked within the same profile/Common identity, while letting them know within the product when a session key has expired so they are clear on the actions they can and need to take to conduct community-level actions.

### Development tasks

- [x] #4413
- [x] #4315 <= Objective 2
- [x] #4317 <= Objective 3
- [ ] #4651 - cleanup (should be done after QA, might be either before or after the production deployment)

### ~~QA Session~~ Product/Design Review issues

- [x] #4917 
- [x] #4918 
- [x] #4919 
- [x] #4945 

### 5 Remaining Launch Blockers 
- [x] #5047
- [x] #5048
- [x] #5049
- [x] #5050
- [x] #5051

## High level updates
- Update universal nav
- Top nav user dropdown that is simplified and clearly shows all their linked addresses,
- Updated community nav to add two new components:
    - Moving `Join` which is a community-level action to the community sidebar
    - Adding the `Connected` or `Not connected` address very clearly in the community sidebar

## Documents for full ~~scope~~ context!
- 📺 [[Loom walkthrough](https://www.loom.com/share/e9d866f53baf4630a234b7e75e511c1f?sid=54f3720f-00b6-45b5-9eca-cdde1af3c942)](https://www.loom.com/share/e9d866f53baf4630a234b7e75e511c1f?sid=54f3720f-00b6-45b5-9eca-cdde1af3c942)
- ▶️ [[Prototype](https://www.figma.com/proto/mJMPTzEnpEFIaR2wBWkElq/Session-Keys-and-Login?page-id=256%3A59608&type=design&node-id=256-63044&viewport=-5458%2C-248%2C0.52&t=BUcPVUnzhqZB7N3K-1&scaling=min-zoom&starting-point-node-id=256%3A63044&mode=design)](https://www.figma.com/proto/mJMPTzEnpEFIaR2wBWkElq/Session-Keys-and-Login?page-id=256%3A59608&type=design&node-id=256-63044&viewport=-5458%2C-248%2C0.52&t=BUcPVUnzhqZB7N3K-1&scaling=min-zoom&starting-point-node-id=256%3A63044&mode=design)
- 🎨 [[Figma file](https://www.figma.com/file/mJMPTzEnpEFIaR2wBWkElq/Session-Keys-and-Login?type=design&node-id=256%3A59608&mode=design&t=UmHX1RO1rPQXAzhT-1)](https://www.figma.com/file/mJMPTzEnpEFIaR2wBWkElq/Session-Keys-and-Login?type=design&node-id=256%3A59608&mode=design&t=UmHX1RO1rPQXAzhT-1)

**Blocking the deployment of Session Keys to Common**

**Comment by raykyri** [comment]
All caught up, and formatting issues should be fixed now!

**Comment by masvelio** [comment]
@raykyri I am writing down my observations after looking at the code, before I start hooking up 3 UI components:
1. Address status indicator in left sidebar
2. Blue information banner
3. User dropdown with addresses

![Screenshot 2023-08-04 at 14 48 09](https://github.com/hicommonwealth/commonwealth/assets/14819225/59c18462-7aaa-410d-be9a-c25ee6310953)


What I need:
- for the user dropdown: 
  - list of user’s unique addresses => app.user.addresses / app.user.acctiveAccounts ?
- for displaying `signed out` info in user dropdown: 
  - state of the session key for each address
- for displaying green checkmark in user dropdown: 
  - information if the address has joined particular community 
- for displaying `joined` button in left sidebar: 
  - information if the address has joined particular community 
- for displaying blue banner: 
  - information if the address has joined particular community & information if the user has other address that already joined particular community



Apart of it:
- we need to change the current logic because right now, when user connects new address with `connect a new address` button, the address is automatically joined to the community. We need to split this behaviour into two steps, so the user can add the address without joining and to join, he needs to click `join community` button manually. We talked about that with Zak [here in the comment (point 3)](https://github.com/hicommonwealth/commonwealth/issues/4413#issuecomment-1634503393)

**Comment by masvelio** [comment]
@jnaviask @zakhap @raykyri Update from my side before my one week off.

- UI is done, merged into the master, hidden behind `FLAG_SESSION_KEYS` feature flag. Components are not functional (#4634 & #4584). 
- started looking on the code how we should hook up the components to make it work in a new way
- left some questions above in the comment. Answers will help me to start working on it again when I will be back on August 14th so please make sure that questions are answered before my return

**Comment by raykyri** [comment]
Hey, quick answers for the above:

> list of user’s unique addresses => app.user.addresses / app.user.activeAccounts ?

Prefer activeAccounts, that should be the list of accounts that pertain to the currently active community.  app.user.addresses might include addresses from alternative chains.

> for displaying signed out info in user dropdown:
> state of the session key for each address

`controller.hasAuthenticatedSession()` inside client/scripts/controllers/server/sessions.ts.

> for displaying green checkmark in user dropdown:
> information if the address has joined particular community
> for displaying joined button in left sidebar:
> information if the address has joined particular community
> for displaying blue banner:
> information if the address has joined particular community & information if the user has other address that already joined particular community

I'm not the owner for this, but line 144 in useJoinCommunity.tsx `app.roles.getRoleInCommunity()` seems to do this?

And finally, if Malik's work on react-query has merged, we should merge this branch into `raymond.react-session-keys-on-merge` and that will make reconciling these branches pretty easy.

**Comment by masvelio** [comment]
> Re 1/2: the only non-login-related actions required are those signed by session keys, which are the 3 Ray noted: creating a thread, creating a comment, creating a reaction. As for login-related actions, if the "basic" login works as expected on all chains, and we verify all of the actions on one chain, we should be good, as the core reason for testing all chains is to ensure the _chain-specific signing logic_ works as anticipated in all cases.

Just FYI, we have more actions that needs sessions keys:
- threads
  - create, edit, delete,
  - thread reaction: upvote/unvote
- comments
  - create, edit, delete
  - comment reaction: upvote/unvote 

> Re 4: I will create a tracking ticket for Session Keys QA, although I'm unsure exactly what TODO items would go in it to begin with besides chain-based testing. Would like feedback here.

In here, I was thinking about bugs or any other defects that we will find during the QA. So for now, nothing is TODO, because we are unaware of any "blockers". But whoever finds it, should ticket it and attach it either here in the bucket or the ticket you will create.

**Comment by masvelio** [comment]
@jessmart1213 It would be great if you could familiarise with Session Keys, because we will need your review soon (maybe this week, we are working on pushing this to the QA environment). Probably would be good for you to go through `Documents for full scope!` from the description above to get the broader context. If you want a full picture, you can also go through the separate tickets and comments sections (https://github.com/hicommonwealth/commonwealth/issues/4413, https://github.com/hicommonwealth/commonwealth/issues/4315, https://github.com/hicommonwealth/commonwealth/issues/4317). However, there were a lot of back and forth during the development and as a result, the scope got cut down quite a bit. Thus, not everything from Figma is relevant anymore. Below, I am attaching 3 comments that summarise work that eventually has been done for each individual ticket, which is decent TLDR
- https://github.com/hicommonwealth/commonwealth/issues/4413#issuecomment-1686548192
- https://github.com/hicommonwealth/commonwealth/issues/4315#issuecomment-1686502698
- https://github.com/hicommonwealth/commonwealth/issues/4317#issuecomment-1691678481

**Comment by raykyri** [comment]
Thanks @masvelio!! This looks generally really good.

Started a discussion with Slack, copying a shorter version here for record:

Engineering led items:
- When you re-validate a session with a different wallet than the one that was requested by the SessionRevalidationModal, the modal closes without doing anything (the account isn't switched). Instead of closing the modal, the modal should show an error message. I think there was an error message in the previous revision that can be used for this.
- Logging in with a new account ("Connect account") results in that account being "Logged out" without a valid session. Upon refreshing the session is then loaded correctly from localStorage. We should call the method on the sessions controller to auth the session immediately though

Design items: 
- Logout button (in menu?)
- Feedback button / Docs button appear to be swapped
- Docs should open in a new window, for consistency
- Not obvious what the buttons do; recommend adding tooltips
- Explore Communities button shown on custom domains?
- Create/explore buttons are duplicated on the left sidebar, could be confusing to have both

**Comment by CowMuon** [comment]
Added 5 [remaining launch blockers](https://www.notion.so/buildcommon/Session-keys-product-acceptance-testing-313fb2c93d9f47e084320c26717597fb) to main description (above) but did not update bucket points.
