### ISSUE TITLE
Draft Pagination Standard

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4326]
## Summary

Pagination is currently implemented in a few parts of the app.

We should draft a proposal for how pagination is to be implemented consistently across the app for the UI and backend API.

## API
Currently, across all paginated API endpoints, we use the same pattern of applying a limit/offset to the SQL query.

⚠️ A Big Question: *Do we want to implement cursor-based pagination?*
- ✅ Apparently when using limit/offset, "incremental page numbers scale poorly—the bigger the page number, the slower the query". Source: https://shopify.engineering/pagination-relative-cursors
- ❌ However, since we have a mix of ORM and complex raw SQL queries with multiple sort columns, this might not be an easy change to apply universally.

Regardless, we should aim to have consistency in a few parts:
- Query Params –– which variable names to use + choose either snake_cake or camelCase
- Code Pattern –– for converting user query params into SQL bindings + setting default values (helper functions?)
- Payload Data Structure –– for payload returned with results + pagination metadata

## UI
We should aim to manage the *least* amount of pagination state in the UI. This means having the API endpoints return pagination metadata (page number, page size, total number of items, etc.).

---

✏️ Once this proposal is drafted, we should create tickets to apply the updates to the codebase.

**Comment by rbennettcw** [comment]
@mzparacha I've created this ticket and assigned both of us to it since we've both recently been working on both sides of the relevant code.

**Comment by mzparacha** [comment]
Thanks for the tag @rbennettcw. I will look into it today.

**Comment by mzparacha** [comment]
> ⚠️ A Big Question: Do we want to implement cursor-based pagination?
✅ Apparently when using limit/offset, "incremental page numbers scale poorly—the bigger the page number, the slower the query". Source: https://shopify.engineering/pagination-relative-cursors
❌ However, since we have a mix of ORM and complex raw SQL queries with multiple sort columns, this might not be an easy change to apply universally.

This is interesting, not sure if other forms of cursor pagination like (`Relative Cursor Pagination`/`Seek Pagination`, etc) scale better?

> Regardless, we should aim to have consistency in a few parts:
> Query Params –– which variable names to use + choose either snake_cake or camelCase

I have noticed that frontend/UI areas mostly use camel case while in db we have snake case and most API responses are snake case (please correct if wrong) --  for consistency, we could use camel/snake in areas where its already used (or if we want to have the same everywhere it would be a huge refactor but doable)

> Code Pattern –– for converting user query params into SQL bindings + setting default values (helper functions?)

Default values would be great.

> Payload Data Structure –– for payload returned with results + pagination metadata

just leaving this here for discussion
```
{
    results: [
        // data/objects
    ],
    // pagination params (cursor based)
    limit: x,
    page: x,
    totalPages: x,
    totalResults: x,
}
```

> UI
We should aim to manage the least amount of pagination state in the UI. This means having the API endpoints return pagination metadata (page number, page size, total number of items, etc.).

Sounds good (to add I think generally we should manage the least amount of data in other areas as well - the required data only)

**Comment by rbennettcw** [comment]
Regarding cursor-based pagination in general, I think that there's a fundamental problem we'll run into: cursor-based pagination requires a unique sequential column, like an ID. So it won't work with "dynamic" columns like `rank`, `numberOfComments`, `numberOfLikes`, etc. I think we should continue with the limit/offset approach and then at a later time, profile performance to see if improvements are needed.

About camelCase vs snake_case–– yeah, the UI tends to be camelCase and the DB variables are snake_case. I 100% agree that those should remain the same as they are. My primary concern was around query parameters, which I think should always be `snake_case`, as it requires more mental effort if we mix and match.

As for variable naming–– While the DB uses the terms `limit` and `offset`– in the UI/API, I've been using the variable names `page` and `pageSize`, because it's more human-readable. I see that you've chosen `page` and `limit`– that works too.

The data structure example you showed is good and I have no issues with it.

**Comment by mzparacha** [comment]
Great, so I think the next action item here is to make a draft of the required changes (procedural) and which endpoints we should update, make tickets/sub-tickets, and then proceed onward. Thoughts @rbennettcw

**Comment by rbennettcw** [comment]
I'm going to:
- Create a wiki doc for the pagination specification
- Create tickets for the affected endpoints

**Comment by rbennettcw** [comment]
I've added the pagination standard wiki doc: https://github.com/hicommonwealth/commonwealth/wiki/Pagination

**Comment by rbennettcw** [comment]
Created new ticket for code updates: [#4455](https://github.com/hicommonwealth/commonwealth/issues/4455)
