### ISSUE TITLE
Show CTA Banner when not a joined

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4380]
## Description

- Show a CTA banner to logged-in users who have not joined the community.

### Banner

![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/e7f74e14-3e76-4194-bf37-1f1fe28cb87a)

- User stories
    - As a user, I need to know that I must join a community to participate in any way.
    - As a user, I want better visibility around joining a community.
- Design specifications
    - Appears 24px under the editor
    - Use new banners in design system with a few modifications.
        - Please see Figma file ‘Design Systems / 🚧 Components and Patterns’ > page ‘ [🟢 Banners and alerts](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=789%3A10883&mode=design&t=HyobTlUa6qSug8qe-1)' > and look for Banner default with actions.
            
            !![image](https://github.com/hicommonwealth/commonwealth/assets/133259695/73f8a781-4fed-4dab-acd6-e43bc37927a9)
            
    - Modifications
        - Use only 1 button
        - Use button Primary small, with no icons.
    - Copy
        - Title: Want to contribute to this discussion?
        - Content: Join now to engage in discussions, leave comments, reply to others, upvote content, and enjoy a host of additional features.
        - Button: Join Community
- Behavior
    - Appears when a user is logged in but has not joined a community they are currently viewing.
    - When user clicks ‘X’ icon, the banner disappears.
    - Banner should come back after 1w of time has passed OR the user clears their cache/local storage. 
    - Pressing "Join Community" is the same behavior as pressing the existing "Join Community" button.

**Comment by masvelio** [comment]
@MuonShot @zakhap 

1. The story says that we should use `banners and alerts` components from new design system. We don't have `banners and alerts` implemented yet. Reasonable approach would be to create those components first and add them to the storybook. After they are merged, we can start using them. If you agree, I need the ticket for creating `banners and alerts` which will be blocker for this ticket #4380.
2. Banners and alerts are always meant to be displayed in a static form (display: block) or they should also be handled as components overlaying the content, something like a modal (position: absolute)? It is important to know this before implementation of `banners and alerts` components.
3. Story says `Appears 24px under the editor`. It should be between the editor and the buttons or under the buttons?
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/2d4b83e8-3bfd-4978-85c6-19d85d27418c)
4. Right now we have logic, that displays the info in the button `Join community to create`. If we introduce the banner, should copy of the button change somehow? Because in this situation we could join the community from the both button under the editor and button in the banner which is kinda weird. On the other hand, when we close out the banner,  having `Join community to create` makes sense. Something to think through. 
5. Just to be clear - this banner should be visible only in one place - when user wants to create thread but has not joined the community?

**Comment by zakhap** [comment]
The CTA Banner, as it's being used here, is as an in-line callout component. 

1. Yes, that is a reasonable approach. However, I also think it is acceptable to make the MVP component to execute this ticket as designed with a followup ticket to generalize/componentize to the [proper spec of the design system](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=789-10883&mode=design&t=coj8pg9TYJiNA20j-0). 
2. The component should be an inline block to the rest of the content on the page. No need for absolute or sticky positioning!
3.  It is beneath the buttons. See the bucket ticket for the task #4306 for full scope of the project's aims. Image below to show more details. 
4. Similar to 3 above, the submit button should have normal copy but be disabled. See image below for pattern.
5. The banner should be in 2 locations: one beneath the new thread editor as you identified, and two inline to the comment tree comment editor, see image below. 

<img width="402" alt="Screen Shot 2023-07-05 at 9 44 26 AM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/b5b228e8-3b6a-4e17-94ad-5785cb7bc249">

**Comment by masvelio** [comment]
@zakhap 
1. Agree, would be nice anyways to create the ticket for `banners and alerts` components already and mention there that some initial work will be done within this ticket.
2. 👍 
3. The bucket story is helpful! Will be happy to take take care of the other tickets afterwards! I can also review them from eng perspective if you want!
4. I see conflicts here with the [figma designs for Quill](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=337-3536&mode=design&t=BP4IBce6fhQ4XXTb-0). [In my current PR](https://github.com/hicommonwealth/commonwealth/pull/4359) I implemented it in the way as it is in the designs so the copy of the button changes depending on the context (thread editor - post, comment editor - comment, comment reply editor - reply). So yeah, `submit` everywhere or the distinction as in the figma for quill?
5. Right know, if I am not part of the community, I cannot see the comment editor whatsoever. See image below. So the desired behaviour now is to show editor but block it from using, correct?
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/aecdf0ae-1ed5-49ac-ae94-e7f7d679c158)

**Comment by zakhap** [comment]
1. Feel free to make the ticket and add relevant information accordingly. I can add the rest of the design system handoff information from the figma file after the fact.
2. 🕺 
3. 🕺 That would be great!!
4. Let's just do "Submit" everywhere. As for the quill work currently in-flight, I will respond with a gameplan to get that resolved shortly on that ticket/PR!
5. Correct, the user should always see the comment editor which is not the current behavior. #4377 details what the disabled editor behavior should be, when not yet joined.

**Comment by masvelio** [comment]
@zakhap @meeshlin I wanted to start working on this tomorrow morning so please let me know if this is ready for development

**Comment by masvelio** [comment]
bumping up to 5 as it was underestimated. UI was easy but the logic part needs some more work

**Comment by CowMuon** [comment]
Per my comment on the PR, the merge conflict fix commit (mine) should be reverted, or just fixed to resolve that merge conflict.

**Comment by masvelio** [comment]
ready to merge
