### ISSUE TITLE
Show "Address removed from Common" for removed addresses

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4486]
## Description
When a user removes an address from Common that has been previously used, it creates confusion in the UX and elsewhere. While this ticket is not scoped to solve that entire problem, we do want to display a helpful message to the user. 

## Acceptance Criteria
When an address has been removed from Common, everywhere it would normally appear is replaced with the text "Address removed from Common"

**Comment by CowMuon** [comment]
@Miaplacidus The basic ask here is straightforward, to replace the address displayed with this placeholder text. The catch here is likely that this text isn't going to fit nicely in that space (unless using too teeny font) so mostly like it would need to be in a tool tip (which @martins87 is still working on?)

**Comment by martins87** [comment]
> @Miaplacidus The basic ask here is straightforward, to replace the address displayed with this placeholder text. The catch here is likely that this text isn't going to fit nicely in that space (unless using too teeny font) so mostly like it would need to be in a tool tip (which @martins87 is still working on?)

Tooltip branch and PR:
- [daniel.4123.tooltip](https://github.com/hicommonwealth/commonwealth/tree/daniel.4123.tooltip)
- https://github.com/hicommonwealth/commonwealth/pull/4514

**Comment by Miaplacidus** [comment]
@CowMuon I wanted to know if you could provide any specific locations where the UI is lacking when an address has been removed. Thus far, address removal seems as though it's being handled properly in the UI, i.e. I can't find a place where it looks off. 

@martins87 I'll consider this card the implementation of your storybook work if implemented.

**Comment by Miaplacidus** [comment]
@CowMuon 
Left questions on this previously that weren't answered, but taking another look at this...

**Comment by Miaplacidus** [comment]
@jnaviask @CowMuon 
Not sure where it would be appropriate to add an "Address removed from Common" message. 
Removing an address seems to be handled pretty well right now. For instance, the connected button just becomes a join button and any threads created using a deleted address still display the address, there's simply no user associated with it when you hover over what would be the user avatar.

**Comment by jessmart1213** [comment]
@CowMuon @jnaviask @zakhap 

So removing an address is little complicated because our product account/profile/ address management is quite complicated in that allows multiple address to be associated with a 1 account. 

Im going to answer the following as thoughts come to me, because the more I think I about how to handle removing an address the larger in scope it becomes for me. But I want to be clear that there is no larger project I am currently working on that relates to this and the following are thoughts not action items. For action items on this, I would involve product as these are decisions we haven't addressed yet. 

---

I don't we need copy replacing the address where it previously existed.

For posts, comments and other content produced by a user using a now removed address, we can have a tooltip on:hover that saying "Address removed".

If the user deletes their account, which I don't actually know if they can do so, then we can have a tooltip saying "Inactive member" or "Deactivated since [date]"

As a user viewing a community that I was previously connected to via a now removed address, as @Miaplacidus said, that Connected module would show me the "Join" button again.

On the edit profile page, the only current way for users to manage their addresses, if I have only one address connected, what happens if I remove that address? I say you're essentially deleting your account, so we should not show users this option. 

Because we do allow users multiple addresses, ad because content of their will still exists if they remove an address, it may be beneficial on the edit profile page to show removed addresses, but this is future thinking.

**Comment by CowMuon** [comment]
@Miaplacidus Can you quickly add the tooltip on:hover ("Address removed") assumed to be a 1 pointer, and then let's all circle back on what the mobile experience is.

**Comment by dillchen** [comment]
I will add this as a discussion item for Mobile Friday

**Comment by Miaplacidus** [comment]
@CowMuon 
I've added "Address removed" on the user avatar tooltip present on threads.
