### ISSUE TITLE
Need service health checks

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#4536]
## Description
Given report that our Telegram bot "seems like it stopped working at some point" we need to get heartbeats in place for all services to monitor uptime and immediately alert on any service outage. 

## Engineering Requirements

- [ ] List of all services that need health checks.
- [ ] Set up healthcheck monitoring for each.
- [ ] Set up pager alerts for service outages.

**Comment by rbennettcw** [comment]
My main questions are:
- What services are currently running in production? I'm aware of the main app and chain events. Anything else @kurtisassad @ianrowan ?
- These services are all hosted on Heroku? So the health check solution could be part of the Heroku platform, otherwise an external tool could work for publicly exposed health check routes.

**Comment by rbennettcw** [comment]
Kurtis responded via DM.

**Comment by ianrowan** [comment]
@rbennettcw We now have the discobot-listener running in production based off of packages/discord-bot. Its running as a heroku app

**Comment by jnaviask** [comment]
@rbennettcw Currently we have the following services:
- discobot-listener
- snapshot-listener
- chain-events
- (not sure if still used): commonbot and commonbot-ui
- commonwealth main app (ofc)

discobot-listener, snapshot-listener, and chain-events mostly function by way of writing to RMQ, so there's no obvious queries we can make against the service. We might instead want to use a datadog heartbeat + create a table which shows us uptime, but ofc I am open to alternative solutions. All are indeed running on heroku, but in separate applications / environments, so there's no clear built-in solution that lets us view all of the services' health at a glance.

**Comment by rbennettcw** [comment]
@jnaviask Alright, I've got results showing up in the datadog dashboard. Each service sends a `gauge` event with a value of `0` for unhealthy and `1` for healthy.

<img width="644" alt="CleanShot 2023-08-07 at 13 31 29@2x" src="https://github.com/hicommonwealth/commonwealth/assets/126922418/2a8e4420-ec91-4280-afa3-a89829ce1267">

The goal at this point was to simply get events showing up in DD, then figure out where to go from there.

One issue with this approach (each service recording its own health status) is that events are only sent when the service process is running (and properly configured to connect with the DD agent). If a service process exits, it will no longer send any more guage events, so the chart won't change in value during process downtime. An external check would be required for that.

The only reason there's the tiny slope at the start is because of a small period of time where the process was running but the service wasn't initialized yet, thus it was unhealthy.

---

So the main goal is to detect downtime and trigger alerts.

One way to properly detect downtime with this "internal healthchecks approach" is to programmatically check "if last healthcheck value is 0 or last healthcheck was over 1 minute ago, then service is down", assuming each healthcheck occurs in < 1m intervals.

As for implementation, it seems like creating a new "healthcheck service" is the way to go. It would:
- Check all services continuously for downtime
- Send alerts to Slack
- Persist historical uptime status for all services to DB

Before going deeper down this path, I wanted to see what your thoughts were.

**Comment by rbennettcw** [comment]
Also, are there any cost concerns with DataDog that I should consider in the implementation?

Currently, I've got it sending 1 event per service (there are 7) every few seconds for testing purposes. I imagine once finalized, we'd have it send healthcheck status every 30-60 seconds per service.

**Comment by jnaviask** [comment]
@rbennettcw datadog cost isn't a concern for the volume of usage we're doing. I think your approach is fine as minimum viable. We can expand it later to add more bells and whistles. I know datadog may have nice features internally that should make it fairly easy to spin up monitors for these heartbeat metrics.

My one caveat is I would describe the healthcheck service as a "module" rather than a "service", because it's going to be imported by all packages. It should live inside `common-common`, as that's where modules used by all packages in the monorepo should go.

Looking forward to checking it out! Let me know if you need any slack admin configuration to set up datadog eventing.

**Comment by rbennettcw** [comment]
@jnaviask Currently, what I've implemented is already as you described. A shared module inside `common-common`, imported into all services: https://github.com/hicommonwealth/commonwealth/pull/4704/files

All 7 services import this module and start the healthcheck loop at the init of each service, sending out a heartbeat event every N seconds. The stat is based on the service name: `service.health.commonwealth`, `service.health.discord-bot-listener`, `service.snapshot-listener`, etc.

---

The part that I had trouble with was getting datadog to detect the absense of a heartbeat within a window of time. If datadog can do that (which I'm sure it can), then we can setup alerts within datadog and probably don't need to create a new "healthcheck service" at all.

**Comment by jnaviask** [comment]
According to [this forum thread](https://community.zenduty.com/t/heartbeat-monitoring-with-datadog/465) there is a "Notify if data is missing for more than 10 minutes" option in the Metrics Monitors section on Datadog. Should probably suffice? @rbennettcw

**Comment by rbennettcw** [comment]
Funny enough I saw that same page earlier and I've been looking for it. I'm seeing a few options that might suffice.
