### ISSUE TITLE
Database Cleaner fails due to deadlock

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4590]
## Describe the bug

Database cleaner run fails midway due to deadlock detected. See: https://app.rollbar.com/a/commonwealth/fix/item/Commonwealth/7132

## To Reproduce

Set the `DATABASE_CLEAN_HOUR` to the current UTC time (Eastern Time + 4). Look in the logs to verify the database cleaner has started. Wait for the failure to be reported.

## Expected behavior

The database cleaner runs successfully.

## "How We Fixed It"

TBD

## Additional context

Likely due to the cleaner running on both web dynos on production simultaneously, so they interfere with each others' queries.

**Comment by timolegros** [comment]
Implemented a solution that uses Redis to create a lock so that only a single databaseCleaner (the first/fastest one) can clean. This however means that execution to completion is not guaranteed since if a dyno shuts down while cleaning (after setting the lock) then no other cleaner can execute until the next day. Also, if Redis cannot be reached in order to create the lock then cleaning is delayed until the next day. This behaviour is acceptable since there is no strict policy that notifications _cannot_ be older than 3 months old.

This adds RedisCache as a dependency for cleaning based on timeouts.

Will be testing on Frick/Frack tomorrow.

Let me know if this solution seems acceptable @jnaviask.
