### ISSUE TITLE
Mixpanel metrics for forum interactions do not expose browser info

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4641]
## Describe the bug

On mixpanel, certain events like Session Start and Login return far more tagged metadata than other events, like forum interactions.

## Expected behavior

Mixpanel metrics should all be tagged with the same metadata as in the Session Start / Login metrics.

**Comment by rbennettcw** [comment]
We capture events via mixpanel in both the API and UI.

The reason the forum interactions don't include browser metadata is because those are captured on the server side.

- The light solution would be to add the request useragent to the server captured events.
- Or we can move the server captured events to the frontend, which will automatically include browser info.
- I assume we don't want to capture a given event on both sides, since we'd see duplicate events show up in the dashboard.

Thoughts @jnaviask ?

**Comment by jnaviask** [comment]
@rbennettcw I think adding the request useragent + any additional metadata needed to server captured events would be a sufficient solution. I think we're better off with server side tracking of interactions for now, because users cannot ad-block it.
