### ISSUE TITLE
Spike: research tRPC framework for fullstack type safety

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#4691]
The tRPC framework was mentioned by Marcin as a solution we should look into for implementing shared types between backend and frontend: https://trpc.io/

## Acceptance Criteria
- Assess the pros/cons of tRPC in relation to our platform goals
- Assess the amount of effort required to perform a partial/full migration to tRPC

**Comment by rbennettcw** [comment]
cc @masvelio @jnaviask

**Comment by kurtisassad** [comment]
I have added a PR which represents a PoC for TRPC. After going through the process of implementing it, these are the PROs and CONs I see:

PROs:
- Full stack type safety: Any change to the zod schema will result in errors in both the back and front end. This will allow developers to catch mistakes at static typecheck time, rather than at runtime. This will reduce errors.
- Extremely easy react query integration: After the backend API is implemented, you just make a call (see reaction_button.tsx in the PoC PR).
- OpenApi doc generation. We will be able to autogenerate documentation for the API and server it through the docs. This will effectively replace the "external API" and allow other developers to write clients for our backend.

CONs:
- RPC: Because it has a totally different methodology than REST (paths represent actions as opposed to nouns), it will be a little more tricky than a direct migration on the backend, as we will need to rename into a different paradigm. This will also make our backend more difficult for other developers to build clients off our backend, as RPC is usually more tailor made to the use case, rather than a more generic REST interface.

**Comment by kurtisassad** [comment]
Trpc is in now
