### ISSUE TITLE
Decide course of action for `/writeUserSettings`

### ISSUE THREAD

**Issue by mzparacha** [hicommonwealth/commonwealth#4701]
We have a `POST /writeUserSettings` api call from this file

https://github.com/hicommonwealth/commonwealth/blob/90041bd91360ab2e419ff11c506200d318421118/packages/commonwealth/client/scripts/controllers/app/login.ts#L147-L167

We call this API whenever we create a thread [here](https://github.com/hicommonwealth/commonwealth/blob/90041bd91360ab2e419ff11c506200d318421118/packages/commonwealth/client/scripts/controllers/server/threads.ts#L347)

Questions
1. Why this was added originally?
2. Do we need this now? If not what update caused it to become obsolete?
3. How to proceed from here

**Comment by jnaviask** [comment]
Timebox for research + writeup: 2 hours.

**Comment by CowMuon** [comment]
Do we know why this was originally added? @jnaviask @gdjohnson

**Comment by gdjohnson** [comment]
I have a vague memory from the olden days this was used to insert a "last seen" divider line in the discussion forum thread listing. Poking through the codebase it does seem like these values are still getting regularly tracked and proliferated, but it's not clear they're getting used for UX.

**Comment by rbennettcw** [comment]
Observations:
- ⚠️ The frontend doesn't use the `user.lastVisited` value
  - It's written to, but not read by the frontend for anything.
- ⚠️ The backend doesn't *directly* use the `user.lastVisited` value
  - The `user.updated_at` value is accessed by the `DatabaseCleaner` class to delete old entities from the DB.
  - It appears that the `user.updated_at` column is only fresh as a side effect of `user.lastVisited` being frequently updated by user actions.

If we remove the `user.lastVisited` column, we'd need to update the `DatabaseCleaner` class to use `address.last_active` instead of `user.lastVisited`

Fun fact: For profiles, we derive `profile.lastActive` from the profile's `address.last_active`

---

I see an opportunity to 
  - ✅ Remove (some) frontend calls to `/writeUserSetting` which will simplify UI code
  - ✅ Use backend-derived data for the last activity timestamp, which can't be spoofed by the client
  - ✅ Have a single source of truth (`address.last_active`) to represent user activity

**Comment by rbennettcw** [comment]
@jnaviask Thoughts on this?

**Comment by jnaviask** [comment]
@rbennettcw I am happy with the plan laid out here. My main concern regarding moving forward is that we have a specific definition of "last active" provided to us by business/product, which we need to ensure that IF we are already supporting, then we MUST continue to support. That definition is specifically documented on ticket #2956.

Would like to check in with @alexyoung23j on the status of related work product/business-side, and if we are clear to move forward with the plan here.

**Comment by alexyoung23j** [comment]
#2956 was closed by @MuonShot a while back because the implementation wasn't agreed upon by everyone. It was based on a request that product (or Dillon, I don't recall who) made to us once and then never brought up again. But in any case, it didn't touch the last active property on users; it was meant to provide a "last active" for chains. So no issues proceeding with @rbennettcw plan from my perspective.
