### ISSUE TITLE
Overview Page Delayed Loading Bug

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#4785]
## Describe the bug
Visual glitch when going to overview page, see video below

https://github.com/hicommonwealth/commonwealth/assets/16248081/25528429-1563-4274-9548-0b102e3c9cc7

## To Reproduce

Go to overview page.

## Expected behavior

No visual glitch, page loads when it's ready.

**Comment by mzparacha** [comment]
Hmm, I actually mentioned a reference to this bug [here](https://github.com/hicommonwealth/commonwealth/pull/4295#issuecomment-1660811096). After #4545, we are now loading active threads on the overview page instead of the chain init, which opened the window for the skeleton loader.

Should we implement it, @jnaviask @CowMuon @zakhap?
