### ISSUE TITLE
Deprecate unused thread-related routes

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4875]
## Description

Following #4830, we should delete the outstanding unused routes previously used to update threads.

**Comment by rbennettcw** [comment]
Since all of these routes have been combined into the patch thread route, the integration tests need to be updated. It'll take a bit more time to get the tests rewritten.

I also want to setup my local env with DB snapshots so I don't need to worry about destructive test runs during integration tests.

Updating to a 3.

**Comment by rbennettcw** [comment]
Got my local environment setup with DB snapshots, which is a big help.

However, I've been having issues running the integration tests locally. Test failures don't get logged locally, but they get reported to rollbar (which is the inverse of what should happen locally).

I'll work with Kurtis and/or others to get this resolved.
