### ISSUE TITLE
Convert feature flags from build time to server side

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#4903]
## Description
Currently our feature flags are environment variables which webpack resolves at build time. This is a "stronger" form of feature flag, as webpack will resolve the environment variable and potentially prune unused branches of code if disabled. However, webpack-based feature flags also means we need to trigger a _full rebuild_ in order to update the flag.

Since we want to avoid triggering rebuilds to enable and disable features, we should move toward a server-based feature flag approach instead, ideally using a standard tool in the space, as feature flags are effectively a solved problem.

## Engineering Requirements
tktktk

## Acceptance Criteria

tktktk

**Comment by kurtisassad** [comment]
Closing and linking this issue and referencing here:
https://github.com/hicommonwealth/commonwealth/issues/5026

I think the approach to go for is to feature flag the webpack middleware as described in the closed issue.
PROs:
- easy to implement
CONs:
- we lose customizability (turning on certain feature flags).

With this solution we would only need to modify the environment variable, then rerun the server, which would cause minimal downtime. The only part I am worried about is how we will get the 2.0 webpack bundle in the server build, with minimal copy-pasting.

Any thoughts?

**Comment by jnaviask** [comment]
Having to produce N different webpack bundles, maybe N! (for every combination of feature flags, where we may have N-many active at a time), seems infeasible.

Ideally our solution permits A-B testing / user-based flags as well.

I'm not familiar with the space of options in the nodejs ecosystem, so perhaps it's worth exploring to see if we can find something simple, light-weight, and industry-standard that meets our needs.

**Comment by kurtisassad** [comment]
Basically we need to determine what is the purpose of this ticket is. Is it to keep the 2.0 code in the repo so that it passes type checking and linting after refactors? Or is it to do A/B testing?

Since our front and backend are coupled to the same repo, it doesn't seem feasible feature flagging from the server side, since it will require copying the front end code. If the front and backend were split, we wouldn't even need to feature flag the backend code, we could just swap out the webpack bundles.

For A/B testing, I think it should be done at the infrastructure level. Since the webpack bundle is interchangeable, the solution would be to spin up 2 servers, one hosting webpack bundle A, one hosting B. Then load balancing them with some ratio (example 50% to server A, 50% to B). This solves the problem of things like statistics collection and extensibility in a way that doesn't interfere with the code itself. The problem is I don't know how feasible this approach is on Heroku, since it doesn't provide a lot of flexibility. If we were running a container based environment, we could start up multiple servers running different webpack bundles in the same node. But our current setup we need one server per node (again due to Heroku's inflexibility).


### TL/DR
If we want to do A/B testing correctly we need to:
1. Migrate to a more flexible SaaS (Or run IaaS)
2. Separate the front and backends into different repos (Or at least write the build step code to build the webpack bundle off a separate commit, and pull it into the build so that the server can serve it).

Outstanding questions:
What is the underlying purpose of this ticket? A/B testing or keeping 2.0 up to date with master.

**Comment by kurtisassad** [comment]
Ok looking more into the software side of things, basically all the standard tools are SaaSs that provide SDKs. This SaaS then has some dashboard that allows you to toggle these feature flags, which are then reflected in the server in real time (without any need for a rebuild and deployment).

I suggest we go with https://github.com/Unleash/unleash. They can provide a SaaS if we choose, but basically we can self host their server for the cost of compute. So the workflow would look like this:

1. add their SDK, convert our feature flags to use it
2. Either subscribe or self host our own unleash server.
3. set up the various pieces of the puzzle through the dashboard (which feature flags to enable for which servers, which ratios to send to which servers for A/B testing)

**Comment by kurtisassad** [comment]
## Implementation specific questions
1. Where will the analytics be stored

### 1
I feel it is better to have the analytics platform separate from our feature flag platform. Instead we will send the user impression data to mixpanel and do the analysis there. This means we should not choose a platform like optimizely which does both feature flagging and analytics.

## Non implementation specific questions (and my suggestions)
So the draft PR is working with unleash. I had presented it last Friday to the 2.0 to get product up to speed with what a feature flagging solution would look like, and to bring up early questions.

Questions brought up from the meeting:
1. What will be the rollout percentage (which percent of users will receive scenario B).
2. How will 2.0 features behind a feature flag interact with master branch workflow.

In my opinion these should be (open to feedback):

### 1
Let `canary release` be the release that we release the new feature behind the feature flag. We should set the rollout percentage based in order of the release like so:
1. 2% (`version(canary release)`). If no problems proceed to step 2. If problems restart step 1 in next release.
2. 50%. (`version(canary release) + 1`). If no problems go to step 2.
3. remove the feature flag. Meaning we go to 100% or 0% depending on statistics (`version(canary release) + 2`)

### 2
Since these features will be behind a feature flag, and can be disabled immediately. I think that non-leads can be dispatched to review the 2.0 work. This will free up time for the leads, and will lead to a more scalable process which will increase efficiency of merging work into master.

**Comment by mzparacha** [comment]
I don't know if this is the right question to ask but can we not use a simple frontend settings page to toggle in-development features (feature flag)?

**Comment by kurtisassad** [comment]
I guess there are 2 reasons I see why should use external software

1. Why reinvent the wheel. Sure it would only be a settings page plus some backend. But then we need to test it and make sure there are no security vulnerabilities. We will then also need to implement the backend for this which will require us to create new table.
2. We need this to be low latency. We shouldn't have to scale the server, we should be able to scale the feature flag server independently from the rest of the API. This is because we need a response before we can start building the feature flagged page for the user.

**Comment by mzparacha** [comment]
Got it. Thanks for the explanation @kurtisassad.

**Comment by kurtisassad** [comment]
Adding more to the discussion based off of todays presentation:

Feature flag service selection questions, what features do we want, how important are they:
* Analytics, should it be part of the feature flagging service? Or should we send user impression data to rollbar?
* Self hosting, how much do we value this?

Technical questions:
* **Will we run into cors issues?** If we were to release it as it is now, then yes. But we will need to add a DNS record to connect our domain with the service (if it is self hosted).
* **How do we scale the service given it needs to keep track of sticky sessions?** Unleash specifically has a concept of edge runners. This is basically primary/replica pattern, where each replica (edge runner) caches the feature flag config and sends responds to the user. We would have to use a geodns strategy for this and it could get complicated, because the different builds will need different unleash URLs.
