### ISSUE TITLE
When editing a draft, "Save as draft" shouldn't close the editor, and the button should be disabled if there are no changes

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#498]
When editing a draft, we should change that button's label to "Save changes to draft", and it should save changes without closing the editor.

If it's easy to do so, we should also disable the button when there are no edits. However this could get complicated state-wise so we can just avoid doing that if it would introduce a lot of conditional logic or additional state to keep track of.

**Comment by gdjohnson** [comment]
The new thread form has been altered so as to not close on saving a draft. :+1: 

Thoughts on keeping all the copy uniform with generic "Save draft" copy? "Save as draft"/"Save changes to draft" as a pairing seem to stretch button width to the borderlands of eyesore territory, and the extra specificity almost seems unnecessary given "save draft" (without the "as") covers both cases. Just my $.02 tho, will change if you feel otherwise!

Re: disabling the save button—

Right now, we use a function called checkForModifications that uses the loDash deep-equality checker to compare deltas (or else, if in Markdown mode, performs a simple string equality check on getText). That function raises & returns the result of a confirmation modal, passed a string (e.g. "Overwrite changes?") given to the function as an argument in case the draft has, in fact, been modified.

I can split that function into two separate functions, one to check equality, one to trigger the confirmation modal, and then continuously run the former & assign it to a state property (e.g. isModified) which could selectively disable the button. I can definitely implement, none of this would be too much work, but don't have a good gut on whether adding that kind of background code makes sense as a tradeoff. Let me know your preference!

**Comment by gdjohnson** [comment]
Bumping—

**Comment by raykyri** [comment]
For first part:

- "Save draft" and "Update saved draft"?
- "Save draft" if no draft is loaded
- "Update saved draft" is a draft is loaded

For second part:
- Don't use checkModifications, just have a flag that the draft was edited, that can get set to true once

**Comment by raykyri** [comment]
Bumping this - I think we should still make the suggested changes.
