### ISSUE TITLE
Heroku Failing Builds

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5127]
## Describe the bug

A corrupt Heroku build cache caused builds to seemingly randomly fail with the following errors during the `[4/4] Building fresh packages...` build step:
```
error An unexpected error occurred: "/tmp/build_28ab7f24/node_modules/sharp: Cannot read properties of undefined (reading 'getOption')".
info If you think this is a bug, please open a bug report with the information provided in "/app/.config/yarn/global/yarn-error.log".
```
or
```
error An unexpected error occurred: "/tmp/build_e7ba9085/node_modules/esbuild: Cannot read properties of undefined (reading 'getOption')".
info If you think this is a bug, please open a bug report with the information provided in "/app/.config/yarn/global/yarn-error.log".
```
These are logged alongside the usual `node-gyp` errors that are logged even during successful builds:
```
warning Error running install script for optional dependency: "/tmp/build_9eb5faac/node_modules/unix-dgram: Failed to auto-install node-gyp. Please run \"yarn global add node-gyp\" manually. Error: \"Couldn't find any versions for \\\"node-gyp\\\" that matches \\\"latest\\\" in our cache (possible versions are \\\"\\\"). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.\""
info This module is OPTIONAL, you can safely ignore this error
```

## To Reproduce

Trigger multiple builds with the corrupt build cache.

## Expected behavior

No failing builds due to node-dependency/node-module issues.

## Additional context

Potentially relevant: https://stackoverflow.com/questions/66972499/heroku-node-js-build-failing-node-gyp-throws-error-during-npm-install

**Comment by timolegros** [comment]
## Solution
Clearing the Heroku build-cache fixed the build errors.
Documentation on how to clear the cache is available [here][1].

[1]: https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache

**Comment by jnaviask** [comment]
Reopening -- could be node-related, as builds started failing with node 18.18 (vs 18.17 succeeding) + remains failing on production.

**Comment by jnaviask** [comment]
Looks like the failing package is `sharp`, only used in a deprecated compressImages script, so I will try removing that before messing with node versions.

**Comment by jnaviask** [comment]
Reopening because removing `sharp` did not fix the error. Will attempt to downgrade node again once I can reproduce the issue on frack.

**Comment by jnaviask** [comment]
@kurtisassad What I would like to see:
- RCA (root cause analysis) and method to _reliably_ reproduce failing build (DO THIS FIRST), ideally locally.
- List of possible solutions based on RCA.
- Implementation of chosen solution.

**Comment by jnaviask** [comment]
Per @timolegros:
> Seems like build/dep install bug is making it's way into CI https://github.com/hicommonwealth/commonwealth/actions/runs/6312540945/job/17138800053

cc @kurtisassad

**Comment by kurtisassad** [comment]
I will do the RCA. But looks like a tentative solution is to use the `--ignore-scripts` for the CI. This will skip node-gyp from building, and consequently does not fail.

This might not be a solution for node because it could have unintended consequences for other packages with install scripts.

**Comment by kurtisassad** [comment]
# RCA:
## Generate error
1. Delete node_modules
2. Delete yarn cache (For me it is /Users/[user]/Library/Cache/Yarn
3. Run `yarn install --verbose`

After running you will notice it returns exit code 1 when trying to build webpack-dev-server:
```
warning Error running install script for optional dependency: "/Users/kurtis/commonwealth/node_modules/webpack-dev-server/node_modules/fsevents: Command failed.                                             
Exit code: 1
```

This also aligns with this ticket creation date and git blame, since this dependency was added Sept, 5.

## Without webpack-dev-server
1. `yarn remove webpack-dev-server`
2. Delete node_modules
3. Delete yarn cache (For me it is /Users/[user]/Library/Cache/Yarn
4. Run `yarn install --verbose`

Notice, yarn install no longer returning exit code 1.

# Possible Solutions
## Solution 1
My suggestion would be to remove the webpack-dev-server. Rewrite packages/commonwealth/package.json "test-client" to use webpack-dev-middleware (should only be a few lines) which will replace the webpack-dev-server usage.

## Solution 2
webpack-dev-server is a popular library, so it shouldn't be the "root cause" of the issue. Another solution would to continue looking into it. I am sure it is acting strangely with another package, which is actually causing this issue to occur. The issue with this solution is that I might not be able to find it.

# Implemention of chosen solution
## Solution 1
If we decide on this one, I can get started on it right away

## Solution 2
If we decide on this one, we should timebox it because yarn is not very transparent, so it is difficult to dig further into the root cause.

**Comment by jnaviask** [comment]
@kurtisassad this looks like a totally different error, as it has nothing to do with gyp build?

**Comment by kurtisassad** [comment]
Sorry, forgot to add the extra line linking it to node-gyp:
```
warning Error running install script for optional dependency: "/Users/kurtis/commonwealth/node_modules/webpack-dev-server/node_modules/fsevents: Command failed.                                             
Exit code: 1
Command: node-gyp rebuild
```

**Comment by jnaviask** [comment]
@kurtisassad Give yourself a 1-2 hour timebox to keep looking into it, and then if you can't figure it out, we'll try to validate the proposed solution.

**Comment by jnaviask** [comment]
cc @kurtisassad to leave update on status here + what our path to proceed is

**Comment by kurtisassad** [comment]
So I think I had the incorrect assumption, as I had tested out the change of removing webpack-dev-server, and it still broke on CI. As a result I am currently looking further into it.

I have obtained a full verbose yarn run with the bug in question here:
https://pipelinesghubeus22.actions.githubusercontent.com/CzeC4omSEqvpnnmwhPZJWWVM5ImBpwYRrnsaiISF0fi12zklRC/_apis/pipelines/1/runs/20235/signedlogcontent/4?urlExpires=2023-10-02T12%3A20%3A18.8555121Z&urlSigningMethod=HMACV1&urlSignature=vxIA8JhiVWxErNr3qoFkXWMEO9KXw1Tfwl2Dj2gOzLI%3D

I still need to work on deciphering it and trying to locate the root cause of the bug.

**Comment by kurtisassad** [comment]
Well I could not perform RCA, so I have been trying various approaches. I have found an approach that seems to not fail on CI/CD, which I will try to implement in our heroku build.

Its a simple change, just globally installing node-gyp before running yarn install.
