### ISSUE TITLE
On Group Creation, compute the members in the group

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5135]
## Description

So that Groups don't appear empty, compute the members of the group upon Group creation. 

To the users, on the create Group page, we will update (in a later ticket) the copy in the callout directly above the "Create" button to explain this to the users. 

## Engineering Requirements

- run the job 🚀 🚀 

## Acceptance Criteria

- Upon Group creation, begin calculating the members that are in the group.

**Comment by jnaviask** [comment]
Working assumption: ticket scope is run group recompute script (like when editing) but on creation.

**Comment by rbennettcw** [comment]
Estimating as a 2. With a small refactor, the existing refresh logic can be reused.

**Comment by rbennettcw** [comment]
With this change, it's worth mentioning that there will be a noticeable impact on DB performance. It was already discussed, but should be mentioned here nonetheless.

## Data

Quite a bit of data will be created from the recompute.

A = num addresses in community
G = num groups in community
A * G = resulting num memberships created

Realistic example scenario:
A = ~11,000 verified addresses (count taken from ethereum community in my local DB)
G = 50 groups
A * G = ~550,000K membership rows created

But at least A * G represents the upper bound for any given community since memberships are upserted.

A few things that can improve performance:
- Only create memberships for recently active users
- Have a background job to delete stale memberships after some time (e.g. 24 hours)

## Pagination

Since the getGroups payload will now routinely return up to thousands of memberships, pagination will need to be implemented.

---

The refresh part is already done– I now need to add pagination. Bumping this to a 3.
