### ISSUE TITLE
DS: Tabs

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5140]
## Description

New Tab component for Tabbed Pages

[DevMode Link](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=2800-12420&mode=dev)

## Engineering Requirements

- Each tab should take a label and optionally a StatusTag. 
- Tabs have 3 states: default, on:hover, selected.

## Acceptance Criteria

- Tabs take required options: label + statusTag?
- Tabs are to design specifications (see: figma)
- Tabs have 3 states: default, on:hover, selected.
  - Styles reflect all 3 states.

## Additional context

Tab Label (Base) - Individual Tab
<img width="426" alt="Screen Shot 2023-09-21 at 1 34 18 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/79c1ad2c-73bd-4d8b-9916-faa09ff79541">

Tab Group 
<img width="606" alt="Screen Shot 2023-09-21 at 1 34 10 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/e40603e0-4c1c-4cc6-87c0-98c9de2640ec">

Status Tags
<img width="313" alt="Screen Shot 2023-09-21 at 1 35 38 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/966e74df-b9ab-45b3-bc0c-56e1ae6aa342">

**Comment by jessmart1213** [comment]
Hi @masvelio 

> What should be the width of the single tab, or, to be more precise, what should be the left/right padding of the the tab (as the width will be adjusted to the content). Asking, because when there is no tag, the padding is 31px, but when the tag is there, the padding is 16px. Should I strictly follow this design?

Do not follow those designs. I think what Meesh was trying to do here was perhaps establish a min-width. I can't decipher really, so I updated the design system so that all tabs (with or without a tag) have a left and right padding of 16px. 

<img width="256" alt="Screen Shot 2023-10-12 at 2 26 27 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/eac241a0-e879-4480-b2e3-628fb0ace5b2">


> Just to make sure, we want to have ability to display only Status Tag (new/trending) from [the design kit](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?node-id=252%3A2907&mode=dev)? We should not care about any other tag from there, right?

The only tag that would be applied on the tab is the Status Tag: New. No need for the Trending tag.

> What should happen with tabs row in smaller screen, when the tabs content does not fit? Currently, we show vertical scroll (see the video below). Should we keep this behaviour in the tabs? There is not much we can do here. The only other solution that comes to my mind is stacking the tabs vertically (see screenshot below).

Let's keep the vertical scroll behavior, but ensure that the tabs fill the whole width of the screens. In the video, there is this unfilled spacing on the right of the tabs that is unnecessary. If there is a way to reduce the size of the vertical scroller bar, that would be nice to do. 

<img width="799" alt="Screen Shot 2023-10-12 at 2 50 35 PM" src="https://github.com/hicommonwealth/commonwealth/assets/133259695/810a6933-aa23-45bd-8439-5b5ae5f57a36">
