### ISSUE TITLE
DS: Dropdown (componentize)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5142]
## Description

Much of the work here has been done: #3821. However, in this implementation, the Dropdown was not turned into a generic (reusable) component. As we move toward using this dropdown in many locations across the site, it is imperative the dropdown becomes a component in our Component Kit.

The Dropdown on https://commonwealth.im/components does not reflect the new designs.

[DevMode Link](https://www.figma.com/file/eIVp33a1oCu0AtcLwSbGjr/%F0%9F%9A%A7-Components-and-Patterns?type=design&node-id=2802-12421&mode=dev)

## Engineering Requirements

- Dropdown Component is made generic and added to the component kit.
- All states are implemented: default, on:hover, active, disabled.
- Both sizes are implemented: default, compact.

**Comment by Miaplacidus** [comment]
@mzparacha 
I believe this work has been completed. These designs are already implemented by the `CWSelectList` component you recently completed (with the exception of attributes for compact and default sizing), correct? They're also present in the typeahead dropdown I worked on.

@zakhap @jessmart1213 See comment above. Also, can we assume that *all* dropdowns (including the typeahead dropdown) will only have default or compact sizing? I ask because the typeahead dropdown is neither of the default or compact sizing in the designs.

I should also note that the components page on the production site is behind our current work.

**Comment by mzparacha** [comment]
> @mzparacha
I believe this work has been completed. These designs are already implemented by the CWSelectList component you recently completed (with the exception of attributes for compact and default sizing), correct? They're also present in the typeahead dropdown I worked on.

Currently, we have 3 components for dropdown doing almost the same things

- CWSelectList
- Select
- CWTypeaheadSelectList

I think we need to generalize all of them into a single generic component.

**Comment by Miaplacidus** [comment]
@mzparacha 
Thanks for your response! I agree - the current components should be consolidated, if possible, into one component that has all of the functionality and styling we expect. I think the asks around sizing are likely outdated. The other two requirements have been met. 

I've created a card here #5500 for unifying the select lists. As a result, this card no longer seems relevant and should probably be closed.

@zakhap If you have any thoughts, please do share.

**Comment by Miaplacidus** [comment]
@zakhap 
Also, do we have a ticket around ripping and replacing select lists?

**Comment by Miaplacidus** [comment]
Yep yep! #5500 conforms to the design system.
