### ISSUE TITLE
Create Sticky Subheader with Join Button on Mobile and Desktop communities

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5173]
## Description

Right now there is no prompt to join communities on mobile because Join is now hidden in the community sidebar.

https://commonxyz.slack.com/files/U04B3KER2V7/F05UL7HQTSM/image.png

**Comment by zakhap** [comment]
While the prompt to join the community is in the expandable sidebar, it is also on the view thread page + create thread page => close to where the user will want to make a post. 

I think we should discuss this issue within the Mobile Readiness work later this quarter rather than jumping on a sticky header solution without design ideation.
<img width="409" alt="Screen Shot 2023-09-29 at 3 30 12 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/02c98df4-6afc-4844-9468-a257ff4f36e9">
<img width="410" alt="Screen Shot 2023-09-29 at 3 30 25 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/4435e3aa-d90a-4737-bf9a-fe18db311d01">
