### ISSUE TITLE
Delete Comments and Threads show up on Dashboard/Feed

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5204]
## Describe the bug

Deleting Comments and Threads does not remove them from the dashboard feed. 
Impact: users who click these feed items get sent to 404 pages (for threads) or to a comment tree without the requested comment present.

## To Reproduce

Create A Thread, Delete it, Go to Dashboard/Global, it's there.

## Expected behavior

When you delete a thread or comment, it no longer gets propogated to users via the dashboard feed!

## Additional context

Context: https://commonxyz.slack.com/archives/C051XFN57FT/p1695865062674769

**Comment by timolegros** [comment]
@masvelio 

>  if the comment is deleted though, the notification in feed stays around => this is not expected, because the notification for deleted comment should not be visible (now, when you click it, it takes you to the thread with 0 comments) 

This is because we don't delete notifications for deleted objects and the activity query does not join with the `Comments` table to discover which comments have been deleted. 2 possible solutions:
1. Delete notifications when the underlying object is deleted.
2. Join/check Comments table to ensure deleted comment notifications are not included

> 2. We use cache for global activity tab and we do not update the cache on creating/deleting threads or comments. Not sure what would be the solution here. My ideas:
    1. either modify the cache on create/delete action
    2. or maybe change the cache time from 5 minutes to something lower
    3. any other idea?

Modifying the cache is likely the correct long-term solution as we drive toward event-driven design + architecture but given the other active projects (gating, weekly-contests, chain->community) it seems like a proper/well-designed event pipeline with cache modification is still a ways away. Having said that, we could probably introduce simple 'cache-refresh/invalidation' functionality that we can trigger from thread or comment delete controller methods. This, I think, would be the simplest/easiest solution given the lack of a proper event pipeline. It may also be the case that the global cache can be removed entirely as it was created a while ago when activity query performance was much worse than it is now so removal should also be considered.

**Comment by jnaviask** [comment]
@timolegros I agree with your analysis -- I think it should be straightforward to introduce an ("event-driven") cache invalidation hook when deletions occur on recent threads and comments.
