### ISSUE TITLE
Update chain community semantics for pages directory - Child of #5290

### ISSUE THREAD

**Issue by lzach83** [hicommonwealth/commonwealth#5327]
Child of #5335 

## Description

Update the `/pages `to replace `Chain` references with `Community` references.

## Project Owner

@lzach83 

## Engineering Requirements

- [ ] Rename the `chain` to `community_id`

**Comment by timolegros** [comment]
@lzach83 we should track the progress of work on #5290, not #3779. Additionally, just referencing #5290 is not sufficient in this case since you are working on a subdirectory that is not explicitly listed in #5290. Instead, we should create a bucket ticket for `/client` semantic work and then link that ticket to #5290. This new bucket ticket should list the client subdirectories and reference issues such as this one for the work to be done in each subdirectory.

https://github.com/hicommonwealth/commonwealth/issues/3779#issuecomment-1766622292 is an example of the type of tracking I mean for your `/client` bucket ticket (but for `/client` subdirectories instead of database columns).
