### ISSUE TITLE
[Spike] Investigate security implications of lengthening Magic and Server Sessions

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5368]
## Description

A common concern / complaint from users is that they get signed out after periods of non use. Our current session length is 7 days, which seems to be the cause of the problem. A naive solution would be to lengthen the session length so that users don't get signed out.

## Acceptance Criteria
1. Report / research on the length of sessions across other social apps (including refresh tokens and more)
2. Clear Security concerns / questions if there are any
3. Client side session key implications
4. Ideally 2 - 3 solutions and effort involved to do this

**Comment by CowMuon** [comment]
My first thought here is that this should be a labs level spike, if we are missing this information across all of labs. Having said that, I don't think a spike is warranted here. 

First a bit of clarification, so that everyone is on the same page. As Zak has said "Common sessions never expire" it may be confusing to see users complaining about the being signed out after 7 days. TBC, that is for 7 days of inactivity. If you are active within that period, you should not be signed out. The referenced complaints are presumably coming from users who go over a week without any activity. 

Not having touched our refresh token implementation, I can't speak to details off the cuff. However, I'm ok with increasing the session length so that inactive users are not logged out in 7 days, but we can set that at 30, which is fine. 

IDK that we are going to find anything in such answers that would supersede best practices, which in web2 can be quite generous if you don’t FIU.

@raykyri  can you please weigh in here WRT any client side session keys implications?

Finally, a bit of editorializing on my part- you might think that web3 would require a stricter approach to authentication in this regard (sessions) bc you know, hacking tokens, but it’s really the opposite; critical parts of authentication have been pushed down the stack and are handled by PKI, which is, you know, pretty secure. Not to be all hand wavy about it, but if there are no surprising side-effects involving session key (Raymond, FF2 re-open if so)  increasing the inactivity timeout from 7 to 30 days is the answer here. 

Not that our sign-in flow model is particularly well thought through, I mean, we've put a *lot* of thought into it, which is not necessarily the same thing.
