### ISSUE TITLE
Implement "Related Communities" query

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5369]
## Description

#4679 is the master ticket for a "related communities" screen. This screen will require a query to fetch related chains depending on the community admin-selected "[base] chain".

## Engineering Requirements

- Given a base chain (equivalent to a chain node), return a paginated list of communities including member counts + thread counts.
- Accept a search parameter which filters the list based on community name (perhaps later: description too?).

## Acceptance Criteria

Should provide @masvelio = assignee of #4679 the data required to populate the table and cards on the related community page.

## Additional context

Frontend will need to provide the community's selected base chain to the query, which means we may need additional database changes (i.e. storing base chain selection on communities) to properly complete #4679.

**Comment by kurtisassad** [comment]
Point explination:
I think that we will not need any database changes since chains already relates to chain nodes via the id which we can join on chain_node for the name. So the flow would look like:

given name -> select ... from chainNodes where name = [name] join chains, threads, addresses

All that is left to implement is:
route: 1 point
tests: 1 point
wiggle room for changes/ discussing with front end: 1 point

**Comment by kurtisassad** [comment]
Will probably bump up the points. There is a large issue here. Based off the query it could take up to 40 seconds to run (finding the 5 largest communities by thread count).

I will need to think of a way we can optimize this. This will probably take more time than 1 point and might require some database changes

**Comment by jnaviask** [comment]
@kurtisassad We may need to implement a system akin to reaction/comment count per #4200 but for threads/members, so that we can have counts triggered by afterCreate/afterDestroy and saved on the root community object.

**Comment by kurtisassad** [comment]
Sorry for the false alarm. I was performing the query in a stupid way, which I was basically joining like:

chainNodes
<- Chains
  <- Threads
  <- Addresses
  
 But this was very inefficient according to the explain analyze command. Instead going with

(chainNodes
<- Chains
  <- Threads) sub query
<- Addresses

Sped this up a huge amount (sub-ms query locally for largest base), as we no longer need to check for distinct keys.

Anyways we can probably discuss this more in detail in the PR, because maybe there is an even more efficient way to perform this query
