### ISSUE TITLE
Default Group Names for Threshold Migrated Groups

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5396]
## Description

Problem: How will group names be generated for Groups that were auto-created from Token Thresholded Topics?

## Project Owner

PM: @zakhap 

## Acceptance Criteria

**Product Requirement:** 
- For each Group created on behalf of existing Token Thresholds, the group name should be:
  - Default Name: `[token] Holders`
    - e.g.  STB Holders, DYDX Holders, ALEX Holders

**Comment by lzach83** [comment]
Handing off to @rbennettcw -- it is API related

**Comment by rbennettcw** [comment]
This is not applicable until the next gating DB migration is applied– which will create groups from topic thresholds:

https://gist.github.com/rbennettcw/929c839d88fcd9a69b6c6205a2957c69

That migration will be run at a later time once the gating API is launched on production– otherwise we'd need to account for generated groups going out of sync with their source token thresholds.

**Comment by jnaviask** [comment]
We want to run this migration without deleting token_threshold tables to start with -- we can drop the old tables later once we've confirmed the success of the feature.
