### ISSUE TITLE
Filter out Unactivated Communities out from /communities Page

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5470]
## Description

We would like to filter out unactivated communities on the /communities page, but we want to keep the "total communities" vanity number. 

Defn "Unactivated Community": A community that has no additional Topics and fewer than 10 members. 

## Project Owner

@zakhap 

## Engineering Requirements

- Zak Suggestion: This should be a backend change only

## Acceptance Criteria

- As a user, I do not want to see communities that are unactivated on the explore communities (`/communities`) page.

**Comment by mzparacha** [comment]
> Engineering Requirements
Zak Suggestion: This should be a backend change only

Tagging @rbennettcw as this looks like a backend thing.

**Comment by CowMuon** [comment]
When we implement this, let's not bury the magic number, but rather surface in an obvious way we are setting an arbitrary value of 10 members. 

Would be good to get a sense of where else in code we are using magic numbers.

**Comment by rbennettcw** [comment]
Since the new query requires checking *all* communities and joining across topics and addresses, it's a very slow query. Adding indexes doesn't help. It's similar to the global stats queries that we use to generate CSVs.

Bumping up to a 3. Need to find a solution to cache/persist and refresh. The list of communities doesn't change often.
