### ISSUE TITLE
[Spike] Custom Community Theming around Color, Image, Text and Background Image

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#5471]
## Description

Sites like Reddit and [Zora](https://zora.co/angeldarmella.eth) have community / profile themes. It makes it way more fun. In the past we have mocked things up and discussed this in [the past](https://www.figma.com/file/6Wz8YmJq5fm6uPETnOhQUX/Customization-Spectrum?type=whiteboard&node-id=0%3A1&t=xoYjQTtk0HTkKvdX-1) and [here](https://www.figma.com/file/d9J9foZcdWMKQUmrOGqkR6/Aden's-stuff?type=design&node-id=13-6803&mode=design&t=cMCRlfwxTEilEyyE-4). We don't know what's "easy" or "hard" therefore making design product decisions here are hard. 

We want to see what's easy to edit and configure on the community-specific.

## Project Owner
PM: @dillchen 

## Engineering Requirements
Timebox - 3 hours (but idk)

## Acceptance Criteria

Are there any "gotchyas" for the product (desired) requirements below? 

Level of Effort (T-Shirt Size) for the Following with one bullet point for the solution to apply styles across a community. Questions: Is this similar to Dark Mode #2717, as a hack, where we had a one boolean and a few other patches to apply.

- Background Color (viewable on all page backgrounds, within a community, I.e listing page)
- Background Sidebar Color (viewable on community sidebar and navigation menu within a community, I.e listing page)
- Background Background Image (similar to [profile page](https://commonwealth.im/profile/id/8098))
- Adding Background Header Image (similar to notion) -> would be viewable across the header across all pages
- Updating all Text Font (Title, H1, H2, H3, Body) - no size changes

<img width="1512" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/5334557/caf0c637-6b85-42b9-bdb5-57b1ca8e9612">

- Nice to Have: any spec thoughts (but probably out of scope)
- Nice to Have: POC / via inspector where we just edit the styles or SCSS and see if anything breaks
- Nice to Have (likely out of scope): Prototype Branch where we have style overrides

## Additional context

We also have styles on the profile, that are saved as a [background image field in the UI](packages/commonwealth/server/models/profile.ts)

cc: @lzach83 , @Miaplacidus , @mzparacha , @masvelio for any first pass thoughts

**Comment by masvelio** [comment]
# Spike Summary 

The goal of this spike was to check the feasibility of introducing custom theming around, including background colors, background images and fonts. The work has been pushed to the branch `marcin.5471-customization-spike`, so everybody can play around on their local machine. Before I go into details, there are a few caveats that have to be highlighted first. 

## Caveats
- Because of the time constraint, the quality of the code is very low on `marcin.5471-customization-spike` branch, and it should not be considered as a production ready solution.
- Presented solution does not include per-community customization. Customization panel is in `/components` page which is not scoped. I would say that currently it works as per-user customization.  
- For final solution, customisation panel should be available only for community admin (eg in `/manage` page).
- LocalStorage is used as a tool for providing persistency. In final solution it should be a database + zustand.   
- Sizing:
  - S => 1 day
  - M => 3 days
  - L => 5 days
  - XL => 10 days

## Overview
The video below shows possibility of changing background color, sidebar color, background image and default font. Also it shows possibility to reset all of these settings to default.

https://github.com/hicommonwealth/commonwealth/assets/14819225/f04b8fcd-5965-4b58-a933-a75853422efd

## Areas of customization
There were 5 sections that have been check during this spike. I will describe briefly each of them.

### Background Color
**Technical concerns**
- Not discovered

**Product/Design concerns**
- Components in the app divides into two groups: those which have background color, and those which do not have background color. For example on the image below, search input is white, but the list of users is transparent. This would require going through the whole app and check/decide how background colors for component should look like to work fine for both default background color and custom background color.

<img width="477" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/db0aef0b-a023-4746-9c2b-31cb82a28ced">

**Implementation details**
- Fairly straightforward problem. Most important thing here is CSS variable that holds custom hex color selected by the user. If the value is not set, background color has default value. 
- We are in a good position here, because every single page in the app is rendered with `Sublayout` component that wraps the children with div containing `Body` classname. Thus, we can simply apply custom background color to `Body` class.
- size: `M` - from technical POV it is simple thing, but considering Product/Design concerns, makes this more complicated

---
### Sidebar Color
**Technical concerns**
- Not discovered

**Product/Design concerns**
- Not discovered

**Implementation details**
- It works very similarly to setting custom background color in previous section. Instead of targeting `Body` though, we target few sidebar classes that are responsible for displaying sidebar switcher, content creation menu, explore communities menu etc.
- size: `S`

---
### Background Image
**Technical concerns**
- Not discovered

**Product/Design concerns**
- Similarly as in background color section above, concern is about the background color of individual components. If they are transparent, custom background image will distract from reading posts etc - generally it may decrease the accessibility of the site. On the other hand, this is admin's decision what kind of image will be set, so he/she should not set image that would make community users upset.
- Similarly to profile background image, we should consider giving ability to set `fill` or `tile` property.

**Implementation details**
- For the sake of this spike I only created toggle that turns background image on and off. In final solution we should have image picker component and then we would store selected image and image URL in the DB. We can use here either CSS variable or JS inline style to set background image for `Body` class (same as background color above).
- Size: `M` - apart from setting background image, we have to upload the image. Also we have to make sure that components colors are not transparent. 

---
### Header Background Image
**Technical concerns**
- In the case of background color and background image, the case was simple because, as I mentioned earlier, each page has a `Body` class and we are able to modify/customize this class setting custom color or image as a background. In this case though, we do not have generic pattern for creating the content of the page. To be more precise, we do not have generic header component that we can use for setting the background image. The solution would be to create generic `PageHeader` component that would display page title (optionally subtitle, maybe beadcrumbs in the future).  This will allow us to set proper height and image for the header, similarly as in Notion. 

**Product/Design concerns**
- We should identify which page should have header with possibility of setting background image.

**Implementation details**
- Not implemented in the PoC branch
- Size: `L` or more if header should be on every page. We should create header component and add it to each page. Also we have to have a possibility to upload/delete/crop image.

---
### Custom Font 
**Technical concerns**
- Complexity of solution would depends of the number and type of fonts we want to provide for the users. If we want to have only couple of system fonts, there will be no problems. If we want to give ability to pick one from dozens of weird fonts it might get bit more complicated (we either need to have font files in the project vs use remote fonts like google-fonts approach).
- To make this work 100%, we should modify the code to always rely on CSS variable if it comes to the font-family. Currently, we have a lot of places in the code where we define `font-family` inline for particular components without using variable. 

**Product/Design concerns**
- We use different fonts for different components. Not 100% true but to illustrate the problem: we use `Silka` for headers,  `Neue Haas Unica` for bodies, `DM Mono` for code or markdown. In the PoC, if I change a font to custom, all of the components use custom font so they do not respect distinction between headers, body etc. I can't see other solution than this currently, because we are not super consistent in terms of what font where we should use.

**Implementation details**
- Again, main thing here is CSS variable that holds current font family name. Technically it is not complicated, but Product/Design concerns can make things easier/harder.
- Size: `M` / `L` depending on the scope (number, type of fonts, distinction of fonts between components)

## ⚠️ Extra disclaimer - Dark mode
Current implementation of dark mode is a CSS hack that inverts the colors. This works "fine" if we have light backgrounds and dark fonts. Things start to complicate if we decide to introduce custom theming as all colors of backgrounds and images will be inverted as well, which will be definitely terrible experience, especially for those, who like their apps to be in dark-mode. See the video below.

https://github.com/hicommonwealth/commonwealth/assets/14819225/a554003a-09de-4480-9e66-16b4847c6f10

In my opinion, if we introduce custom theming, we should either disable custom dark-mode toggle or implement proper dark mode, which might be difficult in our current state of CSS. But this would require additional spike as it was not scope of this task.

## Summary
Most of the things are definitely doable from technical point of view. Product/Design have to think through different scenarios and consider concerns raised in individual sections. Further ideas should be consulted with frontend engineer to make sure that features are feasible.

**Comment by dillchen** [comment]
@masvelio just re iterate based on your spike, and I see that you did make a comment here

> For final solution, customisation panel should be available only for community admin (eg in /manage page).

It seems based on this there is not a heavy lift for this, as we should be able to trigger scoped zuzstand + db changes of the CSS. This would be an S?

----
Overall I think this is highly encouraging. And makes sense that Header Image is a large, given it's technically a redesign / unimplemented component.

Re darkmode comment. I would turn it off if custom theming is avail. then add true dark mode. Perhaps another spike for true dark mode. But definitely to wait to Q1

**Comment by masvelio** [comment]
> > For final solution, customisation panel should be available only for community admin (eg in /manage page).

> It seems based on this there is not a heavy lift for this, as we should be able to trigger scoped zuzstand + db changes of the CSS. 

I think we should extend `ChainInfo` model to add data related to customization like image, bg color, sidebar color etc. Then we will have possibility to display per-community-customization.  

> This would be an S?

Hard to say what "This" exactly means. We need to scope tickets. Indeed, extending `ChainInfo` model is not a big deal but it is just a one piece of the puzzle.In overall, shouldn't be a big lift.
