### ISSUE TITLE
Add divastaking on chain governance contracts

### ISSUE THREAD

**Issue by markiscommon** [hicommonwealth/commonwealth#5487]
Divastaking exists as community with id "divastaking". Divastaking has their governance contract already linked, but specified as an erc20 rather than as an OZ governor contract (network is also set to erc20). We want to get their onchain governance integrated onto their commonwealth page: https://www.tally.xyz/gov/diva

What we need to do:
1. ensure OZ gov ABI exists in table
2. update contracts table for divastaking to have correct type ("compound"?) and reference correct ABI
3. update communities table for divastaking to have correct network ("compound"?)
4. ensure proposal fetching works as expected (+ any additional steps necessary)

**Comment by CowMuon** [comment]
@jnaviask What's the procedure for adding this?

**Comment by jnaviask** [comment]
cc @timolegros added description to ticket body, let me know if you need any additional info.

**Comment by timolegros** [comment]
Neither the front end nor the backend supports raw OZ (only bravo-oz). On the client, `CompoundProposalStats` (and other stat fetching class methods) is not compatible with OZ. On the backend, OZ is not supported because the OZ contract does not have a `proposals(proposalId)` method which returns the votes for and against. From what I can tell the only way to get the OZ votes tally is to fetch all VoteCast events which we don't currently do.

Adding support for OZ governance proposals is probably a 3-5 pointer.

**Comment by timolegros** [comment]
@jnaviask Let me know if this is something I need to work on in the future (backlog) otherwise we should close the ticket or at the very least remove it from my teed-up tickets.

**Comment by jnaviask** [comment]
@timolegros We will plan / scope the work in a separate ticket (which I will create shortly), but we will not be moving forward with the work until after Istanbul. Thanks for doing the research!

**Comment by CowMuon** [comment]
Fiollow up ticket is #5594 8
