### ISSUE TITLE
Spike: Investigate feasibility of event-driven stake updates

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5552]
## Description

One of the essential components of the "community staking" project is an event-driven approach to updating member stakes in a real-time, event-driven fashion as a user makes trades.

To dig into more detail:
- We should assume that a singleton [community staking contract](https://github.com/commonxyz/common/blob/main/src/WeeklyContests/CommunityStakes.sol) which emits `Trade` events when a user buys or sells stake.
- We should assume that `Trade` events contain sufficient information to identify the trader, the amount of stake bought/sold, and the community associated with the trade.
- The `Trade` event should result in triggering a command against the related `Address` object, given the above values, whose functionality is async and not within scope of this investigative spike.
- We should assume that other, similar sorts of event-based policies against a known contract that isn't directly associated to a community via the `Contracts` table will be implemented in the future, and should take into consideration the specification and storage of this data.

The scope of this spike is to write up a brief proposal of changes required to implement the Update Stakes policy (i.e. the procedure which accepts the onchain event and triggers the command) according to the above set of assumptions, ideally using our existing architecture. This will ultimately become the basis for an implementation ticket as we move forward with Community Staking.

A diagram of the event flow involved in this spike:
![2023-11-02-104316_1716x339_scrot](https://github.com/hicommonwealth/commonwealth/assets/1860629/a6d05b6f-ca93-47a0-b6f2-4a09fa2be639)

## Project Owner

@jnaviask 

## Additional context

Timebox: 2 hours.

**Comment by timolegros** [comment]
To be clear, community stakes will only be deployed on a single EVM chain correct?

**Comment by jnaviask** [comment]
> To be clear, community stakes will only be deployed on a single EVM chain correct?

We should assume that the production instance will be deployed on a single chain as MVP, but we should take into consideration what additional changes would be required for listening to instances across multiple EVM chains.

**Comment by Rotorsoft** [comment]
From previous conversations with @timolegros , we use a polling strategy to integrate new blocks from chains given the predictable and low frequency nature of blockchains. I'm assuming the "Update Stakes" policy will follow the same approach, and wondering if there is a generic functionality (existing or to be extracted) that we can reuse here and in future chain integration policies.

**Comment by jnaviask** [comment]
@Rotorsoft that's within scope for discussion as part of the spike! Definitely worth investigating.

**Comment by timolegros** [comment]
So as @Rotorsoft alluded this fits neatly into EVM CE 2.0.

## Assumptions
For these changes, I assume 2 things:
- There is a non-event driven approach to determining a user's stake/weight which is used when a user is new or in the event that EVM 2.0 goes down for an extended period of time.
- When a community staking contract is created and registered in the Commonwealth database, the EvmEventSources table is updated to include the event source of the new trade events we need to capture on-chain.

## Proposed Changes:
EVM CE 2.0 is currently somewhat centered around notifications which means that the event sources we fetch and the way that we process an event once captured need to be modified in order to generalize fully over any event source. So we need to do the following:
- Modify the `getEventSources()` function so that it returns event sources for the community staking contracts on top of the regular contracts that users have subscribed to.
- Create a new string enum called `ChainEventTriggers` that contains string triggers representing a side-effect that an event has. For example, creating a notification, updating stakes, updating TBC, etc.
- Create a new function called `determineEventTriggers()` which given an event, returns an array of enum values indicating the commands that the event triggers.
  - For instance, given an event, the `deteremineEventTriggers()` function would query the database to find if the contract address refers to a community stake contract or a DAO that we support notifications for. If the contract address refers to a compound contract the function would return `[ChainEventTriggers.Notification]`. If instead, it referred to a community stake contract it would return `[ChainEventTriggers.CommunityStakeTrade]`. This is an array because we may want to return multiple ChainEventTriggers in the future (e.g. emit a notification AND update stakes).
-  Modify `processChainNode` function to process events according to the values returned by `determineEventTriggers`.

## Considerations
- We currently poll relevant chains every 120 seconds. This may be more delay than we desire for updating a user's stake. If that is the case we can lower the polling period. There are a limited number of chains we listen to (currently on production only polling 2) so we can easily lower polling time to 30 or even 15 seconds.

**Comment by jnaviask** [comment]
@timolegros looks pretty straightforward to me. Any performance considerations or concerns regarding event volume in particular?

**Comment by timolegros** [comment]
> @timolegros looks pretty straightforward to me. Any performance considerations or concerns regarding event volume in particular?

Not particularly. There is a slight increase in database load because each poll will result in a query (to figure out what to do with events if there are any) but this is fairly insignificant.

Additionally, the worst case scenario is an entire block is filled only with stake events/txns (couple MB worth of data - basically impossible) which should fit easily into memory. If we do see the server struggling we have tons of room to scale on Heroku. Of course, here I am assuming that the stake update operation in our DB is either very cheap or offloaded off of CE 2.0 dyno.

I think the bigger concern is the number of contract addresses we fetch events for. I'm not sure if there is a limit to the number of addresses we can filter for so if that becomes a huge number like 100k+ we probably need to start fetching all events and parsing them on our server rather than sending all contract addresses to the chain node and having them filter. Still a long way away from that though.

**Comment by Rotorsoft** [comment]
The changes @timolegros  is proposing above sound like good candidates for an event storming session. I can hear a few policies in that description.

**Comment by jnaviask** [comment]
@Rotorsoft would love to do that alongside the results and owners of #5553 and #5555 so we can put together a more detailed / better defined SDD than the current one!

**Comment by timolegros** [comment]
From my discussions with @ianrowan it seems like we may not need to listen for trades. The only reason this would be beneficial is to update memberships as part of gating in which case the ticket should be about event-driven token gating rather than just event-driven stake updates.

From my understanding, we can query stake both as part of `/status` (or equivalent) and when a user upvotes. This means event-driven stakes would only be beneficial for updating the UI if a user trades a stake without using the Commonwealth UI but while they _are on_ the Commonwealth UI. Seems like a highly unlikely scenario where a stale stake value shown on the client would be acceptable (simple refresh and it updates).

**Comment by timolegros** [comment]
Confirmed that this spike and the work discussed therein is no longer needed since we do not need to update historical vote weights in real-time and we do not need to store a history of stake txns (fetched at runtime).
