### ISSUE TITLE
Bug: Thread Viewcounts are wrong (High Severity)

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5591]
## Describe the bug

Regarding this thread: https://commonwealth.im/evmos/discussion/6668-ideation-launching-radioshack-dex-with-liquidity-on-evmos

On August 22, we took this screenshot for a community call. The thread had 15k views. Now it has ~300. 

![Slide 16_9 - 17](https://github.com/hicommonwealth/commonwealth/assets/16248081/75030982-36aa-4658-9379-d591510ef715)

Growth was trying to do analysis on our top posts and discovered this bug. We can't do analysis on top posts if we don't have accurate view counts.

## To Reproduce

- Go to link to see thread.

## Expected behavior

- Thread View Counts need to be accurate.

## Additional context

Here are other threads that went viral that should have WAY more views than they currently do: 
https://commonwealth.im/osmosis/discussion/1547-how-can-we-improve-the-osmosis-frontend-feedback-thread
https://commonwealth.im/osmosis/discussion/7424-osmosis-grants-program-ogp-renewal

**Comment by timolegros** [comment]
To note for whoever works further on this, the view counts displayed on those pages are the view counts that are currently stored in the database. That means one of two things:

1. We were previously calculating or displaying the view count incorrectly on the client (and now it's fixed) OR
2. The view count is corrupted in the database when set/updated.

**Comment by RhysCommonwealth** [comment]
another example here: [https://commonwealth.im/terra/discussion/5332-proposed-distribution-method-for-05-emergency-luna-allocation-version-3](https://commonwealth.im/terra/discussion/5332-proposed-distribution-method-for-05-emergency-luna-allocation-version-3) on July 27 2022 this was showing as 26k views its now showing as 430

**Comment by kurtisassad** [comment]
A little bit difficult to debug.

Going along with Tim's suggestions:
1. Did not happen, as I had reverted the code to a commit prior to July 27, and the view count is still being shown correctly (same number as in the database).

This means that 2 is the culprit. The issue is we will not be able to fix it unless we have some database backup from prior to this happening. Currently we only have continuous backups for the last 4 days, and our last manual backup is from 2 years ago.

Engineering Note:
As for the root cause of the "why", It seems there are 2 places that can update view_count:
1. Migration script root-id-refactor. This seems unlikely as it was ran April of this year, so it could not have been the reason because the dates don't line up.
2. viewCount.ts. In here we update the viewcount by adding 1 to the previous count on a new view. It could be the root reason, but seems unlikely due to it being a simple operation. It doesn't seem to me that it could update the view_count to a smaller number than it was previously.

Conclusion:
- Hopefully we have some more recent snapshot which we could write a manual script for in order to roll back view_counts.
- Root cause seems not to be in the source code, at least not what is currently on master. So it was either manually changed, or some previous commit contained bad code.

**Comment by kurtisassad** [comment]
Ok seems that the view_count migration script was actually the issue. Maybe it was in combination with the UI bug, but basically the view_counts were not migrated over correctly.

My recovery plan going forward:
- Run the most recent db dump prior to the view_count migration script on a second DB.
- In a migration script, update the view_count field to be (`current db view_count = old db view_count (in second db) + current db view_count`)

It should be pretty straight forward, but will require us to run a second db with the old dump while we run this recovery migration script. We will also have to manually migrate it to only use the migration scripts up to but not including the view-count-migration script.

**Comment by CowMuon** [comment]
tagging @lzach83 for review

**Comment by CowMuon** [comment]
Can we get this into `v0.9.6` pls? @jnaviask @kurtisassad @timolegros
