### ISSUE TITLE
Modal Select

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#5646]
## Description
The modal select component is used in the Create Community flow. It gives the user the ability to connect a wallet or sign in using a method that is compatible with the ecosystem they selected. The options shown in this modal is limited by the selection that the user made in the select community type screen. The options available for each selection is shown in this [figjam](https://www.figma.com/file/LzDHu1mIJIpB26c9IqyN4S/Create-Community-Process?type=whiteboard&node-id=0%3A1&t=GonP7fK4Mc90phek-1)

<img width="1048" alt="Screenshot 2023-11-28 at 9 50 06 AM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/6fbe6735-c014-42e8-9c4d-d69ef8bc108c">

[Figma dev link](https://www.figma.com/file/WLN4nRpVGQJ9AjuxiJwuDS/Create-Community?node-id=508%3A14363&mode=dev)

## Behaviors
- The modal has a default state and a hover state 
- default state 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/dea0abe7-2ab2-45ee-a977-03953e30b3e2)

- Hover state

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/c1ac95a0-f37f-483c-8f46-b963779a0bcb)

- Once the user makes either of the selections, they are taken to the next step where the user is shown the options that are compatible with the ecosystem they have selected. In this step we will be re-using components from the sign-in flow that we currently have 
- Modal when user is already signed in 
<img width="463" alt="Screenshot 2023-11-09 at 3 06 45 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/bfc62aae-b50e-445e-9cd3-c8f77ed88c9c">

- Modal when user is not signed in
<img width="323" alt="Screenshot 2023-11-09 at 3 54 10 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/00449986-0f76-46fc-8e64-470093f7df65">

- The modal that the user is shown depends on the selection that they make about the ecosystem they are using. For more information about this, check https://github.com/hicommonwealth/commonwealth/issues/5633

**Comment by masvelio** [comment]
@sachben91 
Questions:
1. >The options shown in this modal is limited by the selection that the user made in the select community type screen. 

Can we specify what exactly are those limitations and what/when they are applied to? So eg what is the difference when user picks Ethereum vs Cosmos vs Polygon vs Solana?

2. If user is logged in and has only 1 address, do we still show `address selector modal`?
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/3372941c-bdfc-4d53-b6e3-e531b1b5851b)

3. Sometimes I think like wallet and address are used interchangeably. Eg  in `Which wallet would you like to serve as the admin of the new community?` or `Connect New Wallet` I feel like this should be `address` instead of `wallet`. But that's just my opinion.

4. I think we talked some time ago with @jessmart1213 and agreed that buttons in modals should always be aligned to the right.

5. I see potential issues in the flow, when the user is not logged in and has to do the sign in process via wallet or magic. For example, authentication with magic requires the app to be reloaded. Thus, I am not sure if that will be super easy to come back to the exact spot where the user left off during the community creation process. I am also not sure, if after signing in, the user should see [address selection modal](https://github.com/hicommonwealth/commonwealth/assets/14819225/d4ae0378-378e-4395-ba45-238c0594c556) or should be redirected to [basic information page]?(https://github.com/hicommonwealth/commonwealth/assets/14819225/cd74765f-dd87-4e58-bb87-2c7242467536)
 
 `address selection modal`
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/d4ae0378-378e-4395-ba45-238c0594c556)

`basic information page`
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/cd74765f-dd87-4e58-bb87-2c7242467536)

**Comment by sachben91** [comment]
> @sachben91 Questions:
> 
> 1. > The options shown in this modal is limited by the selection that the user made in the select community type screen. 
> 
> Can we specify what exactly are those limitations and what/when they are applied to? So eg what is the difference when user picks Ethereum vs Cosmos vs Polygon vs Solana?
- Added the figjam to the ticket that shows what the difference is when user selects Ethereum vs Cosmos vs Solana

> 
> 2. If user is logged in and has only 1 address, do we still show `address selector modal`?
>    ![image](https://private-user-images.githubusercontent.com/14819225/286240787-3372941c-bdfc-4d53-b6e3-e531b1b5851b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODYyODQsIm5iZiI6MTcwMTE4NTk4NCwicGF0aCI6Ii8xNDgxOTIyNS8yODYyNDA3ODctMzM3Mjk0MWMtYmRmYy00ZDUzLWI2ZTMtZTUzMWIxYjU4NTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE1Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2OWViZDkyZWQ0YWRmMmQ3NTI5YTBjZGY1NzZiNGYyNGQzZTc4YmQ1YTZiYmMwODIxYzVkMWVhNWYwMDY5NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4G6m9bfT0Uc5CQaL3FHPCZiihEVpH22Fqt4HYiY09qQ)
- Yes we should show it since we want them to confirm that they are using the right wallet 

> 3. Sometimes I think like wallet and address are used interchangeably. Eg  in `Which wallet would you like to serve as the admin of the new community?` or `Connect New Wallet` I feel like this should be `address` instead of `wallet`. But that's just my opinion.
- We should likely use 'wallet' instead of 'address' everywhere to be consistent, but the above question needs further consideration for future projects, we shall make a note to do so.

> 4. I think we talked some time ago with @jessmart1213 and agreed that buttons in modals should always be aligned to the right.
- Will make this change 
> 5. I see potential issues in the flow, when the user is not logged in and has to do the sign in process via wallet or magic. For example, authentication with magic requires the app to be reloaded. Thus, I am not sure if that will be super easy to come back to the exact spot where the user left off during the community creation process. I am also not sure, if after signing in, the user should see [address selection modal](https://github.com/hicommonwealth/commonwealth/assets/14819225/d4ae0378-378e-4395-ba45-238c0594c556) or should be redirected to [basic information page]?(https://github.com/hicommonwealth/commonwealth/assets/14819225/cd74765f-dd87-4e58-bb87-2c7242467536)
> 
> `address selection modal` ![image](https://private-user-images.githubusercontent.com/14819225/286248493-d4ae0378-378e-4395-ba45-238c0594c556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODYyODQsIm5iZiI6MTcwMTE4NTk4NCwicGF0aCI6Ii8xNDgxOTIyNS8yODYyNDg0OTMtZDRhZTAzNzgtMzc4ZS00Mzk1LWJhNDUtMjM4YzA1OTRjNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE1Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YzYzZjBlMzZhYzk2NmM0MDUxNGVlMDJjYTcyZThhN2YyMTU0NGFkMzU2MGU5MTIzYTBkNjNjZGJjMDRhYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A-h60ez1Q8BmwTMTkURySPzjxeXCXWo_SPM7_ugQFKs)
> 
> `basic information page` ![image](https://private-user-images.githubusercontent.com/14819225/286248785-cd74765f-dd87-4e58-bb87-2c7242467536.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODYyODQsIm5iZiI6MTcwMTE4NTk4NCwicGF0aCI6Ii8xNDgxOTIyNS8yODYyNDg3ODUtY2Q3NDc2NWYtZGQ4Ny00ZTU4LWJiODctMmM3MjQyNDY3NTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDE1Mzk0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmYmY1OGU5M2I0ZTgyZDNmYzczZThjMjdiMjhkY2IzMmUwMjBjNDFjNWZiNTU4NTA3MmQ1NzYyMDY1ZGFmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOCG7MbBdq13B3xeaC7ckUjB8jsDGMrOFZmNJxdx41o)

- yeah this one is tricky. If they have to do the sign in process again and the reload does not take them back to the sign in modal, it should drop them back into the select community type screen. The address selector should be still shown when they select a community. It is not the ideal UX but we should consider this as part of Sign in work which we have slated for January

**Comment by sachben91** [comment]
@masvelio 

![image](https://github.com/hicommonwealth/commonwealth/assets/38763242/d9adace7-1196-4693-9153-dd648741839c)
 Copy for modal when user non signed in users and users who are signed in that want to connect a new wallet
 
 Heading: Sign-in to create your community
 body text: To launch your community choose a sign-in option that is compatible with the ecosystem you selected.
