### ISSUE TITLE
1inch: Wallet Connect Sign in Broken (p1)

### ISSUE THREAD

**Issue by RhysCommonwealth** [hicommonwealth/commonwealth#5845]
## Describe the bug
Unable to sign in to existing accounts via wallet connect or create an account with a wallet connect sign in. (two different errors)

## To Reproduce
1. Click Sign in
2. Press wallet connect option
3. Sign in to existing account or try and make a new one
## Expected behavior
Wallet connect sign in should work.
## Additional context
**When creating a new account with Wallet Connect:**
<img width="1505" alt="Screenshot 2023-12-05 at 10 09 50 AM" src="https://github.com/hicommonwealth/commonwealth/assets/88511608/f852f305-dc95-4c56-b88f-6f185429ba50">
^tried with Zerion & 1inch wallet login

**Error from 1inch when trying to log in to an existing account with Wallet Connect:**
![photo_2023-12-05 10 11 18](https://github.com/hicommonwealth/commonwealth/assets/88511608/67f26d53-1a29-4951-81e0-9c2761e318ec)

**Comment by CowMuon** [comment]
@ilijabojanovic Only visible on 1inch? I was unable to sign in with Trust or Uniswap, in both cases the request is just never returned. Feels like a possible library version issue upstream.

**Comment by ianrowan** [comment]
I think this has been broken since session keys potentially and am a bit confused as to how any communities were using wallet connect to sign in

Here is a snippet of the fix: 
<img width="448" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/36428666/afab4f30-67ad-4b7b-8263-ea38c6308d55">

The ordering of the params for personal sign was incorrect, so the lest robust wallets were throwing errors(more robust wallets apparently can re-order by flipping 20 byte hex strings to the second param even if sent as the first)

Wallet connect docs

https://docs.walletconnect.com/advanced/rpc-reference/ethereum-rpc#parameters

will push a pr with this fix and it should resolve the issue for 1inch wallet, trust wallet(tested both), and all other wallet connect evm wallets

CC @CowMuon @ilijabojanovic @jnaviask
