### ISSUE TITLE
Set Community Namespace

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#5882]
# Description
Links community to namespace

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @jnaviask     | @kurtisassad         |

## Model

https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764572378160162&cot=14

## Engineering Requirements

1. **Authorization**
   - Admin (middleware)
2. **Message Schemas** 
   - Use zod as middleware for express as outlined in #5927
   ```typescript
   // import SupportedNetworks enum ->
   
   z.object({
        namespace: z.string(),
        transactionHash: z.string(),
        network: z.enum(SupportedNetworks)
   })
   ```
4. **Routing**
   - `PATCH /communities/:id`
   - Message in body
5. **Loading Aggregate**
   - `const community = await this.models.Community.findOne({ where: { id: id } });`
6. **Business Rules**
   
   | Condition | Error |
   | --------- | ---- |
   | 2. valid owner using EnsProvider#lookupAddress | InvalidInput("Invalid owner") |
   | 3. namespace not being used by another community | InvalidInput("Namespace in use") |
   | 4. valid ERC1155 check passes | InvalidInput("Insufficient ERC1155 balance for namespace") |
 
7. **Mutations**
   Update namespace, other fields are only used in validation logic
   - `community.namespace = body.namespace`
8. **Persistence**
   - No migration needed, because namespace migration already merged into master
   - `await chain.save();`
9. **Events**
   - N/A

## Unit Testing

Happy Path:
- GIVEN existing community without namespace, WHEN set namespace command invoked, THEN expect success
- GIVEN existing community with namespace, WHEN set namespace command invoked, THEN expect success

Sad path:
- GIVEN user does not own corresponding ENS, WHEN set namespace command invoked, THEN expect failure
- GIVEN the user has no ERC1155 balance, WHEN set namespace command invoked, THEN expect failure

**Comment by jnaviask** [comment]
@kurtisassad @Rotorsoft curious about the TODOs here involving validating the other + namespace. Will that logic require separate tickets? Should @ianrowan be involved in writing e.g. policies for this case?

**Comment by kurtisassad** [comment]
I have a general idea, but not sure the exact implementation details, so its a bit difficult to fill out the ticket. Anyways the namespace validation will still be a part of this ticket, I just need to play around with the code before I can write concrete steps here.

General idea is that the backend we will need to be given the transaction hash (which comes from the NamespaceFactory which Ian provided, that front end will call). From this hash we can validate that the transaction went through and add it to the database.

**Comment by jnaviask** [comment]
A little worried about our lack of detail here -- would really like to get a clearer picture of what the eventual implementation will look like _before_ I sign off on the implementation work. Do you have any information to add here @ianrowan that might clear up things for @kurtisassad? In particular, my questions would be:
1. Are we providing a contract address (or some sort of persistent storage value) or a tx hash from the client once the transaction completes? I would assume the former given that we want to make it possible for interrupted client process post-tx submit to complete the flow successfully, but it seems Kurtis is envisioning the latter.
2. Is there any specific validation we can specify in advance regarding the namespace once provided to the route? Will we need to break out a new ticket specifying the constraints (cc @Rotorsoft), so that Ian can write a helper utility or similar?

**Comment by kurtisassad** [comment]
For
1. We had discussed to do it synchronously (so waiting for the transaction to finish). But if we want to do it asynchronously, that is fine too. But it will take a rethinking of how we plan to do it currently. Maybe Ian could add some info to clear up how we could go about doing it async.
2. We can perform a reverse ENS lookup to ensure that the user has the associated namespace. This is an interface I can call on an ENSProvider.

**Comment by ianrowan** [comment]
For 1. We weren't thinking about polling tx hashes on the backend in exchange for creating an attestation/recovery flow in the admin panel. This is due to the fact that if a client navigates away, even if we complete the namespace save operation on the backend, they still would not be able to recover to the Community stakes config step. So in that case we always end up needing recovery steps for each so it seems more worthwhile into building manual recovery archs vs async automatic confirmation. The hope for simplicity was also to use the update community route with some added validation for adding a new namespace value to a community.

Validation would be something like: Confirm namespace is not used by other existing community, confirm user/admin address holds admin token on namespace(just a erc1155 balance check via tbc). This validation helper could be reused for a recovery attestation flow as well using the same route, just with the name being user input vs a tx result

**Comment by ianrowan** [comment]
@Rotorsoft I will make a ticket for this. I forgot/didn't realize we were going to break out that part of the validation to a separate ticket

**Comment by Rotorsoft** [comment]
Thanks @ianrowan !... the validation step will be just calling this helper utility

**Comment by ianrowan** [comment]
@Rotorsoft added the ticket + added to the description above

**Comment by jnaviask** [comment]
Great -- glad we got clarity above. Remaining work here is for @kurtisassad to fill in the places he's tagged on the top-level ticket.
