### ISSUE TITLE
Reduce the number of `getAddressProfile` API requests

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#5917]
## Description

We are making (in some cases) hundreds of `/getAddressProfile` calls ALL of which contain only a single address and many (~40%) contain no response data other than 'success'. This means we are making hundreds of unnecessary API calls. For example, https://commonwealth.im/dydx/proposal/15-governancestrategy-smart-contract-upgrade

## Engineering Requirements

- Modify the logic for fetching address profile so that we properly batch addresses together to drastically reduce the number of API calls without significantly reduce client performance (especially in distant regions e.g. Singapore -> limit response size per request to a reasonable maximum).

**Comment by timolegros** [comment]
Tagging @kurtisassad @rbennettcw and @Rotorsoft for visibility.

**Comment by jnaviask** [comment]
Note that we already support batch querying on the platform side -- we just need to figure out how to support it on the client.

**Comment by kurtisassad** [comment]
I just want to note that modifying the logic so that we properly batch the address calls together will take a lot of work. Right now we make these getAddresProfile calls in each User component (Every time the user is displayed on the screen). The issue is, this is called in 25 places. So it will be a large overhaul.

Also I would like to do it correctly, so we will be joining in the profile table in each originating DB call (For example on the discussions page, we modify the bulkThreads in order to get all the associated user profiles). Again, this adds complexity as now we need to touch the backend as well.

Anyways, it seems the majority of the db calls are in the Discussions and ViewThread pages. So once those are fixed, we shouldn't have issues. But to properly remove all the usages of getAddressProfile, this will take a bit of work.

**Comment by rbennettcw** [comment]
If a lot of similar requests are made in a small window of time, I wonder if it would be feasible to perform frontend batching to convert multiple requests into a single?

Potential solution: https://tanstack.com/query/v4/docs/framework/react/community/batching-requests-using-bathshit

**Comment by kurtisassad** [comment]
There are 2 problems here:

1. React renders at different speeds based on the performance of the computer (What batching time is good for both mobile and desktop? This will be difficult to figure out)
2. We still need to make subsequent synchronous requests (ex one request to get Threads, then after getting addresses, one request to get profiles). Becuase these API calls can not be performed in parallel, this adds an extra roundtrip time. I think its a better idea to just get the profiles while we get the addresses.

**Comment by Rotorsoft** [comment]
Another option is to redefine the query - for example, given the user id as input, return a view with all relevant attributes, including addresses, profiles, etc

**Comment by kurtisassad** [comment]
Yeah that is the direction I am going with. The only problem with this is that it will be a lot of work since we need to lift the state from all children User components, and there are 25 of them. In the associated PR I approach this with the fig-strangler pattern so we can gradually perform this migration.

But with the Threads and Comments cleaned up, I think it will be a ~90% reduction in getAddressProfile calls.
