### ISSUE TITLE
Voting on a gated poll is enabled for all users, throws error

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#5951]
## Describe the bug

Currently, any community member can vote on polls within a gated topic. This results in the user getting an error toast:

> Error submitting vote. Maybe the vote has ended?

## To Reproduce

- [Go to this thread](https://commonwealth-demo.herokuapp.com/cmn-protocol/discussion/14357-testtesttest?tab=1)
- Vote on Poll

## Expected behavior

- In a gated topic, if the user is not in a proper group, the Poll itself **should be disabled** for interaction:
  - [x] The user should not be able to select a radio button (radio buttons should be disabled)
  - [x] The user should not be able to press "Vote" (vote button should be disabled)

## Additional context

<img width="1482" alt="Screen Shot 2023-12-11 at 6 42 22 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/a47ba4c4-80e1-414f-8aab-5f128f6f9e6c">

**Comment by rbennettcw** [comment]
To be a bit more clear here (since it's implied that gating is broken), I'd say:

Currently, any user can _attempt_ to vote on the frontend, even if they aren't in the group. But the backend will still block users who are not in the group. The scope of this ticket is to disable voting on the frontend when a user is not in the group.
