### ISSUE TITLE
Connecting a new address with metamask does not work on any browser

### ISSUE THREAD

**Issue by jnaviask** [hicommonwealth/commonwealth#5971]
## Describe the bug

This issue came from Rhys during our meeting for the login issues.

When a user wants to add a new address to their account, the problem with the login flow we see at #5968 was also affecting the users and they were not able to use multiple accounts under one wallet.

## To Reproduce
1) Create a Commonwealth account with Metamask or Coinbase wallet.
2) Join any EVM community, otherwise, the option to add an additional wallet does not come up in the dropdown menu
3) Try to connect a new wallet.

## Expected behavior
Nothing happens in the front end however, we can see the errors we have seen in the #5968 and #5970 also come up on that screen.

**Comment by ianrowan** [comment]
Please retest with changes from #5968

**Comment by egetekiner** [comment]
Tested the following scenarios

1) Login with Metamask, add Coinbase wallet.
2) Login with Metamask, add Metamask.
3) Login with Coinbase, add Metamask.
4) Login with Coinbase, add Coinbase.
5) several 3-4-5 wallet scenarios to see if everything is working properly

All tests have been passed and as @ianrowan mentioned, the problem was resolved with the merge of #5968 

I also sync up with @RhysCommonwealth to see if the problem seems resolved from his perspective and the answer after his tests is positive.

I am closing the issue with this comment.
