### ISSUE TITLE
Unable to delete community 

### ISSUE THREAD

**Issue by cowballzach** [hicommonwealth/commonwealth#5973]
## Describe the bug
When clicking delete community in admin panel an error pops up for https://commonwealth.im/luna-blockchain/discussions

## To Reproduce
Go through the delete community steps in the admin panel

## Expected behavior
The community that is deleted should delete

## Additional context
![image](https://github.com/hicommonwealth/commonwealth/assets/144931524/9eb734a8-b0e1-4128-9733-e25d5a5b58e7)
![image](https://github.com/hicommonwealth/commonwealth/assets/144931524/7affab98-86c5-4172-9c15-3b59bb4863af)

**Comment by CowMuon** [comment]
Now that we have create community implemented, we "low key more than ever"™ need an epic to clean up community model, so we have clean semantics around what is required for community creation, and moreover what is required for community deletion. 

Heretofore, community deletion has been best efforts following these steps: 
1. User tries to delete an empty or otherwise unused community, but the delete operation fails (silently or not.) 
2. We investigate to determine what property got left hanging that is preventing deletion. We fix both the particular and the general case. 
3. Rinse & repeast, as we do not possess a semantically complete model of what a community is, or a complete list of conditions that must be met for the community to be deleted. 

NB. This also applies to deleting users (same "steps") 

@Rotorsoft to review model so that going forward these deletion operations will be unimpeded.

**Comment by CowMuon** [comment]
Added this to Create Community milestone, just for visibility (v1 is done.)

**Comment by CowMuon** [comment]
Having said that, can we get a point estimate for just this scope of work? @lzach83
