### ISSUE TITLE
[SPIKE] Investigate use of Web3Modal for sign-in

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#5979]
## Description
Maintaining a consistent cross-platform sign-in experience across all wallets and ecosystems is a significant challenge, and has been one of the main app areas users are less than delighted with. It seems like Wallet Connect's [web3modal library](https://github.com/WalletConnect/web3modal) may be a good option to greatly simplify how we handle the diverse mix of use cases too numerous to even list out here. 

This research spike is intended to make an initial determination as to feasibility of using web3modal to handle all sign-in cases. 

## Engineering Requirements
We don't currently have formally specified requirements for the sign-in module. Spike output should include general requirements the chosen solution should meet. (This aligns with our stated approach of solving a specified problem, not picking a solution.)

## Acceptance Criteria
Spike output document should address the following exhaustive list of potential concerns:
- Elaboration of requirements for such a library. 
- Evaluation of suitability for pupose of web3modal library (meeting functional requirements) 
-- What do we think of overall code quality and design patterns? 
- Evaluation of general maintainability of web3modal (some example focus questions) 
-- How many maintainers and how active is development? 
-- What is state of outstanding issues queue? Any showstoppers or concerns? 
-- How many stars on the project github? 
-- How extensive is web3modal test suite?
-- What are web3modal's upstream dependencies and what do we think of them? 
-- What is our assessment of project risk factor for deprecation? 
- Evaluation of collaborative potential
-- How actively does this project merge external contributions? 
-- What expectations would we have WRT contributing to project? 

## Additional context
web3modal version 3.x looks very interesting and is a ground up re-write of the library over v2.x which was originally released in Sept 2022, and has since matured to version 3.4.0/[3.5.0-alpha.1](https://github.com/WalletConnect/web3modal/releases/tag/3.5.0-alpha.1). They claim it is mobile first with seamless handling across iOS, Android and Desktop, and honestly it looks really good. The purpose of this spike should really be to find the downside, to wit, reasons we should avoid using web3modal. 
- https://web3modal.com/

**Comment by dillchen** [comment]
I will add one product consideration here, is it headless or what's the level of UI customizability

**Comment by ianrowan** [comment]
Initial research:

**Comment by ianrowan** [comment]
Initial research: https://docs.google.com/document/d/1ha4Sg5tGQbxQ_VttwhjQ1igwEqViTc942pcLrA99kpQ/edit?usp=sharing

In summary:
- It will not cover most cosmos or non-evm wallets
- It is great for evm wallets and should replace our WC + MM, other evms etc wallets adapters
- Overall very solid product and what many other dapps use purly for their sign in(b/c they are usually just evm by default)

**Comment by egetekiner** [comment]
Here is the output of my research: https://docs.google.com/document/d/1vWR8copHHO2F9IRX0H7I0M1faKxa2GCrVirqBFYAM7U/edit?usp=sharing

My overall opinion is;

I believe Web3Modal is a very resourceful product and in the short/mid-run, it can be very beneficial for us.

Pros:

- Easy to implement
- Allow us to integrate all EVM-based networks effortlessly.
- Maintaining and running by both the team and community
- Continuous integration, documentation, and upgrades for developers


Cons:

- Possible user privacy problems due to its RPC and Wallet connection structure
- Creating third-party dependency that may lead us to a problematic state in the long run.
- Expandibility might be a problem in the mid/long run.
- We might not want to lose the practical knowledge we have on wallet integrations

If we would like to integrate Web3Modal in the long run, we must be sure about the data privacy of our customers.

We can create a custom front-end flow to keep our system expandable and have the flexibility to move away from Web3Modal without creating any problems on the user side.

**Comment by jnaviask** [comment]
Next step, prototype #6141
