### ISSUE TITLE
of our 1inch core team members are having trouble logging in

### ISSUE THREAD

**Issue by markiscommon** [hicommonwealth/commonwealth#6002]
## Describe the bug
"Hey Commonwealth team! Some, but not all, of our 1inch core team members are having trouble logging in. Below is the full context, do you guys have any suggestions for how we can troubleshot this? 

<img width="514" alt="Screenshot 2023-12-13 at 11 51 51 AM" src="https://github.com/hicommonwealth/commonwealth/assets/128752305/96b6c9bb-0fc4-4e98-a9cb-453900e5c0ae">
<img width="534" alt="Screenshot 2023-12-13 at 11 52 10 AM" src="https://github.com/hicommonwealth/commonwealth/assets/128752305/98d084d8-794b-4229-bb23-c81983a16b25">
<img width="552" alt="Screenshot 2023-12-13 at 11 52 19 AM" src="https://github.com/hicommonwealth/commonwealth/assets/128752305/fe664baa-04c4-4ff4-9b5e-ac19ef26994e">

## To Reproduce
"Looks like the connection methods had changed and I can't connect neither web3 browser nor WC2 "

## Expected behavior
able to login without issue

**Comment by ianrowan** [comment]
1. Metamask will no longer work for wallets other than metamask 
2. Wallet connect QR code login will be the only login method for 1inch wallet as their wallet appears to be out of sync with current WC version. 

- More details here: Upon trying to login directly via WC on mobile a 'Invalid url' error is thrown within the WC app(not our own code). This points to the deeplink WC uses to request the 1inch app being out of date or incorrectly specified. Any other wallet browser works with WC(metamask, trust, etc) as tested so this issue is isolated to 1inch x wallet connect. The QR code method does still appear to work as it is much more flexible 

So suggestion would be to have the user sign in with the QR code and confirm is any issues arise.

**Comment by ianrowan** [comment]
For reference the same WC issue occurs using 1inch wallet app browser to access uniswap, so def a 1inch wallet issue
![image](https://github.com/hicommonwealth/commonwealth/assets/36428666/06fa0541-12ff-490e-834c-0b56186b140e)

**Comment by CowMuon** [comment]
We communicated resolution directly to 1inch team on Telegram. Their users should still be able to log in, but the actual bug is in the 1inch wallet (which is lagging behind Wallet Connect current version); as such closing this ticket.
