### ISSUE TITLE
Generated image cannot be uploaded because of the size exceeding the 500kb limit

### ISSUE THREAD

**Issue by masvelio** [hicommonwealth/commonwealth#6009]
## Describe the bug

In new community flow we allow user to generate the community profile image. The problem is that generated images are usually above 500kb. Thus, on community creation, backend throws the error that image is too big. 
In this case we should either:
1. bump up the limit size
2. generate smaller image (max 500kb) 
3. compress generated image in the backend

## To Reproduce

add `FLAG_NEW_CREATE_COMMUNITY=true` to .env

1. go to branch `marcin.5896.create-community-backend` and page /createCommunity
2. be signed in
3. select EVM
4. fill out the form + generate the image (do not upload)
5. launch community
6. Backend throws error that the image is too big

https://github.com/hicommonwealth/commonwealth/assets/14819225/24390d37-b605-426e-90f3-48e1db7cf087

## Expected behavior

6. user should be able to create community with generated image

## Additional context
Because `CWCoverImageUploader` is reused in new create community flow and in edit profile page, making changes, make sure that both places are working correctly.

**Comment by jnaviask** [comment]
cc @kurtisassad and @mzparacha to work together and evaluate the proposed options + implement a fix

**Comment by dillchen** [comment]
Compress on the backend

**Comment by mzparacha** [comment]
cc: @kurtisassad ^

**Comment by kurtisassad** [comment]
@mzparacha sorry for the confusion here. We ended up solving the issue.

So there are 3 approaches:
1. like dillion suggested compress the image on backend
2. decrease max image size from 512x512 to 256x256 (This will reduce the size by 1/4)
3. compress the image on front end.
4. Increase max image size

So lets look more closely at 3, since it is the simplest approach code wise (and doesn't conceded anything on the product side like 4).

The theoretical max image size for a png with 256x256 is as follows:
Since each pixel is represented by rgb + a, and these range from 0-255 (1 byte each) we have:
256×256×4bytes=256KB

So this is well under our currently implemented limit of 500kb. If we determine this is an acceptable approach, then you can find the code here: https://github.com/hicommonwealth/commonwealth/pull/6003/files#diff-1fb6d204310dca2a3803b3f1bff53906ba7e19a3daaa23456be641ccd85a84c7

**Comment by CowMuon** [comment]
Yes, I have a definite preference for compressing on the front end here. Thanks Kurtis

**Comment by dillchen** [comment]
Didn’t know that option 3 was avail. Fully aligned. Sorry for any confusion

Sent via Superhuman iOS ***@***.***>

**Comment by mzparacha** [comment]
so sounds like we are all aligned on compressing the image size on frontend. Working on it...
