### ISSUE TITLE
[Docs Improvement] Create Ubiquitous Language Glossary For Knowledge Base

### ISSUE THREAD

**Issue by gdjohnson** [hicommonwealth/commonwealth#6334]
## Context

This morning, I discovered (6 months into my tenure...) that there is an "engineering glossary" in [Notion](https://www.notion.so/buildcommon/a3184412f9964aa99efe628921f3c7db?v=ae49c547e59b4f60a5b2d1e8e7d680ac).

It has not been updated since January 2023 i.e. over a year ago.

For a long time I've wanted to have a basic glossary for engineering, since internally we use many non-standard terms that can be opaque. This seems like a good place to start.

## Motivations

- Establish, commit to, and document our ubiquitous language
    - E.g. how we use “stake” is unique; we prefer “sign in” to “log in” etc
- Improve onboarding and communication: engineers won't have to ask (or worse, wonder/be confused) about unfamiliar terms, and if they do ask, there are resources to point them to with standard info
- Useful reference in general; helps bridge everyday language with code

## Open questions

- How to bound the glossary: What criteria do we use for inclusion/exclusion of concepts?
    - Ostensibly we don't want/need standard terms, used in standard ways, documented. Being comprehensive about documenting React or crypto vocabulary would be an enormous lift with dubious returns—do we really need to explain what a Layer-1 vs Layer-2 solution is?
    - Ostensibly all terms defined should "exist" in some way as an entity or design principle of the codebase 
- How to interface with other teams; how to evolve definitions
    - My one concern is that from a DDD perspective, the engineering team's understanding of a Chain or Member or Stake should stay in sync with product and growth's understanding of a Chain or Member or Stake. That perhaps this sort of glossary shouldn't be cloistered and independent, or shouldn't need manual updating and syncing with other teams' glossaries. Is this an area we want to collaborate with other teams, and do we think we can get buy-in from them? I'm curious if @Rotorsoft has thoughts about this.

**Comment by Rotorsoft** [comment]
This is a good idea. Language is one of the key elements of DDD, and having a definite understanding of our domain, terms, and jargon in collaboration with product and business teams is essential to any organization.

You probably want to dedicate a special section to this, with examples in context, and focusing on finding if there are any existing ambiguities that need to be resolved.

**Comment by gdjohnson** [comment]
Update: As of 240219, I have built out a basic glossary, but open questions remain. 

Teeing up to be discussed with @CowMuon in person next week after EthDenver wraps:
- "Story" vs "ticket" vs "issue" semantics

Teeing up to discuss with @zakhap next week:
- Roles, permissions, groups—semantics + domain model

**Comment by CowMuon** [comment]
I'll be in Denver next week and then back on 3/4. We should put a bow on Glossary and circle back then, as the TSDoc and DevX projects are much higher priority, and we'd like to execute swiftly on both. (We can discuss any questions around TSDoc async) 

Just to sketch out semantic nuance in question: 
- **Ticket** always refers to to a "physical" location in Github which holds current status and discussion of a given issue. 
- [An] **Issue** is the substantive content of a ticket, which exists in the abstract apart from the ticket. Eg. "The issue is that sign-in with Magic is broken upstream." 
- [A] Story is an issue in story format, that is presumed ready for execution and generally takes the form "as a user I am able to" "as an admin" etc. The idea here is stories represent the actual problem the user needs us to solve for them. 

I feel like above should be enough for you to add entries, HMU on slack if you have any wording you want to run by. 

Let's punt roles & permissions (aka R&P) until after we've completed our 2 top projects (TSDOc & DevX.) Also JTN domain model for R&P will need to be more than an event storm (obvi.)

**Comment by ForestMars** [comment]
(Left review on Open Feature / Unleash language.)

**Comment by gdjohnson** [comment]
@ForestMars where is that? Not seeing on PR
