### ISSUE TITLE
Handle Form Abandonment

### ISSUE THREAD

**Issue by Miaplacidus** [hicommonwealth/commonwealth#6419]
Currently, we have no protocol for how to handle forms when they are abandoned (i.e. a user fills out one or more fields in a form and then navigates away from the page on which the form is located). 

In this card we would like to do the following:

1. update CWForm so that when the user navigates away from any page where it is being used, the user sees a modal informing them that they have unsaved changes and asking them to confirm that they'd like to navigate away
2. handle the situation wherein the form is on a tabbed page (see below for more details)

To complete this card, we recommend making use of `react-router`'s `useBlocker` [hook](https://reactrouter.com/en/main/hooks/use-blocker). Note that it doesn't work when the form is in a tabbed component (i.e. it is within a component that is on a page with tabs and you are navigating to one of the other tabs). It may be better, in this case, to store the form's input details in `localStorage` or something and simply fill in the inputs when the user navigates back to the form.

Follow-up ticket #6420 has been created to make sure that all of our forms (where possible) are using `CWForm`.

@mzparacha @Israellund @masvelio @sachben91 <-- tagged to add any other details
@ForestMars @jnaviask <-- tagged for visibility

**Comment by CowMuon** [comment]
@masvelio Are you in agreement with above approach? Also would be good to get an estimate here for teeing up.

**Comment by masvelio** [comment]
@CowMuon for me the question is if we really need this kind of the behaviour. It is very rare in the web apps to prevent user from navigating away from the current page (it is also not ideal to prevent native behaviour of the browser). I always say that we should not try to be smarter than a user. If one wants to navigate to other page once filling out the form, then he should be able to do this and we can't do much about it.  

The behaviour that can be seen in web apps more often is when the user clicks "cancel"/"back" button on modal/form etc. Then there might be some warning popup that says that progress might be lost. I would rather opt in this direction. 

I can't estimate it, because I don't know how the designs would look like, how many places in the app should be handled and what would be the final solution. We can try to add this "generic" feature to CWForm. The problem is that there are only 7 occurrences of CWForm in the code, and we probably have more forms in the app (they are used with old approach with <form/> or just <input /> components). On the flip side, do we really need this behaviour in every form? 

I think this would need some input from design/product team. In my opinion this is low priority.

**Comment by Miaplacidus** [comment]
@masvelio @CowMuon 
Just want to leave a note here to consider reaching out to growth about logging form abandonment to MIxpanel.

**Comment by CowMuon** [comment]
Per Growth.

**Comment by CowMuon** [comment]
Per Growth.
