### ISSUE TITLE
Creating a new topic shouldn't cause the scroll position to jump to the top of the page

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#649]
Also seems to happen with other modals? Hopefully the fix is simple

**Comment by zakhap** [comment]
@raykyri 
I spent the last little while playing around with different ways to have the modal not-jump when being opened and it's explicitly because we're 'fixing' the document.body when opening the modal. The simplest fix is just removing the position: fixed and all modals still pop up, still go full screen with overlay, but you can still scroll in the background. I couldn't quite get the [csstricks link](https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/) commented into the code of views/modal to work as it said it would. Namely the issue is in setting `document.body.style.top = '-${window.scrollY}px';` which never actually gets set even if though it is run.
