### ISSUE TITLE
[SPIKE] Mobile research 

### ISSUE THREAD

**Issue by CowMuon** [hicommonwealth/commonwealth#6506]
## Description
Placeholder ticket for mobile development spike.  

## Project Owner
@sachben91 

## Spike Goals
As discussed in mobile kickoff on 1/29, to"address any unknowns in the project"; this is fine for an open-ended research spike where we need to take stock and that's really what's needed here. 

That being said, it would be great to surface any specific questions to be answered, apart from the v general questions around
- Feasibility: Are all tickets complete and ready for execution? 
- Missing information:  that ENG needs from Product or Design?
- Anything that Product Design needs to be made aware of?

## Deliverable 
Findings in the form of a write up with risk assessment and recommendations

**Comment by zakhap** [comment]
Most important tickets to get feasibility sign off on are: 
- https://github.com/hicommonwealth/commonwealth/issues/6389
- https://github.com/hicommonwealth/commonwealth/issues/6400
- https://github.com/hicommonwealth/commonwealth/issues/6401

**Comment by rbennettcw** [comment]
## ETH Denver Milestone Risks
- Keyboard Detection
  - Browsers cannot directly detect if the virtual keyboard is open, but they *can* detect if an input field is in focus– which is a decent indicator that the keyboard is *probably* open. The designs/requirements should reflect that.
- Lack of PWA installation detection
  - iOS Safari cannot detect if the PWA is installed (added to home screen)– we should be careful about spamming the PWA install CTA
- Storage isolation
  - Storage is isolated between iOS Safari and standalone PWA, so user will need to log in seperately to both.
- Wallet login on mobile
  - Using wallets on mobile typically requires running a special browser that injects the wallet into the app runtime. Standalone PWAs won't be able to utilize wallet functionality, which is at odds with community stake monetization

## Rendering on Mobile
- Pixel density
  - In CSS, using `em` and `rem` instead of `px` makes it easier to scale UI for accessibility (consult with Marcin on applicability)
  - Demo: https://www.toheeb.com/en/px-em-rem/
- Responsiveness/breakpoints
  - Use CSS media queries (already using it)
  - Or `useMediaQuery` React hook (not using it)

## Offline Usage
- Use Service Workers to prefrech and cache assets, intercept fetch requests
  - Sample code: https://github.com/GoogleChrome/samples/tree/gh-pages/service-worker
  - Live demos: https://googlechrome.github.io/samples/service-worker/
  - Core functionality supported by both Chrome and Safari

## Notifications
- Client side -> Web push notifications
  - iOS: requires PWA to be added to home screen to receive push notifications
  - Android: does NOT require PWA installation to receive push notifications
  - Both require Web App Manifest + ask for notification permission
  - Implementation: Add service worker script which subscribes to notifications in background
- Server side -> Web push notifications
  - Self-hosted solution: https://www.npmjs.com/package/web-push
    - Requires GCM key (google cloud) + VAPID key (apple)
  - Recommend: use 3rd party service + use port/adapter abstraction to avoid vendor lockin
  - More research required to estimate effort
## Testing on Mobile
- Basic: Chrome dev tools -> Device mode
  - Okay for testing responsiveness: https://developer.chrome.com/docs/devtools/device-mode
- Better: Mobile OS Emulation (iOS/Android)
  - Better for testing OS behavior, keyboard, PWA install, notifications
    - iOS -> Download Xcode -> Run iOS Simulator
    - Android -> Download Android Studio -> Virtual Device Manager -> Run Android Emulator
- Best: Physical mobile device (iPhone/Android)
  - For testing real mobile UX

## Manually Installing a PWA
- A proper PWA requires a manifest:
  - Spec: https://developer.mozilla.org/en-US/docs/Web/Manifest
  - Generator tool: https://tomitm.github.io/appmanifest/
  - CW App has one, but incomplete
- Safari/iOS -> Share -> `Add to Home Screen`
- Chrome/Android -> Menu -> `Install app`
  - Or address bar install button

## Programatically Installing a PWA
- Not possible, but can detect device type and show prompt with instructions to install manually

cc @CowMuon

**Comment by rbennettcw** [comment]
Clarification regarding wallets on mobile– user can sign transactions 2 ways:
1. By using their native wallet app's browser (e.g. Metamask) which injects the wallet into the site OR
2. By using WalletConnect as a bridge to a supported wallet

CW app supports WalletConnect, and it works fine in the standalone PWA and in any browser– so nothing to worry about!
