### ISSUE TITLE
Subscriptions Screen

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#6628]
## Descriptions 
The subscriptions screen shows the list of replies and threads that the user has subscribed to receive push notifications by clicking on the subscribe bell icon. The screen will only show items the user has subscribed to by clicking on the subscribe icon. If the user has done this, they will receive both in-app and push notifications for the item they are subscribed to. 

## Feature Specs 
- the subscriptions screen will show the title of the thread the user subscribed to and the name of the community that it has been posted to
- clicking on the title should take the user to the original thread 
- the user should be able to click on unsubscribe from the list to unsubscribe from the thread 
- user should be able to sort the list of threads they have subscribed to by 'most recent' (ascending order by time original thread was posted) or 'oldest' (descending order by time original thread was posted) 

![Image](https://github.com/hicommonwealth/commonwealth/assets/38763242/1a603168-8bc3-4b8a-9dd3-add2e4e26528)

## Designs 
[Figma ](https://www.figma.com/file/WdlVQRpQKg4GMgCOzbQt34/Notifications?node-id=261%3A5014&mode=dev)

**Comment by burtonator** [comment]
There's a problem here.

Right now we fetch /api/communities and that fetches all 2400 of our communities.

I'm worried that's going to fall over really fast.

I could continue the pattern that the existing code uses, or I could update the REST endpoint and fetch only the community IDs that I need to fetch.

I think that's the way to go but would take longer to get this out the door. Probably 1/2 to 1 more day.  

@jnaviask @sachben91 @kurtisassad

**Comment by kurtisassad** [comment]
Basically you should have all the required information from the initial status call that loads in those communities. The regular way of doing it would be to just pull the required info from `app.chains` (Which is loaded in by the initial status call)

As we talked about though, if we ever plan to do it the right way, we will need to refactor this approach out, so we would be adding more work to the pile we need to fix. But for now pulling it from the global variable is the easiest way of doing it.

**Comment by burtonator** [comment]
@kurtisassad Let me kook at the original call and app.config.chains and see if you're correct. I'd love to not have to refactor anything and get this done quickly.

The other idea is to put all the data in the initial REST call then port this to trpc. 

@sachben91 The problem is that this opened up a pandora's box because we have to rework the routes and the way we fetch data here to render this page.  Another idea is to change the UI to not show the community but we can talk about this in the next notifications meeting. IT will add 1/2 to 1 day to get the TRPC changes done and this ported over.

**Comment by burtonator** [comment]
FYI just and update. I've resolved the type issues and I think I just have a few questions for @sachben91 (which I asked over slack)

**Comment by burtonator** [comment]
OK here are the changes

- we are collapsing all the subscriptions for 'comments' and 'reactions' to be under each thread.  Each 'unsubscribe' button does both.
- Filter by will go away and we are just going to have Sort By which will have "most recent" and "oldest" options
-

**Comment by burtonator** [comment]
Update on this one. It's going to create me a bit longer to get this done. I didn't initially know how much tech debt was required here and I went down the path of working with the existing routes. 

After talking to @timolegros it was clear that I have to enable new trpc routes.  I'm working on that now and then the types on the frontend should be clear.  the main thing I have to do is get done the route on the frontend and that's what I'm working on now.

At least it's down hill.

**Comment by burtonator** [comment]
I have the basic functionality working:

![Image](https://github.com/hicommonwealth/commonwealth/assets/45447/1437b4a8-bf26-47a0-86f0-9a21c33377be)

But have 2-3 issues remaining. They're documented in FIXMEs for the draft PR.

They are related to 'id' and types being required but not specified in the client.

https://github.com/hicommonwealth/commonwealth/issues/7912

https://github.com/hicommonwealth/commonwealth/issues/7911

**Comment by burtonator** [comment]
@sachben91 Are you ok with these changes?

This is what the original looks like:

![Image](https://github.com/hicommonwealth/commonwealth/assets/45447/d7276588-c722-4874-b2ec-64dd2b1c726c)

And this is what the current implementation looks like:

![Image](https://github.com/hicommonwealth/commonwealth/assets/45447/37403ed1-96f5-4970-874d-6753c9be8003)

Note the following differences:

- No "..." overflow menu. It doesn't make sense in this context. The main one for threads has options that don't make sense on this page.  
- The author on the line above has an icon to the left.  That's per the thread UI as it does the same thing when mentioning users.
- The time was different "1h" vs "1 hour ago" because that's what our standard "time difference" library does.
- The comment line says has just a number to the left of the comment icon.
- No share icon
- Unsubscribe is just the bell which is how the thread page has it.

I don't feel strongly on any of the above just trying implement it with what we "intend" but if you have any changes I can make them. Just let me know.

**Comment by sachben91** [comment]
these look good to me
