### ISSUE TITLE
Cosmos Proposals UI: Update Input to be Markdown Editor

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#6635]
## Description

Our existing Cosmos New Proposal Form only has Plaintext input for the Proposal Body. Most Cosmos Proposal UIs expect Markdown formatted text from onchain proposals.  In Q2, we will revisit this page in full. However, we should attend to easy wins for users in the meantime.

- [ ] Update our Description Input field to be our Markdown-only Editor. 
- [ ] Make sure Markdown formatted proposals submitted from our UI render properly. Existing MD proposals currently render properly.

## Project Owner

PM: @zakhap 

## Acceptance Criteria

- Users can successfully format new cosmos proposal bodies with our Markdown Editor. 

## Additional context

Existing Cosmos New Proposal Form
<img width="478" alt="Screen Shot 2024-02-07 at 7 31 42 PM" src="https://github.com/hicommonwealth/commonwealth/assets/16248081/c3c015dd-0cf4-40e2-a97b-f307978e203b">

**Comment by mhagel** [comment]
QQ @zakhap 

The markdown editor toolbar wraps to two lines in the existing Proposal form width. Is it ok to stretch it out to 476px instead of 432px to make the toolbar a single line?

<img width="1040" alt="Screenshot 2024-02-20 at 4 00 39 PM" src="https://github.com/hicommonwealth/commonwealth/assets/9438198/cf0067c8-028e-46b2-8b45-6ced64ab87e8">
