### ISSUE TITLE
"Sign in with another email address" does not work

### ISSUE THREAD

**Issue by timolegros** [hicommonwealth/commonwealth#6806]
### Initial conditions

**Environment:** production
**Branch/Release version:** v0.9.5
**Browser:** Chrome

## Reproduction steps

1. Go to https://commonwealth.im/
2. Click sign in button
3. Click "Sign in with another email address"
4. Input your email and then click the "Sign in with Magic" button

## Expected behavior

Should be able to login with an email not connected to a Google account

**Comment by kurtisassad** [comment]
It seems we recently changed the logic for sending emails. We have this line in useWallets.tsx:
```
const tempEmailToUse = emailToUse || email;
```

For whatever reason, when we go through the email flow this is some object, instead of the email address. If you remove the emailToUse ex (`const tempEmailToUse = email;`) then the email flow works fine.
