### ISSUE TITLE
Autogenerate stakeholder group

### ISSUE THREAD

**Issue by HIM92** [hicommonwealth/commonwealth#6843]
## Description

Goal: After enabling stake on a community, automate the creation of "stakeholder" group within the community. 

- User story: As an admin, I want a group named "Stakeholder" autogenerated after I enable Community Stake, or create a community with stake enabled. 
  - the only requirement for to be a member of this group is set to the deployed stake contract of the community with a threshold of "more than 0" tokens. 
  - the group's description copy is: "Any member who acquires your community stake is a stakeholder of your community, and therefore a member of this group."
  - the group is not editable
  - when a member burns all of there stake and has, i.e. goes from 5 to 0, they are removed from the group.
  - Within the members page, the amount of stake owned by a stakeholder is provided in a column.

<img width="592" alt="Screenshot 2024-02-22 at 1 19 20 PM" src="https://github.com/hicommonwealth/commonwealth/assets/153562904/f24c4884-0bad-45ef-960e-ecadaddf8cf1">

## Additional context
figma for Members table: https://www.figma.com/file/KOEVNGXStBhmX3NnYq7MxP/Community-Stake?type=design&node-id=1738%3A118984&mode=design&t=Yy95f9WJmwEIB9hR-1

**Comment by rbennettcw** [comment]
**Key Decisions:**
- Add a flag to `Groups` to mark it as "system managed," which prevents editing by users.
- Store stake balance on `Memberships`, since they need to be efficiently queryable/sortable by the UI.

**Proposed Implementation:**

- ✏️ **Data Model Changes**
  - `Groups`
    - Add `is_system_managed`: bool
      - If true, the group is locked for users.
  - `Memberships`
    - Add `stake_balance`: number
      - To efficiently query/sort stake balances for UI display.
      - Assuming integer overflow won't be a problem

- ⚡️ **Policy Changes**
  - ➡️ Add policy: Autogenerate Stakeholder group for a community and set `is_system_managed` = true.
    - When:
      - Community created.
      - Community stake enabled.
    - Group rule: must have > 0 of stake token.
  - ➡️ Add policy: Update `membership.stake_balance`.
    - When:
      - User buys stake.
      - User sells stake.
    - Helps to keep DB stake balances fresh regardless of currently refresh lifecycle.

- 📚 **Query Changes**
  - Search profiles
    - Add stake balance to memberships payload for UI
    - (Context: this query is used for fetching profiles + group membership status on the Memberships page)

- 💪 **Command Changes**
  - Update/Delete group routes
   - Disable action if group is system managed

- 🪙 **Protocol Changes**
  - No change– can use existing logic for 1155 stake contract

- 💾 **Data Sync Changes**
  - Create a script to retroactively autogenerate Stakeholder group for each existing stake-enabled community.
    - Requires fetching balances from the chain, so would need to be a script rather than a migration, e.g., `yarn refresh-all-memberships`.

- 📄 **Frontend Changes** (New ticket)
  - Lock the groups editing UI if `is_system_managed` is true.
  - Render stake column in memberships list

**Other Considerations:**
- Not sure if/how this may conflict with the upcoming Memberships migration, particularly the concept of public/default groups.
- We should consider creating a Membership cleanup policy. Currently, membership records are never deleted unless the group is updated/deleted. Since system-managed groups can't be edited, cleanup will never happen. Maybe a cron job that deletes memberships where last_checked > 2 weeks ago.

**Comment by jnaviask** [comment]
@rbennettcw 

> ➡️ Add policy: Update membership.stake_balance.

How will we trigger this policy, given that source of truth for stake balance updates is onchain rather than in-app? Also, what is the specific need (we're discussing in DMs but let's discuss here instead)?

> Not sure if/how this may conflict with the upcoming Memberships migration, particularly the concept of public/default groups.

It shouldn't conflict at all. Stakeholders group can coexist with proposed Default group.

> We should consider creating a Membership cleanup policy. Currently, membership records are never deleted unless the group is updated/deleted. Since system-managed groups can't be edited, cleanup will never happen. Maybe a cron job that deletes memberships where last_checked > 2 weeks ago.

Please put up a ticket -- that said we shouldn't delete _active_ memberships, as we want them to be displayed on the members page. But we should definitely clean up rejected memberships.

**Comment by rbennettcw** [comment]
@jnaviask 

> How will we trigger this policy, given that source of truth for stake balance updates is onchain rather than in-app? Also, what is the specific need (we're discussing in DMs but let's discuss here instead)?

The only reason to persist stake balances is if we need to sort members in the UI by balance. I think admins would want to be able to see who the whales are?

Otherwise, balances could technically be pulled on the fly from the TBC  in bulk during the pagination step and the latency wouldn't be too bad. But we wouldn't be able to sort through the entire list of balances, since we'd only be fetching a subset of balances at a time.

**Comment by jnaviask** [comment]
Got it. IMO will want to orient ourselves to a somewhat more general solution here, so that other types of groups (e.g. an ERC20 requirement) can take advantage of persisting the value for display. It may require slightly more modelling work, though, so for the time being, I'm OK with it being stake alone.

**Comment by rbennettcw** [comment]
As for the trigger– I'm not sure if we currently have a framework for responding to chain events? I think we (used to?) have the "chain events service"? I'm unsure what the current state of that is.

But basically if the source of truth is onchain and can be mutated from outside the app, then yeah we'd need to implement a system to pull contract events and trigger policies. Understandably, there may be hesitation about implementing that kind of system due to increased scope and complexity.

**Comment by jnaviask** [comment]
@rbennettcw I'm ok to proceed with the path of least resistance here. What's the point estimate given that implementation strategy?

**Comment by rbennettcw** [comment]
@jnaviask Estimating as a 5 since we're taking the simplified approach. I've updated my original proposal comment to reflect the latest decisions.
