### ISSUE TITLE
Unread notifications should not be grouped

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#698]
Otherwise "new thread ____" just gets collapsed into a notification that says "X threads were created", and similarly for other notifications.

**Comment by zakhap** [comment]
That was kind of the point batching notifications, I thought?

In the cases of: 
- New Comment on X Thread: you'll see a new notification row for each comment, expanding "X and 4 others commented on Y Thread" into 5 different notifications "X commented on Y Thread"
- Same as above for reactions.

I can see expanding the notifications for: 
- Mentions, rather than "X and 5 others mentioned you" => "X mentioned you" 6 times.

Threads are different because if the community is highly active, you'll get a notification for each thread, rather than just guiding you back to the community where the new threads are already being highlighted for the user (did we removed that feature?)
