### ISSUE TITLE
Edit Profile: Quill ops appearing in markdown editor

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#7267]
## Describe the bug

Quill ops appearing in markdown editor for new users created over Social sign in flow
### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

Master/v1.2.3-x
**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Go to https://qa.commonwealth.im/
2. Sing in with new wallet address over social flow (email)
3. Go to Profile edit page
4. Change display name and save
5. Go to Profile Edit page

## Actual behavior

We have quill operations visible in markdown editor
## Screenshots / Video

https://app.screencast.com/AGzeXq8pMIfAy

**Comment by jnaviask** [comment]
Best guess here is that since the issue only happens with an empty editor, that when we initialize the Quill editor, we don't have `__isMarkdown` set yet, so the `serializeDelta()` call in `edit_profile.tsx` attempts to produce a Quill string rather than a Markdown string, and that what we're seeing is the plaintext of an empty Quill-formatted string.
