### ISSUE TITLE
Update: User selects what ERC20 will fund the Contest

### ISSUE THREAD

**Issue by zakhap** [hicommonwealth/commonwealth#7293]
## Description

In our original event storm for this project, we defaulted to just ETH being used for funding Contests. Through validation with customers and growth, we decided to include ERC20 support for one off and recurring contests. This means admins setting up a new one-off contest will pick which ERC20 they want the contest to use for its prize pool. We will want to display and denominate the prize pool in this user-specified ERC20 (which will be enforced/on the contract itself, cc: @ianrowan for any additional information).

For recurring contests, we will default to using the currency used for Stake, as Stake fees will be funding the Contest. As we roll out ERC20 support for Stake later in Q2, this pattern should hold for recurring contests for those communities.

## Project Owner

@zakhap

**Comment by Rotorsoft** [comment]
@rbennettcw coordinate details with protocol team, but seems like the interface won't be impacted since you need to provide contract details to fund new contests anyway. Guess the UI should manage the new details when creating threads (or content in general) that can trigger new contests, and those details will be carried in the emitted events.

**Comment by rbennettcw** [comment]
@masvelio @ianrowan @Rotorsoft  – It looks like this is implemented via `funding_token_address`? Just want to confirm so we can close this ticket.

**Comment by ForestMars** [comment]
Can we get an estimate here kudasai @ryanbennettvoid

**Comment by rbennettcw** [comment]
This is done. User can specify address of ERC20 token to fund one-off contests.
