### ISSUE TITLE
Users should be able to save drafts of their posts, which are stored on the server

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#73]
General notes:
- Drafts should be stored in their own table on the database
- Drafts should always be discussions. There should be no option to save link posts as drafts
- Titles should not be mandatory for drafts

UI:
- Add a "Save draft" button to the new post dialog & new post page, next to the "Create thread" button. It should have intent: none, and only show when the post type is discussion.

Backend:
- Drafts should be passed up to the frontend in /status, or via their own route.
- Add a sidebar to the "New post" form, expanding the width from where it is now
- The composer should take up 9/12ths of the width, while the sidebar takes up 3/12ths of the width of the newly expanded dialog
- The drafts box should be a construct-ui List. Each draft should have Open and Delete options. Clicking Open should load the draft's content into the editor. Clicking Delete should prompt you with a confirmationModalWithText ("Are you sure?") and if you click yes, the draft should be deleted from the frontend and backend.
- Each draft should show its title and a short excerpt (look at discussion_row.ts to see how)
- Untitled drafts should display (Untitled) for their title
- When clicking Open, if there is already content in the editor, prompt with a confirmationModalWithText whether to discard the current document ("Discard any current edits?")
- After loading a draft into the current editor, it should not be deleted. Instead, the editor should remember exactly which draft is being edited. As such, it will be necessary to generate some sort of unique identifier for drafts.
- If Save draft is clicked again, it should overwrite the previous draft
- If Create post is clicked, the draft should be discarded (it's okay if this doesn't happen atomically)
- It should not be possible to overwrite another user's draft. Any route for deleting drafts must perform the appropriate permissions checks

Final note:
- We will still want to make sure any unsaved edits are kept in localStorage. The same way that Twitter stores unsent posts, in addition to its drafts function (both are available on the web interface now, since about last month)

**Comment by gdjohnson** [comment]
Pretty much all this is done but there's a bundle of things that are broken/being fixed or else are unlisted functionality needed for smooth user experience.

Main items remaining:
[ ] Drafts refreshAll (finished last week but apparently broken—need to make sure the call in the right place to use one of the user's address ids, since I can't rely on activeAccount)
[ ] Quill/Markdown format detection/switching as you choose differently formatted drafts to load & update (unlisted; probably a couple hours)
[ ] Haven't implemented "Untitled drafts should display (Untitled) for their title" (listed, quick)
[ ] General debugging, walking through process, making sure routes have consistent error catching, using a consistent structure of passing user vs. author ids. I'd initially linked drafts up to address ids, but I'm considering overwriting that decision so I don't need to do weird workarounds of checking all of a user's addresses (or the potential problem of if a user switches addresses in a community—seems like he should keep access). (1/2-1 day)
[ ] Writing the tests (unlisted; probably a day's work)

Still have not been able to get a full cycle of creating/editing/deleting + refreshAll'ing on status + proper store mechanics. 90% of that logic was implemented last week, but there are just nagging issues in how the frontend and backend are hooked up. Earlier optimistic goals of finishing this in (8) were way off, this is more like a week'n'a'half project for me TBH. Branch divergence from Raymond.construct is about 1400 lines of code right now and growing—4 routes, lots of interfacing with Quill, a store + controller + UI inteface; it's big feature, not sure what to say beyond that.
