### ISSUE TITLE
Finalize contests projection saga with detailed queries and new metadata events

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#7471]
## Description
This is a FF ticket to refine #6820 with new off-chain metadata events and finalize query interfaces.

## Project Owner
@Rotorsoft 

### Projection

- [x] **Path** - `/libs/model/src/contest/Contests.projection.ts`

- [x] **Events** -  No more events needed. Contest manager metadata will be created/updated via new commands.

- [x] **Schema** - `/libs/core/src/schemas/projections/contest.schemas.ts`

```mermaid
erDiagram
    Community ||--o{ ContestManager: has
    ContestManager ||--|{ ContestTopic : has
    ContestTopic }|--|| Topic : topic_id
    ContestManager ||--|{ Contest : has
    Contest ||--|{ ContestAction: has
    ContestAction }|--|| Thread: thread_id

    Community {
       string id PK
       string namespace
       blob the_other_stuff "other community attributes"
    }

    ContestManager {
      %% immutable on-chain fields
       int community_id FK
       string contest_address PK "on-chain contest manager address"
       int interval "recurrent contest interval, 0 when one-off" 
       datetime created_at

       %% metadata fields
       string name "META: contest name or title"
       string image_url "META: contest image url"
       string funding_token_address "META: optional, provided by admin on creation when community stake funds won't be used"
       number prize_percentage "META: percent of pool used for prize in recurring contests, null otherwise"
       number[] payout_structure "META: set at creation time by admin, pct of pool for prizes"
       bool paused "META: flags when contest is active or paused"
    }

    ContestTopic {
       string contest_address PK, FK
       int topic_id PK, FK
    }

    Contest {
      string contest_address FK "on-chain contest manager address"
      int contest_id PK "on-chain recurrent contest id, 0 when one-off"
      datetime start_time 
      datetime end_time
      json[] winners "nullable, ranked contest-winning creator addresses and prize in contest currency"
    }

    ContestAction {
      string contest_address PK,FK "on-chain contest manager address"
      int contest_id PK,FK "on-chain recurrent contest id, 0 when one-off"
      int content_id PK "on-chain content id"
      int thread_id FK "to threads - this might be optional when we support other types of content"
      string actor_address PK "actor address"
      enum action PK "added, upvoted, etc - action in PK will allow same address to add, vote, etc"
      string content_url "this is the url of participating threads (or any other content)"
      number voting_power "voting power of address when action was recorded"
      datetime created_at
    }
```

### Queries
> :bangbang: _Queries should not raise non-auth related errors, instead return empty or filtered result sets... there might be exceptions to this rule_

#### 🟩 GetAllContests

- [x] **Path** - `/libs/model/src/contest/GetAllContests.query.ts`

- [x] **Authorization**
    
    - public
 
- [x] **Schema (in/out)** - `/libs/core/src/schemas/queries/contests.schemas.ts`
   
   - filters: community_id, running? (only active contest), contest_id?
   - validation: community_id: int, running: optional bool, contest_id: optional int
   - pagination: no pagination
   - response: 
      - all the fields in contest manager, contest, and contest actions
      - include topic name and thread name
      - sorted alphabetically, grouped by active/inactive

- [x] **Routing** - `GET /api/v1/contests.getAll`

## Unit Testing

- [x] **Path** - `/libs/model/test/contests-projection-lifecycle.spec.ts`

- Happy Path
  - Given: a stream of events gets projected on two contests (recurring and one-off)
  - When: a winner recorded event gets projected
  - Then: a query of the winner contest should reflect all events, and both contests should be projected
- Sad Path
  - When: a contest deployed event with a non-existing namespace
  - Then: should raise invalid state exception - the system should not get to this state

**Comment by Rotorsoft** [comment]
@masvelio - this ticket is to track the remaining contest related items, mainly queries and the new contest manager metadata. CC: @rbennettcw @ianrowan @egetekiner @kurtisassad 

Questions:
1. Please review the data schema and let's chat... considering new mutable attributes (name, image url, payout structure, and paused) ... anything missing?
2. We need to define the type of payout structure - array or json? Can this change after contest starts?
3. Contest topics table to link participating topics - same question about changing after contest starts
4. This schema requires the on-chain contest manager address as the PK, thus "**the UI must be able to get this address before invoking the command to create the metadata**"... there is a tiny chance to fail this operation after the contract has been created on chain, and we might recover by projecting the creation events with some default placeholders for name and image url... thoughts? 
5. We are projecting `content_url` in contest actions as the only identifier for the UI to link actions to threads (or any other content) ... we might need another projection table (ContestThreads) to build these links at projection time (to optimize query performance)

**Comment by masvelio** [comment]
1. Missing:

### ContestManager
  - `funding token address` - address that can be provided by the admin while contest is being created, when community stake funds won't be used
  
<img width="799" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/1611808b-90de-4673-8f68-982956242821">

- `prize percentage` - number of percent that is used for the prize in recurring contest. I need this available to be able to show it in `edit contest view`. However, it is not possible to change it, I need to show what value has been chosen on contest creation.
  
<img width="604" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/a336792c-57cc-45a1-ad1a-96629233a683">

- ` finish date` - not sure if we should compute it on the backend side or it should be calculated on the front end with the equation `created_at +  7_days - now()`

### ContestTopic
- would be good to add also `name` along with `id`. It will be easier for me to display it on the frontend 

### Thread
- we need to be able to filter threads by contest ([figma](https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=381%3A6709&mode=design&t=eodrA7Geow0LsMNl-1))([ticket](https://github.com/hicommonwealth/commonwealth/issues/7302)) so this requires adding contest information to the thread model
-  we need to be able to show the badge next to the thread name ([figma](https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=304%3A10208&mode=design&t=eodrA7Geow0LsMNl-1))([ticket](https://github.com/hicommonwealth/commonwealth/issues/7300)). For this we need
    - Contest Name,
    - Date Contest Won,
    - Round of Contest (if recurring Contest).
--- 

 2. Payout structure CAN NOT be changed after contest starts. I need payout structure in two places
  - first is in `edit contest view` - not possible to modify but has to be presented to the admin in a way how he defined it in the creation contest process. Here I need only percentage value for each prize (min 1 prize, max 10 prizes). 
  
<img width="584" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/7f29b890-ffa0-454e-a8c0-5d1d5180a27b">

  - second is in `contest card` - here instead of percentage value, I need actual ETH (or other currency) value for each prize.  For me, ideally, it should be array of type:
  `Array<{index: number, percentage: number, value: number, denomination: string}>` but I am not sure how and when the percentage => currency conversion will happen.  
  
  
<img width="559" alt="image" src="https://github.com/hicommonwealth/commonwealth/assets/14819225/95f6e193-47c3-4c32-b4c4-4d3422b2ebce">

--- 
  
3. Topics CAN be modified after contest starts.

--- 

4. I am not sure if I follow that and how/when this affects UI. Let's discuss on call

--- 

5. I think it's related to the point 1 above `missing / thread` part.
