### ISSUE TITLE
Enable Farcaster Contest 

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#7661]
### Description

An admin of a community that has contests enabled should be able to launch a Farcaster contest from within Common. Once they have created a contest, they should be able to get a link for a Farcaster frame which they can post on Farcaster

### Project Owner

@sachben91 

### Bucket ID

https://github.com/hicommonwealth/commonwealth/issues/7659

### User Stories / Acceptance Criteria
- User should be able to choose between Common Contest and Farcaster Contest when they launch contests
- On selecting Farcaster Contest, the user should be able to add the following details that do not exist for Common contests: Description for the contest, select a duration for the contest between 1 and 7 days
- When signing the transaction for the contest launch, the user will not be able to redirect fees for Community Stake for Farcaster contests
- Once the contest is created, a Farcaster frame should be generated which the user can then share within Farcaster 
- The replies to the cast that contain the Farcaster frame for the contest will get added as entries into the contest 

### Design Devlink
[Enable Farcaster Contest flow](https://www.figma.com/file/NNqlhNPHvn0O96TCBIi6WU/Contests?type=design&node-id=713-8432&mode=design&t=9wt0BQAT5B9yI7xl-0)

### Design Screenshot

<img width="765" alt="Screenshot 2024-05-03 at 2 05 08 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/d6d03ae0-6799-4437-a7ef-09bee701f536">
<img width="777" alt="Screenshot 2024-05-03 at 2 05 42 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/38bcac07-8258-44a5-bcd2-ac231460f5bf">
<img width="755" alt="Screenshot 2024-05-03 at 2 05 53 PM" src="https://github.com/hicommonwealth/commonwealth/assets/38763242/9aefdb8a-275d-49b7-8b54-6d3ef5978ffd">

### Additional Context

- Contest mechanism for adding replies to the cast needs a separate back end ticket

**Comment by masvelio** [comment]
@sachben91 @jaybe78 missing things :
- copy for contest type selection cards 
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/37f869c1-fe9d-4343-9427-d38478fd4fa7)

- we might want to modify header copy depending on the common vs farcaster contest (mainly because of the possible contest duration change)
![image](https://github.com/hicommonwealth/commonwealth/assets/14819225/3f8a77bf-e296-4697-be34-cc45fcfc8e0c)

And additional question:
- what happens if the user clicks `copy farcaster frame`? Is this a link or some code snippet or what exactly will be copied?
