### ISSUE TITLE
Check if notifications-page can break Users SSO login flow

### ISSUE THREAD

**Issue by kurtisassad** [hicommonwealth/commonwealth#7851]
## Describe the bug
Right now we store the user email from SSO in the Users table. If a User changes their email in the /notifications-settings page, will this break their login flow with their old email? If it does we should probably surface this with product and decide how to handle it, becuase right now it is not obvious from the GUI.

Also since the JWT contains their user.email, if their email changes, this will invalidate the email portion of the JWT. If we are using this email field in any backend routes, things could break because this will be out of date until a new JWT is issued after the email change.

**Comment by ForestMars** [comment]
Really great that you surfaced this here Kurtis! 🙏

**Comment by timolegros** [comment]
Here are my findings:
- If a user updates their email after a JWT has been created this does not invalidate the JWT because when validating the user we search for a user with a matching `id`. Technically, we could search for a user with a matching `id` _and_ `email` and this would mean that a user updating their email would break authentication (requires JWT refresh).
- It is no longer possible to update your email from the notification settings page so it is not possible to break your SSO flow.

Recommended course of action: remove `email` from the JWT.
