### ISSUE TITLE
Prize/Votes always shows zero

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#8073]
Parent ticket: #7724 

When using the `getContestScore` protocol helper util on a recurring contest, the prize/votes all show as zero even when votes have been added to content on the contest.

The expected behavior is that the util should return the current winners with prize and votes during the contest.

**Comment by Rotorsoft** [comment]
[
  {
    "prize": "0",
    "votes": 0,
    "content_id": "0",
    "creator_address": "0x679d5cB3D7d2cB7eEdCa922f04514517e589581C"
  },
  {
    "prize": "0",
    "votes": 0,
    "content_id": "1",
    "creator_address": "0xF4F797774FC8B617202455F8373836DA3a8656bc"
  },
  {
    "prize": "0",
    "votes": 0,
    "content_id": "2",
    "creator_address": "0xF4F797774FC8B617202455F8373836DA3a8656bc"
  }
]

**Comment by egetekiner** [comment]
Hi @rbennettcw @Rotorsoft ,

After investigating the issue, I identified that the votes and prizes are showing as zero because the voters do not hold any tokens in the specified namespace. The NamespaceVoteStrategy contract calculates voting power based on the token balances held within the namespace, multiplied by a specified weight. If a voter has a zero balance, their voting power will also be zero, resulting in zero votes.

**Findings**

1. Voting Power Calculation:

- The voting power is determined by the product of the voter's token balance and the configured weight for the contest.

- In the transactions provided, the voter 0xf4f797774fc8b617202455f8373836da3a8656bc has a zero token balance in the namespace, leading to zero voting power.

2. Verified Transactions:

- Tx Hash: [0x713c8d2d2e4a4ab2291d4de62f64e5514c6269ee588d10c8890ed927f31e3303](https://sepolia.basescan.org/tx/0x713c8d2d2e4a4ab2291d4de62f64e5514c6269ee588d10c8890ed927f31e3303)

```
{
  "name": "voteContent",
  "params": [
    {
      "name": "voter",
      "value": "0xf4f797774fc8b617202455f8373836da3a8656bc",
      "type": "address"
    },
    {
      "name": "id",
      "value": "3",
      "type": "uint256"
    }
  ]
}
```

Balance of voter (0xf4f797774fc8b617202455f8373836da3a8656bc) = 0

- Tx Hash: [0x9efada1b73a533922537f3ced6ee311426bc69c645c7a0d88fe860aaa7b048a8](https://sepolia.basescan.org/tx/0x9efada1b73a533922537f3ced6ee311426bc69c645c7a0d88fe860aaa7b048a8)

```
{
  "name": "voteContent",
  "params": [
    {
      "name": "voter",
      "value": "0xf4f797774fc8b617202455f8373836da3a8656bc",
      "type": "address"
    },
    {
      "name": "id",
      "value": "2",
      "type": "uint256"
    }
  ]
}

```

Balance of voter (0xf4f797774fc8b617202455f8373836da3a8656bc) = 0

Note: You can use the [link](https://bia.is/tools/abi-decoder/) to decode any transaction input with the associated contract's ABI. 

**Resolution**

To resolve this issue, ensure that voters hold the required tokens in the namespace associated with the contest.

Please let me know if there you fold have any further question(s) or comments :)

**Comment by Rotorsoft** [comment]
Just wondering if we should allow voting on content covered by a running contest when you don't have any voting power?

**Comment by egetekiner** [comment]
I believe we should ask this question to @zakhap or maybe Harris.

Additionally, we can implement different voting strategies and allow users to select which one of them they will want to use. The main point is, the voting strategy cannot be changed after the contest started.

**Comment by rbennettcw** [comment]
@egetekiner Here's what we see:
- I bought stake and voted on a thread– it correctly showed voting power in the score:
  - Contest address: `0xb2C8268EAaEe4A69655c3DD5df06fE4D2624A292`
- When Roger bought stake and voted on a thread– it showed zero voting power:
  - Contest address: `0x8bc4C4F907193B615C61C8999B5E94cc2D840fec `

Could you check and confirm if the contract is correctly tracking voting power?

**Comment by egetekiner** [comment]
@rbennettcw 

I just checked in my local environment and yes, the contract is keeping the records of the votes. 

Here is the output I have:

```
Content ID: 0
URL: /contesting/discussion/17180
Cumulative Votes: 0
Creator: 0x679d5cB3D7d2cB7eEdCa922f04514517e589581C
Completed: False

Content ID: 1
URL: /contesting/discussion/17181
Cumulative Votes: 3
Creator: 0xF4F797774FC8B617202455F8373836DA3a8656bc
Completed: False

Content ID: 2
URL: /contesting/discussion/17182
Cumulative Votes: 3
Creator: 0xF4F797774FC8B617202455F8373836DA3a8656bc
Completed: False

Content ID: 3
URL: /contesting/discussion/17183
Cumulative Votes: 3
Creator: 0xF4F797774FC8B617202455F8373836DA3a8656bc
Completed: False

Content ID: 4
URL: /contesting/discussion/17184
Cumulative Votes: 3
Creator: 0x679d5cB3D7d2cB7eEdCa922f04514517e589581C
Completed: False

Content ID: 5
URL: /contesting/discussion/17185
Cumulative Votes: 3
Creator: 0x679d5cB3D7d2cB7eEdCa922f04514517e589581C
Completed: False

Content ID: 6
URL: /contesting/discussion/17186
Cumulative Votes: 0
Creator: 0x679d5cB3D7d2cB7eEdCa922f04514517e589581C
Completed: False
```

and here is the output of the helper:

```
Contest Scores: {
  scores: [
    {
      winningContent: 3n,
      winningAddress: '0xF4F797774FC8B617202455F8373836DA3a8656bc',
      voteCount: 3n
    },
    {
      winningContent: 4n,
      winningAddress: '0x679d5cB3D7d2cB7eEdCa922f04514517e589581C',
      voteCount: 3n
    },
    {
      winningContent: 2n,
      winningAddress: '0xF4F797774FC8B617202455F8373836DA3a8656bc',
      voteCount: 3n
    }
  ],
  contestBalance: '0.'
}
```

Both outputs are matching right now in my end. If you would like to, we can setup a quick meet to go over the issue.

**Comment by Rotorsoft** [comment]
Looks like the issue is that the contest balance is zero

**Comment by Rotorsoft** [comment]
Guess another question for product team: Should we allow voting on contests with no balance?

**Comment by rbennettcw** [comment]
Closing this since it's resolved from a technical standpoint. Maybe we can find another channel to communicate UI/UX changes to product.
