### ISSUE TITLE
Optimizations for recent activity in /api/status 

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#824]
Currently we retrieve the full thread data, including body text, version history, etc for each recent thread and recent comment in the /api/status request. This increases the size of the request significantly (it's 1.5MB for Edgeware on my local machine). We should adjust the query and maybe the associated frontend typings too, to only include data that is required.

**Comment by gdjohnson** [comment]
This makes sense to me. I think it would be good to have a specific modelFromServer function that's meant for abbreviated thread objects, because we also run into this with loading threads/comments on the community-scale... Where all that's really needed is 1) a list of thread titles/slugs/ids for links, and 2) a list of addresses in the "conversation" + comment count. I'll build this out!
