### ISSUE TITLE
Kusama decimals incorrectly set in chain-events

### ISSUE THREAD

**Issue by raykyri** [hicommonwealth/commonwealth#894]
0 KSM bonded/unbonded events are triggered whenever someone bonds/unbonds a small amount of KSM (look up a block number), 1 KSM bonded/unbonded events are triggered whenever someone bonds/unbonds ~1000 KSM, etc.

**Comment by jnaviask** [comment]
That's interesting because chain-events doesn't even attempt to look up decimals. Here's the enricher code (note that `event.data` are the data passed via the native substrate event):

```
 case EventKind.Bonded:
      case EventKind.Unbonded: {
        const [ stash, amount ] = event.data as unknown as [ AccountId, Balance ] & Codec;
        const controllerOpt = await api.query.staking.bonded<Option<AccountId>>(stash);
        if (!controllerOpt.isSome) {
          throw new Error(`could not fetch staking controller for ${stash.toString()}`);
        }
        return {
          includeAddresses: [ stash.toString() ],
          data: {
            kind,
            stash: stash.toString(),
            amount: amount.toString(),
            controller: controllerOpt.unwrap().toString(),
          }
        };
      }
```

Not sure where we could be losing accuracy, because we go straight to string and leave it. Or is this just at the view level? We have KSM decimals hardcoded to 15.

**Comment by raykyri** [comment]
That must be it:

![image](https://user-images.githubusercontent.com/1273926/96043998-949f2000-0e24-11eb-85a6-acb904c1790c.png)

polkadot.js shows EDG as having 18 decimals, which is in agreement with filters/labeler.ts.

**Comment by jnaviask** [comment]
Should be an easy fix, will push a patch shortly.
