### ISSUE TITLE
Implement Eligibility Check for Farcaster Frame

### ISSUE THREAD

**Issue by rbennettcw** [hicommonwealth/commonwealth#8982]
One of the farcaster contest frames shows the user if they're eligible to enter a contest.

In order to detect eligibility, we need to check if the user's address is connected to farcaster. This may required using Neynar to pull account info about the user who requested the frame.

## Acceptance Criteria
- Implement an eligibility check on the frame that the returns true or false based on the user's connectivity to farcaster

**Comment by rbennettcw** [comment]
cc @masvelio if you have any additional comments about this

**Comment by masvelio** [comment]
- instead of `fakeApiCall`, you need to evaluate eligibility [here ](https://github.com/hicommonwealth/commonwealth/blob/6eb7775c3e683cbafb362e4f1726f0406279ff28/packages/commonwealth/server/farcaster/frames/contest/checkEligibility.tsx#L11)
- try to find some data in context that is available as a param 
```
export const checkEligibility = frames(async (ctx) => {
  console.log('ctx', ctx);
   ...
  });
```
- run debbuger locally and try to login as this might get us some additional data. Having warpacast account created will be very useful
 
![image](https://github.com/user-attachments/assets/3575bfaf-52a6-48a6-8057-d16298deed2f)
