### ISSUE TITLE
Use Community Stake for weighted voting screen

### ISSUE THREAD

**Issue by sachben91** [hicommonwealth/commonwealth#9065]
### Description

If the user chooses to enable weighted voting using community stake at the topic level and community stake has already been enabled for the community, then the user should be taken to a screen that shows the details of the community stake that has already been enabled 

### Project Owner
@sachben91 
### Bucket ID

#8805 
### User Stories / Acceptance Criteria

- When the user selects "use community stake" for the weighted voting option and the community already has stake enabled, then they should be taken to a screen that contains details about the existing community stake. 
- The screen will have the following details: community namespace, symbol, amount of stake and vote weight the user owns and current value of the stake 
- none of the details should be editable 
<img width="558" alt="Screenshot 2024-08-29 at 12 30 30 PM" src="https://github.com/user-attachments/assets/8ac745f2-4674-4742-850c-e1ee29179b45">

### Design Devlink

[Figma](https://www.figma.com/design/DZ5IN1p0QUxpwd0csJRuvv/Contest-V2?node-id=382-30424&node-type=FRAME&t=ATGawOrkkNVuKhRs-0)

**Comment by masvelio** [comment]
@sachben91 Currently we have in the app the view accessible from `admin menu => integrations => stake` which shows information about stake when it is enabled. It looks like this 

video of current implementation:

https://github.com/user-attachments/assets/b9afe426-3dc6-49fb-ad57-f014a2e4d765

image of current implementation:
![image](https://github.com/user-attachments/assets/b502d118-59a6-4edd-ba8b-a92264c09219)


---
**However designed view for enabled community stake looks a bit different** 


---


image of new design:
![image](https://github.com/user-attachments/assets/e1ccab85-5072-480e-9869-cb1cb2c620a0)

We should show the same view both from the create topic flow and integrations menu, just to be consistent for the user + to be able to reuse the same components for developers. So there are three options
1. We use the one integrations 
2. We use the one from new design
3. We will merge two views because they look slightly different but it would require some work from designer in order to redesign it a bit.

**Comment by sachben91** [comment]
@masvelio we should just go with option one and use the view that we already have.
