### ISSUE TITLE
Update In App Notifcations Display to Design

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#9422]
### Description

Update the Knock In App Provider to the Designs Below

### Project Owner

@sachben91 

### Design Screenshot

<img width="229" alt="image" src="https://github.com/user-attachments/assets/a46f09b7-b955-4d26-9839-783b82f881e0">

- Keep the Mark as Read Button that's provided via the Application and use our design system Normal font
- Clicking Settings should take you to managing notifications settings
- See All should be removed on desktop (we don't have designs for the display of a full notifications page)

### Design Devlink

[Figma 1](https://www.figma.com/design/WdlVQRpQKg4GMgCOzbQt34/Notifications?node-id=440-6479&t=mm77gRMAsOpawz37-4) and [Figma 2](https://www.figma.com/design/WdlVQRpQKg4GMgCOzbQt34/Notifications?node-id=27-7316&t=mm77gRMAsOpawz37-4)

**Comment by burtonator** [comment]
This one is a bit complicated and wanted some guidance here.

Right now we just use the standard Knock in-app notification widget.  

Here's a screenshot of the current control:

![CleanShot 2024-10-03 at 12 40 35@2x](https://github.com/user-attachments/assets/05291643-1819-4dc4-9f83-38cfff7f1d2c)

This entire thing is implement in the Knock React SDK which is what was requested for us to implement when I started working on the React / Knock SDK.

One thing I didn't consider is dark/light mode.  

This design calls for a 'muted' color for the text of the message.

![CleanShot 2024-10-03 at 12 43 58@2x](https://github.com/user-attachments/assets/c09ea7a4-6ba5-4ecf-8e95-a97257bc3f97)

The problem is that this might change in dark mode. I'm not sure dark grey would look good on black.  

Plus I would have to hard code the colors in the template.

Knock has a basic "brand color" but not real light/dark mode toggle or colors associated with them.

If we want to use the templates, we have to verify that we're sending our user image icon / avatar:

<img width="826" alt="image" src="https://github.com/user-attachments/assets/619c79a1-632f-4042-805c-2bf5deb5ab0d">

![CleanShot 2024-10-03 at 12 39 23@2x](https://github.com/user-attachments/assets/1e4902b1-3faf-4997-a1dd-f29f8813e202)

### Potential Solutions.

I think in order to do this we'd either have to:

## Templates

Use the Knock templates. Hard code the color. Have a less than ideal dark mode. Make sure we're sending the avatar URL.

**pros**: Get it done faster at the downside of having to send the avatar URL and less ideal dark mode.  
**cons**: less customizable, we have to go through their template system, and we can't use native components in our app

## Re-implement as React Component

Completely re-implement the Knock React SDK to use the hook, not the pre-built component.  

**pros**: Full control over message display, better features like adding the settings link in the notifications, full dark mode support, we can use native components. Don't need the avatar URL sent to Knock

**cons**: Will take 1-2 days to implement.  Hopefully less but I also have to test it and make sure the dialog functionality works.
