### ISSUE TITLE
BUG: Discussion page crashes on some communities 

### ISSUE THREAD

**Issue by ilijabojanovic** [hicommonwealth/commonwealth#9825]
## Describe the bug

When user navigate on community, Discussion page crashes.
### Initial conditions

**Environment:** 

QA
**Branch/Release version:** 

Master/release/v1.7.3-x
**Browser:** 

All
**Wallet:** 

All
## Reproduction steps

1. Go to: https://qa.commonwealth.im/
2. Sing in
3. Navigate to https://qa.commonwealth.im/october/ or https://qa.commonwealth.im/common/archived
## Actual behavior

Page crashes 
```
ThreadOptions-Bt4Z72Zw.js:4 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at Gt (ThreadOptions-Bt4Z72Zw.js:4:25012)
    at KA (index-CXALuvZi.js:142:414)
    at sI (index-CXALuvZi.js:158:10880)
    at rw (index-CXALuvZi.js:160:12831)
    at HTMLUnknownElement.Rl (index-CXALuvZi.js:77:33827)
    at HTMLUnknownElement.c (rocket-loader.min.js:1:9405)
    at Object.Qf (index-CXALuvZi.js:77:34177)
    at Vd (index-CXALuvZi.js:77:35160)
    at x8 (index-CXALuvZi.js:177:2436)
```
## Screenshots / Video

https://app.screencast.com/dCIJHaXBUOKeN

**Comment by timolegros** [comment]
The root of the issue is having threads that don't have an associated topic. To resolve this issue we need to make `Thread.topic_id` required. To do this we must introduce per-topic archival (replaces topic deletion)

# Topic Archival
1. New `archived_at` column in `Topics` table
2. Update `DeleteTopic.command` to `ArchiveTopic.command`
    - Set `archived_at` for the topic and all threads associated with that topic
    - Requires client changes both for references but also in copy (e.g. updated modal + do we show archival topics in Manage Topics?)
3. Update `UpdateTopic.command` to prevent updates on archived topics (except for unarchival?)
4. Potentially update `GetTopics.query`
    - Archived topics should not be returned by default so that they don't show up in Group or Contest forms. We need to be mindful of caching responses that include archived topics so they don't carry over from Manage Topics to other forms (if we display archived topics in Manage Topics).
5. Update whatever queries load all topics + threads on initial community load to exclude archived topics.

# TBD
- What do we do with existing soft deleted topics?
- What do we do with existing threads without topics?
