### ISSUE TITLE
Enable User to Pin Token in any Community

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/commonwealth#9898]
### Description

A community should be able to pin a token in any community, even if not the launchpad community (for example 1inch). 

Once admins pin the token, users should be able to swap in and out of the asset using the Uniswap Modal.

### User Stories / Acceptance Criteria

- Admin is able to pin token from the integration page
- User is able to swap using #9887, it should default to a pool address that is ETH - [asset], and on the chain that the community is deployed on.
- User is able to to see in sidebar the token that has now been pinned.

### Design Devlink

Admin Flow Figma: https://www.figma.com/design/1b9wbqv9YV2FlU2svFyf0I/IdeaCoin?node-id=830-44750&t=HTEIkJjSlAt79J10-4

Swap Flow (same as #9887)

### Design Screenshot

<img width="456" alt="image" src="https://github.com/user-attachments/assets/50bdb88e-2a77-4c03-b3f0-50694d92c33c">

**Comment by timolegros** [comment]
Per request from @mzparacha: platform work here includes:
- [ ] Rename `Tokens` table/model to `LaunchpadTokens`
- [ ] Create a new `Tokens` table which maps external tokens to communities
- [ ] Create new query route to get these tokens
- [ ] (potentially) Add "supported chains" according to Alchemy Transfers API supported chains intersection with Uniswap deployments

@dillchen will transactions of these tokens be included in the My Transactions page? If so it may be best to limit chains to those supported by Alchemy Transactions API otherwise we will 100X the number of transactions we index internally (might then need to handle CE/Postgres scaling issues).

**Comment by mzparacha** [comment]
A few questions
1. Only Ethereum communities can pin tokens?
2. What a token is pinned to community, what are the management options for the admin? Can admin remove the pinned token?
<img width="414" alt="image" src="https://github.com/user-attachments/assets/5a94bec7-38a5-4149-ba5b-e8b76f31d8ed">
3. Can a community have a pinned token and a community token at the same time? If only 1 token is allowed the what happens if a token community admin wants to pin an external token, do we block him or something?
4. Where does this link redirect to?
<img width="373" alt="image" src="https://github.com/user-attachments/assets/f39f9c08-2070-483b-bb87-9b1f433b8897">


cc: @dillchen

**Comment by dillchen** [comment]
Answer for @timolegros 

> @dillchen will transactions of these tokens be included in the My Transactions page? If so it may be best to limit chains to those supported by Alchemy Transactions API otherwise we will 100X the number of transactions we index internally (might then need to handle CE/Postgres scaling issues).

Yes. Let's try to limit as much as possible to the Alchemy API surface area

**Comment by dillchen** [comment]
For @mzparacha 

> Only Ethereum communities can pin tokens?

For now yes, let's hardcode this in for EVM specific chains (or chains in which we support the swap module for). In short order (early Q1, we want to add support for Solana)

> Only 1 external token can be pinned to a community?

Yes

> When a token is pinned to community, what are the management options for the admin? Can admin remove the pinned token or add a different token?

They can update it, 1) remove it 2) change to different one
