### ISSUE TITLE
🟪 Referral Manager

### ISSUE THREAD

**Issue by Rotorsoft** [hicommonwealth/commonwealth#9999]
## Description
Implement a Referral Manager policy to collect XP points when platform referral events are emitted.

- Can also be directly implemented in referrals projection!

https://docs.google.com/spreadsheets/d/1LL8jGRwCaqrG_bpYW5WW3CfjN-vVEYkIbvY91Bwg4-g/edit?gid=2005659128#gid=2005659128

## Stakeholders

| Product   | Engineering |
| --------- | ----------- |
| @dillchen      |  @Rotorsoft       |

## Model
[Referral Manager](https://miro.com/app/board/uXjVNZ8oB3U=/?moveToWidget=3458764605019145524&cot=14)

## Engineering Requirements

1. **Integration**
   - RabbitMQ integration
2. **Routing**
   - internal
3. **References**
   - Event payloads (Initially CommunityCreated, SignInFlowCompleted)
4. **Business Rules**
   - Implement protocol service "command" that collects on-chain referral fees
5. **Response**
   - ack event or throw if protocol service fails

## Unit Testing
- Referral lifecycle should be able to collect fees and process the resulting event back to the UserReferrals projection

**Comment by timolegros** [comment]
1. Add `User.referral_earnings`
2. Add all fee distributed in a new model + write query to get earnings by user
3. Index ReferralSet in Referrals table by addresses

**Comment by timolegros** [comment]
Remaining TODOs:
- [ ] Update queries to handle ETH vs non-ETH fees
- [ ] Update GetUserReferrals.query
- [ ] Update ETH earnings counters in Users/Referrals

**Comment by timolegros** [comment]
This ticket is blocked until I follow up with @Rotorsoft about referral links and the `UserReferrals` projection. It seems that referral links should reference user addresses rather than IDs since otherwise, we can't provide an address as the referral when creating the namespace. Additionally, I'm not sure whether we need to track referral events that aren't associated with a fee distribution event such as `SignUpFlowCompleted`.

**Comment by timolegros** [comment]
From a conversation with @Rotorsoft:
1. Remove `User.referral_link` since referral links are just user addresses now
2. Remove Queries/Commands related to referral links
3. Update `Referrals` model to have a generic primary key and a unique index on eth chain id + txn id
4. Update `UserReferrals.projection` to only handle the `SignUpFlowCompleted` event -> should create an "incomplete" Referrals record (without txn)
5. Update `ReferralSet` handle to create or complete an incomplete Referrals record
